# -*- coding: utf-8 -*-
"""Authentic Carciofi alla romana (artichauts a la romaine) x4 languages."""
from recipe_render import write_cluster

C = {}
C["fr"] = dict(
    title="Artichauts à la romaine (Carciofi alla romana) : la vraie recette à l'huile d'olive",
    desc="Vrais carciofi alla romana : artichauts braisés à l'huile d'olive, ail, persil et menthe, à la façon romaine. Comment tourner les artichauts, cuisson à l'étouffée et service.",
    h1="Artichauts à la romaine (Carciofi alla romana)",
    lede="Les carciofi alla romana sont des artichauts entiers, parés jusqu'au cœur tendre, farcis d'ail, de persil et de menthe romaine, puis braisés doucement à l'huile d'olive. Un classique du Latium, fondant et parfumé.",
    info="<strong>Préparation :</strong> 30 min · <strong>Cuisson :</strong> 40 min · <strong>Pour :</strong> 4 personnes · <strong>Cuisine :</strong> italienne (Rome) · <strong>Difficulté :</strong> moyenne",
    intro="À Rome, on utilise les artichauts « mammole » ou « romaneschi », ronds et sans foin. La recette repose sur deux gestes : bien parer l'artichaut jusqu'à sa partie tendre, puis le braiser lentement dans l'huile d'olive avec de l'eau, tête en bas, jusqu'à ce qu'il fonde. La menthe romaine (mentuccia) fait la signature aromatique.",
    ingredients=[
        "4 gros artichauts ronds (type romanesco, sans foin)",
        "2 gousses d'ail",
        "1 bouquet de persil plat",
        "Quelques feuilles de menthe (idéalement mentuccia romaine)",
        "1 citron (pour éviter l'oxydation)",
        "100 ml d'huile d'olive extra vierge",
        "Sel, poivre, eau (et un peu de vin blanc, facultatif)",
    ],
    steps=[
        "<strong>Tourner les artichauts.</strong> Retirez les feuilles extérieures dures, coupez la pointe, et parez le cœur en gardant une tige de 4-5 cm épluchée. Frottez au citron et plongez dans l'eau citronnée pour qu'ils ne noircissent pas.",
        "<strong>Préparer la farce.</strong> Hachez l'ail, le persil et la menthe avec du sel et du poivre. Ouvrez légèrement le centre de chaque artichaut et garnissez-le de ce mélange.",
        "<strong>Ranger dans la cocotte.</strong> Placez les artichauts tête en bas, bien serrés, dans une cocotte où ils tiennent debout.",
        "<strong>Braiser.</strong> Versez l'huile d'olive extra vierge et de l'eau (à mi-hauteur des artichauts), plus un filet de vin blanc si vous voulez. Salez. Couvrez et laissez cuire à feu doux 30 à 40 min, jusqu'à ce qu'une pointe de couteau s'enfonce sans résistance.",
        "<strong>Servir.</strong> Servez tièdes ou à température ambiante, arrosés du jus de cuisson à l'huile d'olive, avec du pain.",
    ],
    oil="Ici, l'huile d'olive est le milieu de cuisson : elle confit lentement l'artichaut et se charge de son parfum et de la menthe. Utilisez une <strong>extra vierge de bonne qualité</strong>, en quantité généreuse — le jus huileux fait partie du plat. Un filet cru à la fin renforce le goût.",
    tips=[
        "Parez bien l'artichaut : seule la partie tendre doit rester, sinon c'est fibreux.",
        "L'eau citronnée évite que les cœurs noircissent pendant l'épluchage.",
        "Cuisez doucement à couvert : c'est un braisé, pas une friture.",
        "La menthe (mentuccia) est la signature romaine ; à défaut, menthe douce + persil.",
    ],
    variations=[
        "<strong>Sans menthe :</strong> persil et ail seuls, façon plus simple.",
        "<strong>Au vin blanc :</strong> un trait de vin blanc dans le liquide de braisage.",
        "<strong>Carciofi alla giudia :</strong> version romaine différente, artichauts frits et croustillants (autre recette).",
    ],
    serve="Servez les artichauts à la romaine en entrée ou en accompagnement, tièdes ou à température ambiante, nappés de leur huile de cuisson, avec du pain pour saucer. Ils accompagnent aussi très bien un poisson ou une viande blanche.",
    store="Ils se conservent 2 à 3 jours au réfrigérateur dans leur huile de cuisson, et sont même meilleurs le lendemain. Sortez-les à l'avance : le froid fige l'huile d'olive.",
    faqs=[
        ("Quels artichauts pour les carciofi alla romana ?",
         "Des artichauts ronds et charnus, sans foin, type romanesco (« mammole »). À défaut, de gros artichauts globe bien tendres, soigneusement parés jusqu'au cœur."),
        ("Comment parer (tourner) un artichaut ?",
         "Retirez les feuilles dures extérieures, coupez la pointe, épluchez la tige et gardez uniquement la partie tendre. Frottez au citron et plongez dans l'eau citronnée pour éviter le noircissement."),
        ("Quelle est la différence avec les carciofi alla giudia ?",
         "Les alla romana sont braisés entiers à l'huile d'olive avec des herbes ; les alla giudia (romano-juifs) sont frits jusqu'à devenir croustillants. Deux recettes romaines distinctes."),
        ("Quelle herbe utiliser ?",
         "La menthe romaine, la mentuccia, est traditionnelle. À défaut, un mélange de menthe douce et de persil donne un résultat très proche."),
        ("Peut-on les préparer à l'avance ?",
         "Oui, ils gagnent même en saveur : conservez-les dans leur huile de cuisson et ramenez-les à température ambiante avant de servir."),
    ],
    schema_name="Artichauts à la romaine (Carciofi alla romana)",
    schema_desc="Vrais carciofi alla romana : artichauts braisés à l'huile d'olive avec ail, persil et menthe romaine.",
    schema_ing=["4 gros artichauts ronds", "2 gousses d'ail", "persil plat", "menthe (mentuccia)",
                "1 citron", "100 ml huile d'olive extra vierge", "sel, poivre, eau, vin blanc facultatif"],
    schema_steps=[
        "Parer les artichauts jusqu'au cœur tendre, frotter au citron.",
        "Préparer une farce d'ail, persil et menthe et en garnir le centre.",
        "Ranger les artichauts tête en bas dans une cocotte.",
        "Ajouter huile d'olive et eau, couvrir et braiser 30-40 min à feu doux.",
        "Servir tièdes nappés de leur huile de cuisson."],
    keywords="carciofi alla romana, artichauts à la romaine, artichauts braisés, artichauts huile d'olive, recette artichauts romaine",
    cuisine="Italian", category="Entrée", prep="PT30M", cook="PT40M", total="PT1H10M", yield_="4 servings",
    nutrition={"servingSize": "1 portion", "calories": "180 kcal", "fatContent": "14 g", "proteinContent": "4 g", "carbohydrateContent": "11 g"},
)
C["en"] = dict(
    title="Roman-Style Artichokes (Carciofi alla romana): the real olive-oil recipe",
    desc="Real carciofi alla romana: whole artichokes braised in olive oil with garlic, parsley and Roman mint. How to trim artichokes, the slow braise and how to serve them.",
    h1="Roman-Style Artichokes (Carciofi alla romana)",
    lede="Carciofi alla romana are whole artichokes trimmed to the tender heart, stuffed with garlic, parsley and Roman mint, then braised gently in olive oil. A melting, fragrant classic of Lazio.",
    info="<strong>Prep:</strong> 30 min · <strong>Cook:</strong> 40 min · <strong>Serves:</strong> 4 · <strong>Cuisine:</strong> Italian (Rome) · <strong>Difficulty:</strong> medium",
    intro="In Rome, cooks use round 'mammole' or 'romanesco' artichokes, with no choke. The recipe rests on two moves: trim the artichoke down to its tender part, then braise it slowly in olive oil with water, head down, until it melts. Roman mint (mentuccia) is the aromatic signature.",
    ingredients=[
        "4 large round artichokes (romanesco type, no choke)",
        "2 garlic cloves",
        "1 bunch flat-leaf parsley",
        "A few mint leaves (ideally Roman mentuccia)",
        "1 lemon (to prevent browning)",
        "100 ml extra virgin olive oil",
        "Salt, pepper, water (and a splash of white wine, optional)",
    ],
    steps=[
        "<strong>Trim the artichokes.</strong> Remove the tough outer leaves, cut off the tip, and trim the heart, keeping a peeled 4–5 cm stem. Rub with lemon and drop into lemon water so they don't blacken.",
        "<strong>Make the filling.</strong> Chop the garlic, parsley and mint with salt and pepper. Open the centre of each artichoke slightly and fill with the mixture.",
        "<strong>Arrange in the pot.</strong> Place the artichokes head down, packed tightly, in a pot where they stand upright.",
        "<strong>Braise.</strong> Pour in the extra virgin olive oil and water (halfway up the artichokes), plus a splash of white wine if you like. Season. Cover and cook over low heat 30–40 min, until a knife tip slides in without resistance.",
        "<strong>Serve.</strong> Serve warm or at room temperature, spooned with the olive-oil cooking juices, with bread.",
    ],
    oil="Here olive oil is the cooking medium: it slowly confits the artichoke and takes on its aroma and the mint. Use a <strong>good-quality extra virgin</strong>, generously — the oily juice is part of the dish. A raw drizzle at the end boosts the flavour.",
    tips=[
        "Trim well: only the tender part should remain, or it stays fibrous.",
        "Lemon water stops the hearts browning while you trim.",
        "Cook gently, covered: this is a braise, not a fry.",
        "Mint (mentuccia) is the Roman signature; otherwise mild mint + parsley.",
    ],
    variations=[
        "<strong>Without mint:</strong> parsley and garlic only, a simpler style.",
        "<strong>With white wine:</strong> a splash of white wine in the braising liquid.",
        "<strong>Carciofi alla giudia:</strong> a different Roman version, fried and crispy (another recipe).",
    ],
    serve="Serve Roman-style artichokes as a starter or side, warm or at room temperature, coated in their cooking oil, with bread to mop up. They also pair very well with fish or white meat.",
    store="They keep 2–3 days in the fridge in their cooking oil, and are even better the next day. Take them out ahead: cold sets the olive oil.",
    faqs=[
        ("Which artichokes for carciofi alla romana?",
         "Round, fleshy, choke-free artichokes, romanesco type ('mammole'). Otherwise large, tender globe artichokes, carefully trimmed to the heart."),
        ("How do you trim an artichoke?",
         "Remove the tough outer leaves, cut off the tip, peel the stem and keep only the tender part. Rub with lemon and drop into lemon water to prevent browning."),
        ("What's the difference from carciofi alla giudia?",
         "Alla romana are braised whole in olive oil with herbs; alla giudia (Roman-Jewish) are deep-fried until crisp. Two distinct Roman recipes."),
        ("Which herb should I use?",
         "Roman mint, mentuccia, is traditional. Otherwise a mix of mild mint and parsley gives a very close result."),
        ("Can they be made ahead?",
         "Yes, they even gain flavour: keep them in their cooking oil and bring back to room temperature before serving."),
    ],
    schema_name="Roman-Style Artichokes (Carciofi alla romana)",
    schema_desc="Real carciofi alla romana: whole artichokes braised in olive oil with garlic, parsley and Roman mint.",
    schema_ing=["4 large round artichokes", "2 garlic cloves", "flat-leaf parsley", "mint (mentuccia)",
                "1 lemon", "100 ml extra virgin olive oil", "salt, pepper, water, optional white wine"],
    schema_steps=[
        "Trim artichokes to the tender heart, rub with lemon.",
        "Make a garlic, parsley and mint filling and stuff the centre.",
        "Arrange artichokes head down in a pot.",
        "Add olive oil and water, cover and braise 30-40 min on low heat.",
        "Serve warm coated in their cooking oil."],
    keywords="carciofi alla romana, roman artichokes, braised artichokes, artichokes olive oil, roman-style artichokes recipe",
    cuisine="Italian", category="Appetizer", prep="PT30M", cook="PT40M", total="PT1H10M", yield_="4 servings",
    nutrition={"servingSize": "1 serving", "calories": "180 kcal", "fatContent": "14 g", "proteinContent": "4 g", "carbohydrateContent": "11 g"},
)
C["it"] = dict(
    title="Carciofi alla romana: la vera ricetta all'olio d'oliva",
    desc="Veri carciofi alla romana: carciofi brasati nell'olio d'oliva con aglio, prezzemolo e mentuccia. Come pulire i carciofi, la cottura lenta e come servirli.",
    h1="Carciofi alla romana",
    lede="I carciofi alla romana sono carciofi interi, puliti fino al cuore tenero, farciti con aglio, prezzemolo e mentuccia, poi brasati piano nell'olio d'oliva. Un classico del Lazio, morbido e profumato.",
    info="<strong>Preparazione:</strong> 30 min · <strong>Cottura:</strong> 40 min · <strong>Per:</strong> 4 persone · <strong>Cucina:</strong> italiana (Roma) · <strong>Difficoltà:</strong> media",
    intro="A Roma si usano i carciofi tondi 'mammole' o 'romaneschi', senza barba. La ricetta si basa su due gesti: pulire bene il carciofo fino alla parte tenera, poi brasarlo lentamente nell'olio d'oliva con acqua, a testa in giù, finché è fondente. La mentuccia è la firma aromatica.",
    ingredients=[
        "4 grossi carciofi tondi (romaneschi, senza barba)",
        "2 spicchi d'aglio",
        "1 ciuffo di prezzemolo",
        "Qualche foglia di mentuccia romana",
        "1 limone (contro l'ossidazione)",
        "100 ml di olio extravergine d'oliva",
        "Sale, pepe, acqua (e un po' di vino bianco, facoltativo)",
    ],
    steps=[
        "<strong>Pulire i carciofi.</strong> Togli le foglie dure esterne, taglia la punta e pulisci il cuore lasciando un gambo di 4-5 cm sbucciato. Strofina con limone e immergi in acqua acidulata perché non anneriscano.",
        "<strong>Preparare il ripieno.</strong> Trita aglio, prezzemolo e mentuccia con sale e pepe. Apri leggermente il centro di ogni carciofo e farciscilo.",
        "<strong>Disporre in pentola.</strong> Metti i carciofi a testa in giù, ben stretti, in una pentola dove stanno in piedi.",
        "<strong>Brasare.</strong> Versa l'olio extravergine e l'acqua (a metà altezza dei carciofi), più un goccio di vino bianco se vuoi. Sala. Copri e cuoci a fuoco basso 30–40 min, finché la punta di un coltello entra senza resistenza.",
        "<strong>Servire.</strong> Servi tiepidi o a temperatura ambiente, irrorati con il fondo all'olio d'oliva, con pane.",
    ],
    oil="Qui l'olio d'oliva è il mezzo di cottura: confisce lentamente il carciofo e si carica del suo profumo e della mentuccia. Usa un <strong>extravergine di qualità</strong>, in abbondanza — il fondo oleoso fa parte del piatto. Un filo a crudo alla fine esalta il gusto.",
    tips=[
        "Pulisci bene: deve restare solo la parte tenera, altrimenti è fibroso.",
        "L'acqua acidulata evita che i cuori anneriscano durante la pulizia.",
        "Cuoci piano e coperto: è una brasatura, non una frittura.",
        "La mentuccia è la firma romana; in mancanza, menta dolce + prezzemolo.",
    ],
    variations=[
        "<strong>Senza menta:</strong> solo prezzemolo e aglio, più semplice.",
        "<strong>Con vino bianco:</strong> un goccio nel liquido di brasatura.",
        "<strong>Carciofi alla giudia:</strong> versione romana diversa, fritti e croccanti (altra ricetta).",
    ],
    serve="Servi i carciofi alla romana come antipasto o contorno, tiepidi o a temperatura ambiente, con il loro fondo all'olio, con pane per raccoglierlo. Accompagnano bene anche pesce o carni bianche.",
    store="Si conservano 2–3 giorni in frigo nel loro olio di cottura e sono migliori il giorno dopo. Toglili in anticipo: il freddo rapprende l'olio.",
    faqs=[
        ("Quali carciofi per i carciofi alla romana?",
         "Carciofi tondi, carnosi, senza barba, tipo romanesco ('mammole'). In mancanza, grossi carciofi teneri, puliti con cura fino al cuore."),
        ("Come si pulisce un carciofo?",
         "Togli le foglie dure esterne, taglia la punta, sbuccia il gambo e lascia solo la parte tenera. Strofina con limone e immergi in acqua acidulata."),
        ("Che differenza c'è con i carciofi alla giudia?",
         "Gli alla romana sono brasati interi nell'olio con erbe; gli alla giudia (giudaico-romani) sono fritti fino a diventare croccanti. Due ricette romane distinte."),
        ("Quale erba usare?",
         "La mentuccia romana è tradizionale. In mancanza, un mix di menta dolce e prezzemolo dà un risultato molto simile."),
        ("Si possono preparare in anticipo?",
         "Sì, guadagnano anche in sapore: conservali nel loro olio di cottura e portali a temperatura ambiente prima di servire."),
    ],
    schema_name="Carciofi alla romana",
    schema_desc="Veri carciofi alla romana: carciofi brasati nell'olio d'oliva con aglio, prezzemolo e mentuccia.",
    schema_ing=["4 grossi carciofi tondi", "2 spicchi d'aglio", "prezzemolo", "mentuccia",
                "1 limone", "100 ml olio extravergine d'oliva", "sale, pepe, acqua, vino bianco facoltativo"],
    schema_steps=[
        "Pulire i carciofi fino al cuore tenero, strofinare con limone.",
        "Preparare un ripieno di aglio, prezzemolo e mentuccia e farcire il centro.",
        "Disporre i carciofi a testa in giù in una pentola.",
        "Aggiungere olio e acqua, coprire e brasare 30-40 min a fuoco basso.",
        "Servire tiepidi con il loro olio di cottura."],
    keywords="carciofi alla romana, ricetta carciofi alla romana, carciofi brasati, carciofi olio d'oliva, carciofo alla romana",
    cuisine="Italian", category="Antipasto", prep="PT30M", cook="PT40M", total="PT1H10M", yield_="4 porzioni",
    nutrition={"servingSize": "1 porzione", "calories": "180 kcal", "fatContent": "14 g", "proteinContent": "4 g", "carbohydrateContent": "11 g"},
)
C["el"] = dict(
    title="Αγκινάρες αλά ρομάνα (Carciofi alla romana): η αυθεντική συνταγή με ελαιόλαδο",
    desc="Αυθεντικές carciofi alla romana: αγκινάρες μαγειρεμένες σιγά στο ελαιόλαδο με σκόρδο, μαϊντανό και δυόσμο. Πώς καθαρίζονται, το αργό σιγοβράσιμο και το σερβίρισμα.",
    h1="Αγκινάρες αλά ρομάνα (Carciofi alla romana)",
    lede="Οι carciofi alla romana είναι ολόκληρες αγκινάρες, καθαρισμένες ως την τρυφερή καρδιά, γεμισμένες με σκόρδο, μαϊντανό και δυόσμο, μετά μαγειρεμένες σιγά στο ελαιόλαδο. Κλασικό του Λάτσιο, βουτυράτο και αρωματικό.",
    info="<strong>Προετοιμασία:</strong> 30 λεπτά · <strong>Μαγείρεμα:</strong> 40 λεπτά · <strong>Μερίδες:</strong> 4 · <strong>Κουζίνα:</strong> ιταλική (Ρώμη) · <strong>Δυσκολία:</strong> μέτρια",
    intro="Στη Ρώμη χρησιμοποιούν στρογγυλές αγκινάρες 'mammole', χωρίς χνούδι. Η συνταγή στηρίζεται σε δύο κινήσεις: καλό καθάρισμα ως το τρυφερό μέρος και αργό μαγείρεμα στο ελαιόλαδο με νερό, ανάποδα, μέχρι να λιώσουν. Ο δυόσμος (mentuccia) είναι η αρωματική υπογραφή.",
    ingredients=[
        "4 μεγάλες στρογγυλές αγκινάρες (χωρίς χνούδι)",
        "2 σκελίδες σκόρδο",
        "1 ματσάκι μαϊντανός",
        "Λίγα φύλλα δυόσμου (ιδανικά mentuccia)",
        "1 λεμόνι (κατά της οξείδωσης)",
        "100 ml έξτρα παρθένο ελαιόλαδο",
        "Αλάτι, πιπέρι, νερό (και λίγο λευκό κρασί, προαιρετικά)",
    ],
    steps=[
        "<strong>Καθαρίστε τις αγκινάρες.</strong> Αφαιρέστε τα σκληρά εξωτερικά φύλλα, κόψτε τη μύτη και καθαρίστε την καρδιά κρατώντας κοτσάνι 4-5 εκ. καθαρισμένο. Τρίψτε με λεμόνι και βυθίστε σε ξινισμένο νερό για να μη μαυρίσουν.",
        "<strong>Ετοιμάστε τη γέμιση.</strong> Ψιλοκόψτε σκόρδο, μαϊντανό και δυόσμο με αλάτι και πιπέρι. Ανοίξτε ελαφρά το κέντρο κάθε αγκινάρας και γεμίστε.",
        "<strong>Τοποθετήστε στην κατσαρόλα.</strong> Βάλτε τις αγκινάρες ανάποδα, σφιχτά, σε κατσαρόλα όπου στέκονται όρθιες.",
        "<strong>Σιγοβράστε.</strong> Ρίξτε το ελαιόλαδο και νερό (ως τη μέση των αγκινάρων), και λίγο λευκό κρασί αν θέλετε. Αλατίστε. Σκεπάστε και μαγειρέψτε σε χαμηλή φωτιά 30–40 λεπτά, μέχρι η μύτη μαχαιριού να μπαίνει εύκολα.",
        "<strong>Σερβίρετε.</strong> Σερβίρετε χλιαρές ή σε θερμοκρασία δωματίου, με το λαδερό ζουμί τους, με ψωμί.",
    ],
    oil="Εδώ το ελαιόλαδο είναι το μέσο μαγειρέματος: κομφί σιγά την αγκινάρα και ποτίζεται με το άρωμά της και τον δυόσμο. Χρησιμοποιήστε ένα <strong>ποιοτικό έξτρα παρθένο</strong>, γενναιόδωρα — το λαδερό ζουμί είναι μέρος του πιάτου.",
    tips=[
        "Καθαρίστε καλά: μόνο το τρυφερό μέρος να μείνει, αλλιώς είναι ινώδες.",
        "Το ξινισμένο νερό εμποδίζει το μαύρισμα κατά το καθάρισμα.",
        "Μαγειρέψτε σιγά και σκεπασμένα: είναι σιγοβράσιμο, όχι τηγάνισμα.",
        "Ο δυόσμος (mentuccia) είναι η ρωμαϊκή υπογραφή· αλλιώς δυόσμος + μαϊντανός.",
    ],
    variations=[
        "<strong>Χωρίς δυόσμο:</strong> μόνο μαϊντανός και σκόρδο, πιο απλά.",
        "<strong>Με λευκό κρασί:</strong> λίγο κρασί στο υγρό μαγειρέματος.",
        "<strong>Carciofi alla giudia:</strong> διαφορετική ρωμαϊκή εκδοχή, τηγανητές και τραγανές (άλλη συνταγή).",
    ],
    serve="Σερβίρετε τις αγκινάρες αλά ρομάνα ως ορεκτικό ή συνοδευτικό, χλιαρές ή σε θερμοκρασία δωματίου, με το λάδι μαγειρέματος και ψωμί. Ταιριάζουν και με ψάρι ή λευκό κρέας.",
    store="Διατηρούνται 2–3 ημέρες στο ψυγείο μέσα στο λάδι τους και είναι καλύτερες την επόμενη μέρα. Βγάλτε τες νωρίτερα: το κρύο πήζει το ελαιόλαδο.",
    faqs=[
        ("Ποιες αγκινάρες για carciofi alla romana;",
         "Στρογγυλές, σαρκώδεις, χωρίς χνούδι, τύπου romanesco. Αλλιώς μεγάλες τρυφερές αγκινάρες, καλά καθαρισμένες ως την καρδιά."),
        ("Πώς καθαρίζεται μια αγκινάρα;",
         "Αφαιρέστε τα σκληρά εξωτερικά φύλλα, κόψτε τη μύτη, καθαρίστε το κοτσάνι και κρατήστε μόνο το τρυφερό μέρος. Τρίψτε με λεμόνι και βυθίστε σε ξινισμένο νερό."),
        ("Ποια η διαφορά από τις carciofi alla giudia;",
         "Οι alla romana σιγομαγειρεύονται ολόκληρες στο ελαιόλαδο με μυρωδικά· οι alla giudia (εβραιο-ρωμαϊκές) τηγανίζονται τραγανές. Δύο ξεχωριστές ρωμαϊκές συνταγές."),
        ("Ποιο μυρωδικό να χρησιμοποιήσω;",
         "Ο ρωμαϊκός δυόσμος, mentuccia, είναι παραδοσιακός. Αλλιώς ένα μείγμα ήπιου δυόσμου και μαϊντανού δίνει πολύ κοντινό αποτέλεσμα."),
        ("Ετοιμάζονται από πριν;",
         "Ναι, κερδίζουν σε γεύση: κρατήστε τες στο λάδι μαγειρέματος και φέρτε τες σε θερμοκρασία δωματίου πριν το σερβίρισμα."),
    ],
    schema_name="Αγκινάρες αλά ρομάνα (Carciofi alla romana)",
    schema_desc="Αυθεντικές carciofi alla romana: αγκινάρες σιγομαγειρεμένες στο ελαιόλαδο με σκόρδο, μαϊντανό και δυόσμο.",
    schema_ing=["4 μεγάλες στρογγυλές αγκινάρες", "2 σκελίδες σκόρδο", "μαϊντανός", "δυόσμος (mentuccia)",
                "1 λεμόνι", "100 ml έξτρα παρθένο ελαιόλαδο", "αλάτι, πιπέρι, νερό, λευκό κρασί προαιρετικά"],
    schema_steps=[
        "Καθαρίστε τις αγκινάρες ως την τρυφερή καρδιά, τρίψτε με λεμόνι.",
        "Ετοιμάστε γέμιση σκόρδου, μαϊντανού και δυόσμου και γεμίστε το κέντρο.",
        "Τοποθετήστε τις αγκινάρες ανάποδα σε κατσαρόλα.",
        "Προσθέστε ελαιόλαδο και νερό, σκεπάστε και σιγοβράστε 30-40 λεπτά.",
        "Σερβίρετε χλιαρές με το λάδι μαγειρέματος."],
    keywords="carciofi alla romana, αγκινάρες αλά ρομάνα, αγκινάρες σιγομαγειρεμένες, αγκινάρες ελαιόλαδο, ρωμαϊκές αγκινάρες",
    cuisine="Italian", category="Ορεκτικό", prep="PT30M", cook="PT40M", total="PT1H10M", yield_="4 μερίδες",
    nutrition={"servingSize": "1 μερίδα", "calories": "180 kcal", "fatContent": "14 g", "proteinContent": "4 g", "carbohydrateContent": "11 g"},
)

if __name__ == "__main__":
    write_cluster("artichauts-a-la-romaine", C)
