# -*- coding: utf-8 -*-
"""Authentic Salade de poulpe / insalata di polpo / octopus salad x4 languages."""
from recipe_render import write_cluster

C = {}
C["fr"] = dict(
    title="Salade de poulpe traditionnelle : recette méditerranéenne à l'huile d'olive",
    desc="Salade de poulpe méditerranéenne : poulpe fondant, pommes de terre, céleri, oignon rouge, persil, citron et huile d'olive extra vierge. Astuce pour un poulpe tendre et temps de cuisson.",
    h1="Salade de poulpe traditionnelle",
    lede="Une salade de poulpe réussie, c'est d'abord un poulpe fondant : cuit doucement, laissé reposer dans son eau, puis assaisonné tiède à l'huile d'olive, citron, ail et persil. Voici la méthode méditerranéenne et l'astuce pour l'attendrir.",
    info="<strong>Préparation :</strong> 30 min · <strong>Cuisson :</strong> 1 h · <strong>Repos :</strong> 30 min · <strong>Pour :</strong> 4 personnes · <strong>Cuisine :</strong> méditerranéenne · <strong>Difficulté :</strong> moyenne",
    intro="La salade de poulpe est un classique de toute la Méditerranée, de la Grèce à l'Italie. Le secret n'est pas dans l'assaisonnement mais dans la cuisson : un poulpe tendre, coupé tiède et mariné dans une bonne huile d'olive avec du citron. Le reste — pommes de terre, céleri, oignon — n'est là que pour l'accompagner.",
    ingredients=[
        "1 poulpe d'environ 1 kg (frais ou surgelé)",
        "2 pommes de terre à chair ferme",
        "1 branche de céleri",
        "1/2 oignon rouge",
        "1 bouquet de persil plat",
        "1 gousse d'ail",
        "1 citron (le jus)",
        "5 c. à soupe d'huile d'olive extra vierge",
        "Une poignée d'olives, laurier, sel, poivre",
    ],
    steps=[
        "<strong>Attendrir.</strong> Si le poulpe est frais, congelez-le puis décongelez-le : la congélation casse les fibres et l'attendrit. Rincez-le.",
        "<strong>Cuire doucement.</strong> Plongez le poulpe dans une grande casserole d'eau non salée avec une feuille de laurier. Portez à frémissement et laissez cuire 45 min à 1 h, jusqu'à ce qu'une pointe de couteau s'enfonce facilement dans la partie épaisse.",
        "<strong>Reposer.</strong> Coupez le feu et laissez le poulpe refroidir 15 à 30 min dans son eau de cuisson : il reste moelleux.",
        "<strong>Les légumes.</strong> Pendant ce temps, faites cuire les pommes de terre à l'eau, puis coupez-les en cubes. Émincez le céleri et l'oignon rouge, hachez le persil et l'ail.",
        "<strong>Assembler.</strong> Coupez le poulpe en bouchées. Mélangez-le tiède avec les pommes de terre, le céleri et l'oignon. Assaisonnez d'huile d'olive extra vierge, de jus de citron, d'ail, de persil, de sel et de poivre.",
        "<strong>Laisser mariner.</strong> Laissez reposer 30 min pour que les saveurs se lient. Servez à température ambiante avec des olives et un dernier filet d'huile d'olive.",
    ],
    oil="L'huile d'olive lie la salade et adoucit la fermeté du poulpe. Ajoutée tiède, elle s'imprègne mieux. Choisissez une <strong>extra vierge fruitée, moyennement intense</strong>, et gardez un filet à cru au moment de servir pour le parfum.",
    tips=[
        "Congeler-décongeler le poulpe frais l'attendrit sans effort.",
        "Ne salez pas l'eau de cuisson : le sel raffermit le poulpe.",
        "Laissez refroidir dans l'eau de cuisson pour un poulpe moelleux.",
        "Assaisonnez tiède, puis laissez mariner : la salade est meilleure après 30 min de repos.",
    ],
    variations=[
        "<strong>À la grecque :</strong> origan, oignon rouge, vinaigre de vin et olives Kalamata.",
        "<strong>À l'italienne (insalata di polpo) :</strong> pommes de terre, céleri, persil, ail et citron.",
        "<strong>Plus relevée :</strong> une pointe de piment ou de zeste de citron.",
    ],
    serve="Servez la salade de poulpe en entrée fraîche ou en mezze, à température ambiante, avec du pain pour saucer l'huile d'olive citronnée. Elle accompagne aussi très bien un plateau de fruits de mer ou un apéritif méditerranéen.",
    store="Elle se conserve 2 jours au réfrigérateur dans un contenant hermétique et gagne même en saveur le lendemain. Sortez-la 20 minutes avant de servir pour qu'elle ne soit pas froide. Ne la congelez pas une fois assaisonnée.",
    faqs=[
        ("Comment rendre le poulpe tendre ?",
         "Deux leviers : la congélation (congeler puis décongeler un poulpe frais casse les fibres) et une cuisson douce et longue, suivie d'un repos dans l'eau de cuisson. Ne salez pas l'eau, qui raffermit la chair."),
        ("Combien de temps cuire le poulpe ?",
         "Comptez 45 min à 1 h à frémissement pour un poulpe d'environ 1 kg, jusqu'à ce qu'une pointe de couteau s'enfonce facilement dans la partie épaisse. Puis laissez-le tiédir dans son eau."),
        ("Poulpe frais ou surgelé ?",
         "Le surgelé est très pratique et souvent plus tendre, car la congélation attendrit naturellement. Si vous prenez du frais, congelez-le d'abord pour le même effet."),
        ("Salade de poulpe tiède ou froide ?",
         "On assaisonne le poulpe tiède pour qu'il absorbe l'huile et le citron, puis on la sert à température ambiante. Trop froide, la salade perd en parfum et l'huile fige."),
        ("Le bouchon de liège dans l'eau, ça marche ?",
         "C'est une tradition sans effet prouvé sur la tendreté. Ce qui compte vraiment, c'est la congélation préalable, une cuisson douce et le repos dans l'eau de cuisson."),
    ],
    schema_name="Salade de poulpe traditionnelle",
    schema_desc="Salade de poulpe méditerranéenne : poulpe fondant, pommes de terre, céleri, oignon rouge, persil, citron et huile d'olive extra vierge.",
    schema_ing=["1 poulpe d'environ 1 kg", "2 pommes de terre", "1 branche de céleri", "1/2 oignon rouge",
                "persil plat", "1 gousse d'ail", "1 citron", "5 c. à soupe huile d'olive extra vierge", "olives, laurier"],
    schema_steps=[
        "Congeler puis décongeler le poulpe frais pour l'attendrir.",
        "Cuire à frémissement 45 min-1 h dans l'eau non salée avec du laurier.",
        "Laisser refroidir dans l'eau de cuisson.",
        "Cuire les pommes de terre, tailler céleri, oignon, persil, ail.",
        "Couper le poulpe et mélanger tiède avec les légumes, huile d'olive, citron, ail, persil.",
        "Laisser mariner 30 min et servir à température ambiante avec des olives."],
    keywords="salade de poulpe, salade poulpe traditionnelle, recette poulpe, insalata di polpo, poulpe huile d'olive",
    cuisine="Mediterranean", category="Entrée", prep="PT30M", cook="PT1H", total="PT2H", yield_="4 servings",
    nutrition={"servingSize": "1 portion", "calories": "260 kcal", "fatContent": "16 g", "proteinContent": "22 g", "carbohydrateContent": "9 g"},
)
C["en"] = dict(
    title="Traditional Octopus Salad: Mediterranean recipe with olive oil",
    desc="Mediterranean octopus salad: tender octopus, potatoes, celery, red onion, parsley, lemon and extra virgin olive oil. The trick for tender octopus and how long to cook it.",
    h1="Traditional Octopus Salad",
    lede="A great octopus salad starts with tender octopus: gently cooked, rested in its own liquid, then dressed warm with olive oil, lemon, garlic and parsley. Here is the Mediterranean method and the trick to tenderise it.",
    info="<strong>Prep:</strong> 30 min · <strong>Cook:</strong> 1 h · <strong>Rest:</strong> 30 min · <strong>Serves:</strong> 4 · <strong>Cuisine:</strong> Mediterranean · <strong>Difficulty:</strong> medium",
    intro="Octopus salad is a classic across the Mediterranean, from Greece to Italy. The secret is not the dressing but the cooking: tender octopus, cut warm and marinated in good olive oil with lemon. The rest — potatoes, celery, onion — is just there to support it.",
    ingredients=[
        "1 octopus, about 1 kg (fresh or frozen)",
        "2 waxy potatoes",
        "1 celery stalk",
        "1/2 red onion",
        "1 bunch flat-leaf parsley",
        "1 garlic clove",
        "1 lemon (juice)",
        "5 tbsp extra virgin olive oil",
        "A handful of olives, bay leaf, salt, pepper",
    ],
    steps=[
        "<strong>Tenderise.</strong> If the octopus is fresh, freeze then thaw it: freezing breaks the fibres and tenderises. Rinse.",
        "<strong>Cook gently.</strong> Lower the octopus into a large pot of unsalted water with a bay leaf. Bring to a bare simmer and cook 45 min–1 h, until a knife tip slides easily into the thick part.",
        "<strong>Rest.</strong> Turn off the heat and let the octopus cool 15–30 min in its cooking liquid: it stays moist.",
        "<strong>The vegetables.</strong> Meanwhile boil the potatoes, then cube them. Slice the celery and red onion; chop the parsley and garlic.",
        "<strong>Assemble.</strong> Cut the octopus into bite-size pieces. Mix it warm with the potatoes, celery and onion. Dress with extra virgin olive oil, lemon juice, garlic, parsley, salt and pepper.",
        "<strong>Marinate.</strong> Rest 30 min so the flavours bind. Serve at room temperature with olives and a final drizzle of olive oil.",
    ],
    oil="Olive oil binds the salad and softens the firmness of the octopus. Added warm, it soaks in better. Choose a <strong>fruity, medium-intensity extra virgin</strong>, and keep a raw drizzle for serving to add aroma.",
    tips=[
        "Freeze-then-thaw fresh octopus to tenderise it effortlessly.",
        "Don't salt the cooking water: salt firms the octopus.",
        "Let it cool in the cooking liquid for a moist result.",
        "Dress it warm, then marinate: the salad is best after 30 min resting.",
    ],
    variations=[
        "<strong>Greek style:</strong> oregano, red onion, wine vinegar and Kalamata olives.",
        "<strong>Italian style (insalata di polpo):</strong> potatoes, celery, parsley, garlic and lemon.",
        "<strong>Spicier:</strong> a touch of chili or lemon zest.",
    ],
    serve="Serve octopus salad as a chilled starter or mezze, at room temperature, with bread to mop up the lemony olive oil. It also pairs well with a seafood platter or a Mediterranean aperitivo.",
    store="It keeps 2 days in the fridge in an airtight container and even improves the next day. Take it out 20 minutes before serving so it isn't fridge-cold. Do not freeze once dressed.",
    faqs=[
        ("How do you make octopus tender?",
         "Two levers: freezing (freezing then thawing fresh octopus breaks the fibres) and gentle, long cooking followed by resting in the cooking liquid. Don't salt the water, which firms the flesh."),
        ("How long do you cook octopus?",
         "About 45 min–1 h at a bare simmer for a 1 kg octopus, until a knife tip slides easily into the thick part. Then let it cool in its liquid."),
        ("Fresh or frozen octopus?",
         "Frozen is very practical and often more tender, because freezing naturally tenderises. If you buy fresh, freeze it first for the same effect."),
        ("Octopus salad warm or cold?",
         "Dress the octopus warm so it absorbs the oil and lemon, then serve at room temperature. Too cold, the salad loses aroma and the oil sets."),
        ("Does a wine cork in the water work?",
         "It's a tradition with no proven effect on tenderness. What really matters is prior freezing, gentle cooking and resting in the liquid."),
    ],
    schema_name="Traditional Octopus Salad",
    schema_desc="Mediterranean octopus salad: tender octopus, potatoes, celery, red onion, parsley, lemon and extra virgin olive oil.",
    schema_ing=["1 octopus about 1 kg", "2 waxy potatoes", "1 celery stalk", "1/2 red onion",
                "flat-leaf parsley", "1 garlic clove", "1 lemon", "5 tbsp extra virgin olive oil", "olives, bay leaf"],
    schema_steps=[
        "Freeze then thaw fresh octopus to tenderise.",
        "Simmer gently 45 min-1 h in unsalted water with bay leaf.",
        "Cool in the cooking liquid.",
        "Boil potatoes; slice celery, onion, parsley, garlic.",
        "Cut octopus and mix warm with vegetables, olive oil, lemon, garlic, parsley.",
        "Marinate 30 min and serve at room temperature with olives."],
    keywords="octopus salad, traditional octopus salad, octopus recipe, insalata di polpo, octopus olive oil",
    cuisine="Mediterranean", category="Appetizer", prep="PT30M", cook="PT1H", total="PT2H", yield_="4 servings",
    nutrition={"servingSize": "1 serving", "calories": "260 kcal", "fatContent": "16 g", "proteinContent": "22 g", "carbohydrateContent": "9 g"},
)
C["it"] = dict(
    title="Insalata di polpo tradizionale: ricetta mediterranea all'olio d'oliva",
    desc="Insalata di polpo mediterranea: polpo tenero, patate, sedano, cipolla rossa, prezzemolo, limone e olio extravergine d'oliva. Il trucco per un polpo tenero e i tempi di cottura.",
    h1="Insalata di polpo tradizionale",
    lede="Una buona insalata di polpo parte da un polpo tenero: cotto piano, lasciato riposare nella sua acqua, poi condito tiepido con olio d'oliva, limone, aglio e prezzemolo. Ecco il metodo mediterraneo e il trucco per ammorbidirlo.",
    info="<strong>Preparazione:</strong> 30 min · <strong>Cottura:</strong> 1 h · <strong>Riposo:</strong> 30 min · <strong>Per:</strong> 4 persone · <strong>Cucina:</strong> mediterranea · <strong>Difficoltà:</strong> media",
    intro="L'insalata di polpo è un classico di tutto il Mediterraneo, dalla Grecia all'Italia. Il segreto non è il condimento ma la cottura: polpo tenero, tagliato tiepido e marinato in un buon olio d'oliva con limone. Il resto — patate, sedano, cipolla — serve solo ad accompagnare.",
    ingredients=[
        "1 polpo di circa 1 kg (fresco o surgelato)",
        "2 patate a pasta soda",
        "1 gambo di sedano",
        "1/2 cipolla rossa",
        "1 ciuffo di prezzemolo",
        "1 spicchio d'aglio",
        "1 limone (succo)",
        "5 cucchiai di olio extravergine d'oliva",
        "Una manciata di olive, alloro, sale, pepe",
    ],
    steps=[
        "<strong>Ammorbidire.</strong> Se il polpo è fresco, congelalo e scongelalo: il congelamento rompe le fibre e lo ammorbidisce. Sciacqualo.",
        "<strong>Cuocere piano.</strong> Immergi il polpo in una pentola capiente di acqua non salata con una foglia di alloro. Porta a leggero sobbollire e cuoci 45 min–1 h, finché la punta di un coltello entra facilmente nella parte spessa.",
        "<strong>Riposare.</strong> Spegni e lascia raffreddare il polpo 15–30 min nella sua acqua: resta morbido.",
        "<strong>Le verdure.</strong> Intanto lessa le patate e tagliale a cubetti. Affetta sedano e cipolla rossa; trita prezzemolo e aglio.",
        "<strong>Assemblare.</strong> Taglia il polpo a bocconcini. Uniscilo tiepido con patate, sedano e cipolla. Condisci con olio extravergine, succo di limone, aglio, prezzemolo, sale e pepe.",
        "<strong>Marinare.</strong> Lascia riposare 30 min. Servi a temperatura ambiente con olive e un ultimo filo d'olio.",
    ],
    oil="L'olio d'oliva lega l'insalata e ammorbidisce la consistenza del polpo. Aggiunto tiepido, si assorbe meglio. Scegli un <strong>extravergine fruttato, di media intensità</strong>, e tieni un filo a crudo al momento di servire.",
    tips=[
        "Congelare-scongelare il polpo fresco lo ammorbidisce senza fatica.",
        "Non salare l'acqua di cottura: il sale indurisce il polpo.",
        "Lascialo raffreddare nell'acqua di cottura per un risultato morbido.",
        "Condisci tiepido, poi marina: l'insalata è migliore dopo 30 min di riposo.",
    ],
    variations=[
        "<strong>Alla greca:</strong> origano, cipolla rossa, aceto di vino e olive Kalamata.",
        "<strong>All'italiana (insalata di polpo):</strong> patate, sedano, prezzemolo, aglio e limone.",
        "<strong>Più piccante:</strong> una punta di peperoncino o scorza di limone.",
    ],
    serve="Servi l'insalata di polpo come antipasto fresco o mezze, a temperatura ambiente, con pane per raccogliere l'olio al limone. Sta bene anche con un piatto di frutti di mare o un aperitivo mediterraneo.",
    store="Si conserva 2 giorni in frigorifero in un contenitore ermetico e migliora il giorno dopo. Toglila 20 minuti prima di servire. Non congelarla una volta condita.",
    faqs=[
        ("Come rendere tenero il polpo?",
         "Due leve: il congelamento (congelare e scongelare un polpo fresco rompe le fibre) e una cottura piano e lunga, seguita dal riposo nell'acqua di cottura. Non salare l'acqua, che indurisce la carne."),
        ("Quanto cuocere il polpo?",
         "Circa 45 min–1 h a leggero sobbollire per un polpo da 1 kg, finché la punta di un coltello entra facilmente nella parte spessa. Poi lascialo raffreddare nella sua acqua."),
        ("Polpo fresco o surgelato?",
         "Il surgelato è comodo e spesso più tenero, perché il congelamento ammorbidisce naturalmente. Se prendi il fresco, congelalo prima per lo stesso effetto."),
        ("Insalata di polpo tiepida o fredda?",
         "Si condisce il polpo tiepido perché assorba olio e limone, poi si serve a temperatura ambiente. Troppo fredda, l'insalata perde profumo e l'olio si rapprende."),
        ("Il tappo di sughero nell'acqua funziona?",
         "È una tradizione senza effetto provato sulla tenerezza. Ciò che conta davvero è il congelamento, la cottura piano e il riposo nell'acqua."),
    ],
    schema_name="Insalata di polpo tradizionale",
    schema_desc="Insalata di polpo mediterranea: polpo tenero, patate, sedano, cipolla rossa, prezzemolo, limone e olio extravergine d'oliva.",
    schema_ing=["1 polpo di circa 1 kg", "2 patate", "1 gambo di sedano", "1/2 cipolla rossa",
                "prezzemolo", "1 spicchio d'aglio", "1 limone", "5 cucchiai olio extravergine d'oliva", "olive, alloro"],
    schema_steps=[
        "Congelare e scongelare il polpo fresco per ammorbidirlo.",
        "Cuocere a leggero sobbollire 45 min-1 h in acqua non salata con alloro.",
        "Raffreddare nell'acqua di cottura.",
        "Lessare le patate; affettare sedano, cipolla, prezzemolo, aglio.",
        "Tagliare il polpo e unirlo tiepido con verdure, olio, limone, aglio, prezzemolo.",
        "Marinare 30 min e servire a temperatura ambiente con olive."],
    keywords="insalata di polpo, insalata di polpo tradizionale, ricetta polpo, polpo olio d'oliva, polpo patate",
    cuisine="Mediterranean", category="Antipasto", prep="PT30M", cook="PT1H", total="PT2H", yield_="4 porzioni",
    nutrition={"servingSize": "1 porzione", "calories": "260 kcal", "fatContent": "16 g", "proteinContent": "22 g", "carbohydrateContent": "9 g"},
)
C["el"] = dict(
    title="Χταποδοσαλάτα παραδοσιακή: μεσογειακή συνταγή με ελαιόλαδο",
    desc="Μεσογειακή χταποδοσαλάτα: τρυφερό χταπόδι, πατάτες, σέλινο, κόκκινο κρεμμύδι, μαϊντανός, λεμόνι και έξτρα παρθένο ελαιόλαδο. Το κόλπο για τρυφερό χταπόδι και χρόνοι βρασίματος.",
    h1="Χταποδοσαλάτα παραδοσιακή",
    lede="Μια καλή χταποδοσαλάτα ξεκινά από τρυφερό χταπόδι: βρασμένο σιγά, αφημένο να ξεκουραστεί στα υγρά του, μετά ντυμένο χλιαρό με ελαιόλαδο, λεμόνι, σκόρδο και μαϊντανό. Δείτε τη μεσογειακή μέθοδο και το κόλπο για να μαλακώσει.",
    info="<strong>Προετοιμασία:</strong> 30 λεπτά · <strong>Βράσιμο:</strong> 1 ώρα · <strong>Ξεκούραση:</strong> 30 λεπτά · <strong>Μερίδες:</strong> 4 · <strong>Κουζίνα:</strong> μεσογειακή · <strong>Δυσκολία:</strong> μέτρια",
    intro="Η χταποδοσαλάτα είναι κλασική σε όλη τη Μεσόγειο, από την Ελλάδα ως την Ιταλία. Το μυστικό δεν είναι το ντύσιμο αλλά το βράσιμο: τρυφερό χταπόδι, κομμένο χλιαρό και μαριναρισμένο σε καλό ελαιόλαδο με λεμόνι.",
    ingredients=[
        "1 χταπόδι περίπου 1 κιλό (φρέσκο ή κατεψυγμένο)",
        "2 πατάτες σφιχτές",
        "1 κλαράκι σέλινο",
        "1/2 κόκκινο κρεμμύδι",
        "1 ματσάκι μαϊντανός",
        "1 σκελίδα σκόρδο",
        "1 λεμόνι (χυμός)",
        "5 κ.σ. έξτρα παρθένο ελαιόλαδο",
        "Μια χούφτα ελιές, δάφνη, αλάτι, πιπέρι",
    ],
    steps=[
        "<strong>Μαλακώστε.</strong> Αν το χταπόδι είναι φρέσκο, καταψύξτε το και ξεπαγώστε το: η κατάψυξη σπάει τις ίνες και το μαλακώνει. Ξεπλύνετε.",
        "<strong>Βράστε σιγά.</strong> Βυθίστε το χταπόδι σε μεγάλη κατσαρόλα με νερό χωρίς αλάτι και μια δάφνη. Σιγοβράστε 45 λεπτά–1 ώρα, μέχρι η μύτη μαχαιριού να μπαίνει εύκολα στο χοντρό σημείο.",
        "<strong>Ξεκουράστε.</strong> Σβήστε τη φωτιά και αφήστε το χταπόδι να κρυώσει 15–30 λεπτά στα υγρά του: μένει ζουμερό.",
        "<strong>Τα λαχανικά.</strong> Στο μεταξύ βράστε τις πατάτες και κόψτε τες σε κύβους. Ψιλοκόψτε σέλινο και κρεμμύδι· ψιλοκόψτε μαϊντανό και σκόρδο.",
        "<strong>Συνθέστε.</strong> Κόψτε το χταπόδι σε μπουκιές. Ανακατέψτε το χλιαρό με πατάτες, σέλινο και κρεμμύδι. Ντύστε με ελαιόλαδο, χυμό λεμονιού, σκόρδο, μαϊντανό, αλάτι και πιπέρι.",
        "<strong>Μαρινάρετε.</strong> Αφήστε 30 λεπτά να δέσουν οι γεύσεις. Σερβίρετε σε θερμοκρασία δωματίου με ελιές και λίγο ελαιόλαδο.",
    ],
    oil="Το ελαιόλαδο δένει τη σαλάτα και απαλύνει το σφιχτό χταπόδι. Χλιαρό απορροφάται καλύτερα. Διαλέξτε ένα <strong>φρουτώδες, μέτριας έντασης έξτρα παρθένο</strong>, και κρατήστε λίγο ωμό για το σερβίρισμα.",
    tips=[
        "Κατάψυξη-ξεπάγωμα του φρέσκου χταποδιού το μαλακώνει χωρίς κόπο.",
        "Μην αλατίζετε το νερό βρασίματος: το αλάτι σφίγγει το χταπόδι.",
        "Αφήστε το να κρυώσει στα υγρά του για ζουμερό αποτέλεσμα.",
        "Ντύστε χλιαρό και μετά μαρινάρετε: η σαλάτα είναι καλύτερη μετά από 30 λεπτά.",
    ],
    variations=[
        "<strong>Ελληνικά:</strong> ρίγανη, κόκκινο κρεμμύδι, ξίδι και ελιές Καλαμών.",
        "<strong>Ιταλικά (insalata di polpo):</strong> πατάτες, σέλινο, μαϊντανός, σκόρδο και λεμόνι.",
        "<strong>Πιο πικάντικη:</strong> λίγη καυτερή ή ξύσμα λεμονιού.",
    ],
    serve="Σερβίρετε τη χταποδοσαλάτα ως κρύο ορεκτικό ή μεζέ, σε θερμοκρασία δωματίου, με ψωμί για το λεμονάτο ελαιόλαδο. Ταιριάζει και με πιατέλα θαλασσινών ή μεσογειακό απεριτίφ.",
    store="Διατηρείται 2 ημέρες στο ψυγείο σε αεροστεγές δοχείο και βελτιώνεται την επόμενη μέρα. Βγάλτε την 20 λεπτά πριν το σερβίρισμα. Μην την καταψύχετε αφού ντυθεί.",
    faqs=[
        ("Πώς γίνεται τρυφερό το χταπόδι;",
         "Δύο τρόποι: η κατάψυξη (κατάψυξη και ξεπάγωμα φρέσκου χταποδιού σπάει τις ίνες) και το αργό, μακρύ βράσιμο με ξεκούραση στα υγρά. Μην αλατίζετε το νερό, που σφίγγει τη σάρκα."),
        ("Πόση ώρα βράζει το χταπόδι;",
         "Περίπου 45 λεπτά–1 ώρα σε σιγανό βράσιμο για χταπόδι 1 κιλού, μέχρι η μύτη μαχαιριού να μπαίνει εύκολα στο χοντρό σημείο. Μετά αφήστε το να κρυώσει στα υγρά του."),
        ("Φρέσκο ή κατεψυγμένο χταπόδι;",
         "Το κατεψυγμένο είναι πρακτικό και συχνά πιο τρυφερό, γιατί η κατάψυξη μαλακώνει φυσικά. Αν πάρετε φρέσκο, καταψύξτε το πρώτα για το ίδιο αποτέλεσμα."),
        ("Χταποδοσαλάτα χλιαρή ή κρύα;",
         "Ντύνουμε το χταπόδι χλιαρό για να απορροφήσει λάδι και λεμόνι, μετά σερβίρουμε σε θερμοκρασία δωματίου. Πολύ κρύα, η σαλάτα χάνει άρωμα και το λάδι πήζει."),
        ("Ο φελλός στο νερό βοηθά;",
         "Είναι παράδοση χωρίς αποδεδειγμένη επίδραση. Αυτό που μετράει είναι η προηγούμενη κατάψυξη, το αργό βράσιμο και η ξεκούραση στα υγρά."),
    ],
    schema_name="Χταποδοσαλάτα παραδοσιακή",
    schema_desc="Μεσογειακή χταποδοσαλάτα: τρυφερό χταπόδι, πατάτες, σέλινο, κόκκινο κρεμμύδι, μαϊντανός, λεμόνι και έξτρα παρθένο ελαιόλαδο.",
    schema_ing=["1 χταπόδι περίπου 1 κιλό", "2 πατάτες", "1 σέλινο", "1/2 κόκκινο κρεμμύδι",
                "μαϊντανός", "1 σκελίδα σκόρδο", "1 λεμόνι", "5 κ.σ. έξτρα παρθένο ελαιόλαδο", "ελιές, δάφνη"],
    schema_steps=[
        "Κατάψυξη και ξεπάγωμα φρέσκου χταποδιού για μαλάκωμα.",
        "Σιγοβράσιμο 45 λεπτά-1 ώρα σε ανάλατο νερό με δάφνη.",
        "Κρύωμα στα υγρά βρασίματος.",
        "Βράσιμο πατάτας· κόψιμο σέλινου, κρεμμυδιού, μαϊντανού, σκόρδου.",
        "Κόψιμο χταποδιού και ανακάτεμα χλιαρού με λαχανικά, ελαιόλαδο, λεμόνι, σκόρδο, μαϊντανό.",
        "Μαρινάρισμα 30 λεπτά και σερβίρισμα σε θερμοκρασία δωματίου με ελιές."],
    keywords="χταποδοσαλάτα, παραδοσιακή χταποδοσαλάτα, συνταγή χταπόδι, insalata di polpo, χταπόδι ελαιόλαδο",
    cuisine="Mediterranean", category="Ορεκτικό", prep="PT30M", cook="PT1H", total="PT2H", yield_="4 μερίδες",
    nutrition={"servingSize": "1 μερίδα", "calories": "260 kcal", "fatContent": "16 g", "proteinContent": "22 g", "carbohydrateContent": "9 g"},
)

if __name__ == "__main__":
    write_cluster("salade-de-poulpe-traditionnelle", C)
