# -*- coding: utf-8 -*-
"""Batch 3b: authentic EVOO guides — for the face/skin, for hair. x4 languages.
Cosmetic use, honest caveats (patch test, skin-barrier nuance, not medical)."""
from guide_render import write_guide_cluster

DISC = {
    "fr": "Usage cosmétique informatif. Faites un test sur une petite zone avant usage et demandez conseil à un dermatologue en cas de peau sensible, acnéique ou de problème cutané.",
    "en": "Informational cosmetic use. Patch-test on a small area first and consult a dermatologist if you have sensitive, acne-prone or problem skin.",
    "it": "Uso cosmetico informativo. Fai un test su una piccola zona prima dell'uso e consulta un dermatologo se hai pelle sensibile, acneica o problemi cutanei.",
    "el": "Ενημερωτική κοσμετική χρήση. Κάντε τεστ σε μικρή περιοχή πρώτα και συμβουλευτείτε δερματολόγο αν έχετε ευαίσθητο, ακνεϊκό ή προβληματικό δέρμα.",
}

# =============================================================== FACE / SKIN ==
F = {}
F["fr"] = dict(
    title="Huile d'olive extra vierge pour le visage : bienfaits, usages et précautions",
    desc="L'huile d'olive extra vierge sur la peau du visage : squalène, vitamine E, antioxydants. Démaquillage, hydratation, nettoyage à l'huile, et à qui elle ne convient pas.",
    h1="Huile d'olive extra vierge pour le visage",
    lede="Utilisée depuis l'Antiquité en cosmétique, l'huile d'olive extra vierge nourrit et protège la peau. Voici ses usages sur le visage, ses composés actifs, et les cas où mieux vaut s'abstenir.",
    section="skincare", datePublished="2026-05-04", disclaimer=DISC["fr"],
    keywords="huile d'olive visage, huile d'olive extra vierge peau, huile d'olive démaquillant, squalène huile d'olive, huile d'olive soin visage",
    intro="L'huile d'olive extra vierge est un émollient naturel riche en composés protecteurs. Sur le visage, elle peut hydrater, démaquiller et adoucir — mais elle ne convient pas à tous les types de peau. Voici un usage honnête, avantages et limites compris.",
    key_facts=[
        "L'huile d'olive contient du squalène, de l'acide oléique, de la vitamine E et des polyphénols aux propriétés émollientes et antioxydantes.",
        "Usages courants : démaquillant, huile de nettoyage, soin hydratant, huile de massage.",
        "Riche en acide oléique, elle peut fragiliser la barrière cutanée de certaines peaux sensibles ou acnéiques : faites un test.",
        "Elle ne remplace ni une crème solaire, ni un traitement dermatologique.",
    ],
    sections=[
        ("Pourquoi l'huile d'olive est utilisée sur la peau",
         "<p>L'huile d'olive extra vierge est un émollient : elle forme un film qui limite la perte en eau et assouplit la peau. Elle apporte du <strong>squalène</strong> (proche d'un lipide naturel de la peau), de la <strong>vitamine E</strong> et des <strong>polyphénols antioxydants</strong>. C'est cette composition qui explique son usage traditionnel en cosmétique méditerranéenne.</p>"),
        ("Démaquillage et nettoyage à l'huile",
         "<p>Comme toute huile, l'huile d'olive dissout le maquillage et le sébum : massez quelques gouttes sur peau sèche, puis retirez avec un linge tiède humide. C'est la base du « nettoyage à l'huile ». Résultat doux, mais rincez bien pour ne pas laisser de film sur les peaux mixtes à grasses.</p>"),
        ("Hydratation et soin",
         "<p>En très petite quantité, l'huile d'olive peut sceller l'hydratation sur peau sèche, sur le corps comme sur les zones rugueuses (coudes, talons). Sur le visage, une à deux gouttes suffisent, idéalement sur peau encore humide pour emprisonner l'eau.</p>"),
        ("À qui elle ne convient pas",
         "<p>Point important et souvent tu : l'huile d'olive est <strong>riche en acide oléique</strong>, et des études suggèrent qu'elle peut <strong>fragiliser la barrière cutanée</strong> chez certaines personnes, en particulier les peaux sensibles, atopiques ou acnéiques. Elle peut être comédogène pour les peaux à tendance acnéique. Faites toujours un test sur une petite zone, et évitez sur peau lésée sans avis médical.</p>"),
        ("Comment bien l'utiliser",
         "<p>Choisissez une <strong>huile d'olive extra vierge</strong> de qualité, en petite quantité, et testez d'abord au creux du bras. Privilégiez l'usage le soir (démaquillage, soin), pas comme protection solaire. En cas de doute ou de problème de peau, demandez conseil à un dermatologue.</p>"),
    ],
    faqs=[
        ("L'huile d'olive est-elle bonne pour le visage ?",
         "Elle peut hydrater, démaquiller et adoucir grâce à son squalène et sa vitamine E. Mais elle ne convient pas à toutes les peaux : riche en acide oléique, elle peut fragiliser la barrière de certaines peaux sensibles ou acnéiques."),
        ("Peut-on se démaquiller à l'huile d'olive ?",
         "Oui. Massez quelques gouttes sur peau sèche pour dissoudre le maquillage, puis retirez avec un linge tiède humide et rincez. C'est un démaquillant doux et économique."),
        ("L'huile d'olive est-elle comédogène ?",
         "Elle peut l'être pour les peaux à tendance acnéique, en raison de sa richesse en acide oléique. Si vous avez la peau grasse ou acnéique, testez prudemment ou préférez une huile plus légère."),
        ("Quelle huile d'olive pour la peau ?",
         "Une huile d'olive extra vierge de qualité, fraîche et bien conservée. Le raffinage retire une partie des polyphénols ; l'extra vierge en garde davantage."),
        ("L'huile d'olive protège-t-elle du soleil ?",
         "Non. Elle ne remplace pas une crème solaire et n'offre pas de protection UV fiable. Utilisez une protection solaire dédiée."),
    ],
)
F["en"] = dict(
    title="Extra Virgin Olive Oil for the Face: benefits, uses and precautions",
    desc="Extra virgin olive oil on facial skin: squalene, vitamin E, antioxidants. Makeup removal, moisturising, oil cleansing, and who it doesn't suit.",
    h1="Extra Virgin Olive Oil for the Face",
    lede="Used in cosmetics since antiquity, extra virgin olive oil nourishes and protects the skin. Here are its uses on the face, its active compounds, and the cases where it's better avoided.",
    section="skincare", datePublished="2026-05-04", disclaimer=DISC["en"],
    keywords="olive oil for face, extra virgin olive oil skin, olive oil makeup remover, olive oil squalene, olive oil skincare",
    intro="Extra virgin olive oil is a natural emollient rich in protective compounds. On the face it can moisturise, remove makeup and soften — but it doesn't suit every skin type. Here's an honest guide, benefits and limits included.",
    key_facts=[
        "Olive oil contains squalene, oleic acid, vitamin E and polyphenols with emollient and antioxidant properties.",
        "Common uses: makeup remover, cleansing oil, moisturising treatment, massage oil.",
        "High in oleic acid, it can weaken the skin barrier in some sensitive or acne-prone skin: patch-test first.",
        "It replaces neither a sunscreen nor a dermatological treatment.",
    ],
    sections=[
        ("Why olive oil is used on skin",
         "<p>Extra virgin olive oil is an emollient: it forms a film that limits water loss and softens the skin. It provides <strong>squalene</strong> (close to a natural skin lipid), <strong>vitamin E</strong> and <strong>antioxidant polyphenols</strong>. This composition explains its traditional use in Mediterranean cosmetics.</p>"),
        ("Makeup removal and oil cleansing",
         "<p>Like any oil, olive oil dissolves makeup and sebum: massage a few drops onto dry skin, then wipe off with a warm damp cloth. This is the basis of 'oil cleansing'. The result is gentle, but rinse well so you don't leave a film on combination-to-oily skin.</p>"),
        ("Moisturising and care",
         "<p>In very small amounts, olive oil can seal in moisture on dry skin, on the body and on rough areas (elbows, heels). On the face, one or two drops are enough, ideally on still-damp skin to trap water.</p>"),
        ("Who it doesn't suit",
         "<p>An important and often-omitted point: olive oil is <strong>high in oleic acid</strong>, and studies suggest it can <strong>weaken the skin barrier</strong> in some people, particularly sensitive, atopic or acne-prone skin. It can be comedogenic for acne-prone skin. Always patch-test on a small area, and avoid on broken skin without medical advice.</p>"),
        ("How to use it well",
         "<p>Choose a quality <strong>extra virgin olive oil</strong>, in small amounts, and test first on the inner arm. Favour evening use (makeup removal, treatment), not as sun protection. If in doubt or if you have a skin condition, ask a dermatologist.</p>"),
    ],
    faqs=[
        ("Is olive oil good for the face?",
         "It can moisturise, remove makeup and soften thanks to its squalene and vitamin E. But it doesn't suit all skin: high in oleic acid, it can weaken the barrier of some sensitive or acne-prone skin."),
        ("Can you remove makeup with olive oil?",
         "Yes. Massage a few drops onto dry skin to dissolve makeup, then wipe off with a warm damp cloth and rinse. It's a gentle, economical makeup remover."),
        ("Is olive oil comedogenic?",
         "It can be for acne-prone skin, because of its high oleic acid content. If you have oily or acne-prone skin, test carefully or prefer a lighter oil."),
        ("Which olive oil for skin?",
         "A quality extra virgin olive oil, fresh and well stored. Refining removes some polyphenols; extra virgin keeps more."),
        ("Does olive oil protect against the sun?",
         "No. It doesn't replace sunscreen and offers no reliable UV protection. Use a dedicated sunscreen."),
    ],
)
F["it"] = dict(
    title="Olio extravergine d'oliva per il viso: benefici, usi e precauzioni",
    desc="Olio extravergine d'oliva sulla pelle del viso: squalene, vitamina E, antiossidanti. Struccante, idratazione, detersione a olio e a chi non è adatto.",
    h1="Olio extravergine d'oliva per il viso",
    lede="Usato in cosmesi fin dall'antichità, l'olio extravergine d'oliva nutre e protegge la pelle. Ecco gli usi sul viso, i composti attivi e i casi in cui è meglio evitarlo.",
    section="skincare", datePublished="2026-05-04", disclaimer=DISC["it"],
    keywords="olio d'oliva viso, olio extravergine pelle, olio d'oliva struccante, squalene olio d'oliva, olio d'oliva skincare",
    intro="L'olio extravergine d'oliva è un emolliente naturale ricco di composti protettivi. Sul viso può idratare, struccare e ammorbidire — ma non è adatto a ogni tipo di pelle. Ecco una guida onesta, benefici e limiti inclusi.",
    key_facts=[
        "L'olio d'oliva contiene squalene, acido oleico, vitamina E e polifenoli con proprietà emollienti e antiossidanti.",
        "Usi comuni: struccante, olio detergente, trattamento idratante, olio da massaggio.",
        "Ricco di acido oleico, può indebolire la barriera cutanea in alcune pelli sensibili o acneiche: fai un test.",
        "Non sostituisce né una crema solare né un trattamento dermatologico.",
    ],
    sections=[
        ("Perché l'olio d'oliva si usa sulla pelle",
         "<p>L'olio extravergine d'oliva è un emolliente: forma un film che limita la perdita d'acqua e ammorbidisce la pelle. Apporta <strong>squalene</strong> (simile a un lipide naturale della pelle), <strong>vitamina E</strong> e <strong>polifenoli antiossidanti</strong>. Questa composizione spiega l'uso tradizionale nella cosmesi mediterranea.</p>"),
        ("Struccare e detersione a olio",
         "<p>Come ogni olio, scioglie trucco e sebo: massaggia qualche goccia su pelle asciutta, poi rimuovi con un panno tiepido umido. È la base della 'detersione a olio'. Risultato delicato, ma risciacqua bene per non lasciare film su pelli miste o grasse.</p>"),
        ("Idratazione e cura",
         "<p>In piccolissima quantità, può sigillare l'idratazione su pelle secca, sul corpo e su zone ruvide (gomiti, talloni). Sul viso bastano una o due gocce, meglio su pelle ancora umida.</p>"),
        ("A chi non è adatto",
         "<p>Punto importante e spesso taciuto: è <strong>ricco di acido oleico</strong> e alcuni studi suggeriscono che può <strong>indebolire la barriera cutanea</strong> in alcune persone, in particolare pelli sensibili, atopiche o acneiche. Può essere comedogeno per la pelle acneica. Fai sempre un test e evita su pelle lesa senza parere medico.</p>"),
        ("Come usarlo bene",
         "<p>Scegli un <strong>olio extravergine</strong> di qualità, in piccole quantità, e testa prima sull'interno del braccio. Preferisci l'uso serale, non come protezione solare. In caso di dubbi o problemi cutanei, consulta un dermatologo.</p>"),
    ],
    faqs=[
        ("L'olio d'oliva fa bene al viso?",
         "Può idratare, struccare e ammorbidire grazie a squalene e vitamina E. Ma non è adatto a ogni pelle: ricco di acido oleico, può indebolire la barriera di alcune pelli sensibili o acneiche."),
        ("Si può struccare con l'olio d'oliva?",
         "Sì. Massaggia qualche goccia su pelle asciutta per sciogliere il trucco, poi rimuovi con un panno tiepido umido e risciacqua."),
        ("L'olio d'oliva è comedogeno?",
         "Può esserlo per la pelle acneica, per l'alto contenuto di acido oleico. Con pelle grassa o acneica, testa con prudenza o preferisci un olio più leggero."),
        ("Quale olio d'oliva per la pelle?",
         "Un olio extravergine di qualità, fresco e ben conservato. La raffinazione toglie parte dei polifenoli; l'extravergine ne conserva di più."),
        ("L'olio d'oliva protegge dal sole?",
         "No. Non sostituisce la crema solare e non offre protezione UV affidabile."),
    ],
)
F["el"] = dict(
    title="Έξτρα παρθένο ελαιόλαδο για το πρόσωπο: οφέλη, χρήσεις και προφυλάξεις",
    desc="Έξτρα παρθένο ελαιόλαδο στο δέρμα του προσώπου: σκουαλένιο, βιταμίνη E, αντιοξειδωτικά. Ντεμακιγιάζ, ενυδάτωση, καθαρισμός με λάδι και σε ποιους δεν ταιριάζει.",
    h1="Έξτρα παρθένο ελαιόλαδο για το πρόσωπο",
    lede="Σε χρήση στην κοσμετική από την αρχαιότητα, το έξτρα παρθένο ελαιόλαδο θρέφει και προστατεύει το δέρμα. Δείτε τις χρήσεις στο πρόσωπο, τις δραστικές ενώσεις και πότε είναι καλύτερα να το αποφύγετε.",
    section="skincare", datePublished="2026-05-04", disclaimer=DISC["el"],
    keywords="ελαιόλαδο πρόσωπο, έξτρα παρθένο ελαιόλαδο δέρμα, ελαιόλαδο ντεμακιγιάζ, σκουαλένιο ελαιόλαδο, ελαιόλαδο περιποίηση",
    intro="Το έξτρα παρθένο ελαιόλαδο είναι φυσικός μαλακτικός παράγοντας πλούσιος σε προστατευτικές ενώσεις. Στο πρόσωπο μπορεί να ενυδατώσει, να ντεμακιγιάρει και να απαλύνει — αλλά δεν ταιριάζει σε κάθε τύπο δέρματος.",
    key_facts=[
        "Το ελαιόλαδο περιέχει σκουαλένιο, ελαϊκό οξύ, βιταμίνη E και πολυφαινόλες με μαλακτικές και αντιοξειδωτικές ιδιότητες.",
        "Συνήθεις χρήσεις: ντεμακιγιάζ, λάδι καθαρισμού, ενυδατική φροντίδα, λάδι μασάζ.",
        "Πλούσιο σε ελαϊκό οξύ, μπορεί να αποδυναμώσει τον φραγμό του δέρματος σε ευαίσθητα ή ακνεϊκά δέρματα: κάντε τεστ.",
        "Δεν αντικαθιστά ούτε αντηλιακό ούτε δερματολογική θεραπεία.",
    ],
    sections=[
        ("Γιατί χρησιμοποιείται στο δέρμα",
         "<p>Το έξτρα παρθένο ελαιόλαδο είναι μαλακτικό: σχηματίζει ένα φιλμ που περιορίζει την απώλεια νερού και απαλύνει το δέρμα. Παρέχει <strong>σκουαλένιο</strong> (κοντά σε φυσικό λιπίδιο του δέρματος), <strong>βιταμίνη E</strong> και <strong>αντιοξειδωτικές πολυφαινόλες</strong>.</p>"),
        ("Ντεμακιγιάζ και καθαρισμός με λάδι",
         "<p>Όπως κάθε λάδι, διαλύει το μακιγιάζ και το σμήγμα: κάντε μασάζ λίγες σταγόνες σε στεγνό δέρμα, μετά αφαιρέστε με χλιαρό υγρό πανί. Είναι η βάση του «καθαρισμού με λάδι». Ξεπλύνετε καλά σε μικτά/λιπαρά δέρματα.</p>"),
        ("Ενυδάτωση και φροντίδα",
         "<p>Σε πολύ μικρή ποσότητα, μπορεί να σφραγίσει την ενυδάτωση σε ξηρό δέρμα, στο σώμα και σε τραχιές περιοχές (αγκώνες, φτέρνες). Στο πρόσωπο αρκούν μία-δύο σταγόνες, ιδανικά σε νωπό δέρμα.</p>"),
        ("Σε ποιους δεν ταιριάζει",
         "<p>Σημαντικό και συχνά αποσιωπημένο: είναι <strong>πλούσιο σε ελαϊκό οξύ</strong>, και μελέτες δείχνουν ότι μπορεί να <strong>αποδυναμώσει τον φραγμό του δέρματος</strong> σε κάποιους, ιδίως ευαίσθητα, ατοπικά ή ακνεϊκά δέρματα. Μπορεί να φράζει τους πόρους σε ακνεϊκό δέρμα. Κάντε πάντα τεστ και αποφύγετε σε πληγωμένο δέρμα χωρίς ιατρική συμβουλή.</p>"),
        ("Πώς να το χρησιμοποιείτε σωστά",
         "<p>Επιλέξτε ποιοτικό <strong>έξτρα παρθένο ελαιόλαδο</strong>, σε μικρή ποσότητα, και δοκιμάστε πρώτα στο εσωτερικό του βραχίονα. Προτιμήστε βραδινή χρήση, όχι ως αντηλιακό. Σε αμφιβολία, συμβουλευτείτε δερματολόγο.</p>"),
    ],
    faqs=[
        ("Κάνει καλό το ελαιόλαδο στο πρόσωπο;",
         "Μπορεί να ενυδατώσει, να ντεμακιγιάρει και να απαλύνει χάρη στο σκουαλένιο και τη βιταμίνη E. Δεν ταιριάζει όμως σε κάθε δέρμα: πλούσιο σε ελαϊκό οξύ, μπορεί να αποδυναμώσει τον φραγμό ευαίσθητων ή ακνεϊκών δερμάτων."),
        ("Γίνεται ντεμακιγιάζ με ελαιόλαδο;",
         "Ναι. Κάντε μασάζ λίγες σταγόνες σε στεγνό δέρμα για να διαλύσετε το μακιγιάζ, μετά αφαιρέστε με χλιαρό υγρό πανί και ξεπλύνετε."),
        ("Φράζει τους πόρους το ελαιόλαδο;",
         "Μπορεί, σε ακνεϊκό δέρμα, λόγω του ελαϊκού οξέος. Με λιπαρό ή ακνεϊκό δέρμα, δοκιμάστε προσεκτικά ή προτιμήστε ελαφρύτερο λάδι."),
        ("Ποιο ελαιόλαδο για το δέρμα;",
         "Ποιοτικό έξτρα παρθένο, φρέσκο και καλά αποθηκευμένο. Η ραφινάρισμα αφαιρεί μέρος των πολυφαινολών."),
        ("Προστατεύει από τον ήλιο;",
         "Όχι. Δεν αντικαθιστά αντηλιακό ούτε προσφέρει αξιόπιστη προστασία UV."),
    ],
)

# ==================================================================== HAIR =====
R = {}
R["fr"] = dict(
    title="Huile d'olive pour les cheveux : bienfaits, masque avant-shampoing et limites",
    desc="L'huile d'olive sur les cheveux : bain d'huile avant-shampoing, pointes, frisottis, cuir chevelu. Méthode, quantités et ce qu'il ne faut pas en attendre.",
    h1="Huile d'olive pour les cheveux",
    lede="L'huile d'olive est un soin capillaire traditionnel : elle gaine la fibre, adoucit et discipline les frisottis. Voici comment l'utiliser en bain d'huile, et ce qu'elle peut — ou non — faire pour vos cheveux.",
    section="haircare", datePublished="2026-05-04", disclaimer=None,
    keywords="huile d'olive cheveux, bain d'huile d'olive, huile d'olive pointes, masque huile d'olive, huile d'olive cheveux secs",
    intro="Utilisée depuis longtemps en soin capillaire, l'huile d'olive gaine la fibre et limite la casse. Ce n'est pas un produit miracle, mais un bon émollient pour cheveux secs et pointes fourchues, à condition de l'utiliser avec mesure.",
    key_facts=[
        "L'huile d'olive gaine la fibre capillaire : elle adoucit, réduit les frisottis et limite la casse.",
        "Usage type : bain d'huile avant-shampoing sur les longueurs et pointes, 30 min à une nuit, puis shampoing.",
        "Elle est lourde : une petite quantité suffit, et un double shampoing peut être nécessaire.",
        "Aucune preuve solide qu'elle fasse « pousser » les cheveux ; son intérêt est cosmétique (gainage, hydratation).",
    ],
    sections=[
        ("Ce que l'huile d'olive fait aux cheveux",
         "<p>L'huile d'olive est un émollient qui <strong>gaine la fibre capillaire</strong>. Elle lisse les écailles, réduit les frisottis, apporte de la souplesse et limite la casse mécanique lors du démêlage. C'est particulièrement utile pour les cheveux secs, épais, bouclés ou abîmés.</p>"),
        ("Le bain d'huile avant-shampoing",
         "<p>La méthode la plus efficace : tiédissez un peu d'huile d'olive, appliquez sur les longueurs et surtout les pointes (peu sur les racines si vous avez le cuir chevelu gras), laissez poser 30 minutes à une nuit sous une serviette, puis lavez avec un shampoing. Un pré-shampoing à l'huile réduit la porosité et protège la fibre pendant le lavage.</p>"),
        ("Cuir chevelu et pointes",
         "<p>Un léger massage du cuir chevelu à l'huile d'olive peut aider à assouplir les squames et apaiser la sensation de sécheresse. Sur les pointes fourchues, l'huile ne « répare » pas la fibre coupée mais la gaine temporairement pour un aspect plus lisse.</p>"),
        ("Quantité et rinçage",
         "<p>L'huile d'olive est lourde : <strong>une petite quantité suffit</strong>, sinon les cheveux paraissent gras et ternes. Émulsionnez le shampoing avant de mouiller pour mieux retirer l'huile, et prévoyez un second shampoing si nécessaire.</p>"),
        ("Ce qu'il ne faut pas en attendre",
         "<p>Contrairement à certaines promesses, aucune preuve solide n'établit que l'huile d'olive <strong>fait pousser</strong> les cheveux plus vite. Son bénéfice est cosmétique : gainage, souplesse, réduction des frisottis. Pour un problème de chute ou de cuir chevelu, consultez un professionnel.</p>"),
    ],
    faqs=[
        ("L'huile d'olive est-elle bonne pour les cheveux ?",
         "Oui pour un usage cosmétique : elle gaine la fibre, adoucit, réduit les frisottis et limite la casse, surtout sur cheveux secs ou abîmés. Utilisée en bain d'huile avant-shampoing, c'est un soin simple et efficace."),
        ("Comment faire un bain d'huile d'olive ?",
         "Tiédissez un peu d'huile, appliquez sur les longueurs et pointes, laissez poser 30 min à une nuit sous une serviette, puis lavez avec un shampoing (deux si besoin)."),
        ("L'huile d'olive fait-elle pousser les cheveux ?",
         "Il n'existe pas de preuve solide qu'elle accélère la pousse. Son intérêt est cosmétique : elle gaine et adoucit la fibre. En cas de chute, consultez un professionnel."),
        ("Huile d'olive bio ou classique pour les cheveux ?",
         "Pour un usage capillaire, la différence est négligeable : c'est surtout la qualité et la fraîcheur qui comptent. Une extra vierge de bonne qualité convient parfaitement."),
        ("Comment enlever l'huile d'olive des cheveux ?",
         "Appliquez le shampoing sur cheveux encore secs ou peu humides pour émulsionner l'huile, massez, puis rincez. Répétez une seconde fois si les cheveux restent gras."),
    ],
)
R["en"] = dict(
    title="Olive Oil for Hair: benefits, pre-shampoo mask and limits",
    desc="Olive oil on hair: pre-shampoo oil treatment, ends, frizz, scalp. Method, amounts, and what not to expect from it.",
    h1="Olive Oil for Hair",
    lede="Olive oil is a traditional hair treatment: it coats the strand, softens and tames frizz. Here's how to use it as an oil treatment, and what it can — or can't — do for your hair.",
    section="haircare", datePublished="2026-05-04", disclaimer=None,
    keywords="olive oil for hair, olive oil hair mask, olive oil hair treatment, olive oil dry hair, olive oil hair ends",
    intro="Long used as a hair treatment, olive oil coats the strand and limits breakage. It's not a miracle product, but a good emollient for dry hair and split ends — as long as you use it in moderation.",
    key_facts=[
        "Olive oil coats the hair shaft: it softens, reduces frizz and limits breakage.",
        "Typical use: pre-shampoo oil treatment on lengths and ends, 30 min to overnight, then shampoo.",
        "It is heavy: a small amount is enough, and a double shampoo may be needed.",
        "No strong evidence it makes hair 'grow'; its benefit is cosmetic (coating, softening).",
    ],
    sections=[
        ("What olive oil does for hair",
         "<p>Olive oil is an emollient that <strong>coats the hair shaft</strong>. It smooths the cuticle, reduces frizz, adds flexibility and limits mechanical breakage during detangling. This is especially useful for dry, thick, curly or damaged hair.</p>"),
        ("The pre-shampoo oil treatment",
         "<p>The most effective method: warm a little olive oil, apply to the lengths and especially the ends (little on the roots if your scalp is oily), leave 30 minutes to overnight under a towel, then wash with shampoo. A pre-shampoo oil reduces porosity and protects the strand during washing.</p>"),
        ("Scalp and ends",
         "<p>A gentle olive oil scalp massage can help soften flakes and ease the feeling of dryness. On split ends, oil doesn't 'repair' the cut strand but temporarily coats it for a smoother look.</p>"),
        ("Amount and rinsing",
         "<p>Olive oil is heavy: <strong>a small amount is enough</strong>, otherwise hair looks greasy and dull. Work shampoo in before wetting to remove the oil more easily, and plan a second shampoo if needed.</p>"),
        ("What not to expect",
         "<p>Contrary to some claims, there's no strong evidence that olive oil <strong>makes hair grow</strong> faster. Its benefit is cosmetic: coating, softness, less frizz. For hair loss or a scalp problem, see a professional.</p>"),
    ],
    faqs=[
        ("Is olive oil good for hair?",
         "Yes for cosmetic use: it coats the strand, softens, reduces frizz and limits breakage, especially on dry or damaged hair. Used as a pre-shampoo oil treatment, it's a simple, effective care."),
        ("How do you do an olive oil hair treatment?",
         "Warm a little oil, apply to lengths and ends, leave 30 min to overnight under a towel, then wash with shampoo (twice if needed)."),
        ("Does olive oil make hair grow?",
         "There is no strong evidence it speeds growth. Its benefit is cosmetic: it coats and softens the strand. For hair loss, see a professional."),
        ("Organic or regular olive oil for hair?",
         "For hair use, the difference is negligible: quality and freshness matter most. A good extra virgin works perfectly."),
        ("How do you get olive oil out of hair?",
         "Apply shampoo to dry or barely damp hair to emulsify the oil, massage, then rinse. Repeat once more if hair stays greasy."),
    ],
)
R["it"] = dict(
    title="Olio d'oliva per i capelli: benefici, maschera pre-shampoo e limiti",
    desc="Olio d'oliva sui capelli: impacco pre-shampoo, punte, crespo, cuoio capelluto. Metodo, quantità e cosa non aspettarsi.",
    h1="Olio d'oliva per i capelli",
    lede="L'olio d'oliva è un trattamento tradizionale per capelli: riveste la fibra, ammorbidisce e doma il crespo. Ecco come usarlo in impacco e cosa può — o non può — fare per i tuoi capelli.",
    section="haircare", datePublished="2026-05-04", disclaimer=None,
    keywords="olio d'oliva capelli, impacco olio d'oliva, maschera olio d'oliva, olio d'oliva capelli secchi, olio d'oliva punte",
    intro="Usato da tempo per i capelli, l'olio d'oliva riveste la fibra e limita la rottura. Non è un prodotto miracoloso, ma un buon emolliente per capelli secchi e doppie punte, se usato con moderazione.",
    key_facts=[
        "L'olio d'oliva riveste il fusto del capello: ammorbidisce, riduce il crespo e limita la rottura.",
        "Uso tipico: impacco pre-shampoo su lunghezze e punte, 30 min o tutta la notte, poi shampoo.",
        "È pesante: basta poca quantità e può servire un doppio shampoo.",
        "Nessuna prova solida che faccia 'crescere' i capelli; il beneficio è cosmetico.",
    ],
    sections=[
        ("Cosa fa l'olio d'oliva ai capelli",
         "<p>L'olio d'oliva è un emolliente che <strong>riveste il fusto</strong>. Leviga la cuticola, riduce il crespo, dona morbidezza e limita la rottura meccanica durante la spazzolatura. È utile soprattutto per capelli secchi, spessi, ricci o rovinati.</p>"),
        ("L'impacco pre-shampoo",
         "<p>Il metodo più efficace: intiepidisci un po' d'olio, applica su lunghezze e soprattutto punte (poco sulle radici se il cuoio è grasso), lascia in posa 30 minuti o tutta la notte sotto un asciugamano, poi lava con lo shampoo. Un pre-shampoo all'olio riduce la porosità e protegge la fibra durante il lavaggio.</p>"),
        ("Cuoio capelluto e punte",
         "<p>Un leggero massaggio del cuoio con olio d'oliva può aiutare ad ammorbidire le squame e alleviare la sensazione di secchezza. Sulle doppie punte l'olio non 'ripara' ma riveste temporaneamente per un aspetto più liscio.</p>"),
        ("Quantità e risciacquo",
         "<p>L'olio d'oliva è pesante: <strong>basta poco</strong>, altrimenti i capelli appaiono grassi e spenti. Emulsiona lo shampoo prima di bagnare per rimuovere meglio l'olio e prevedi un secondo lavaggio se serve.</p>"),
        ("Cosa non aspettarsi",
         "<p>Contrariamente ad alcune promesse, non c'è prova solida che l'olio d'oliva <strong>faccia crescere</strong> i capelli più in fretta. Il beneficio è cosmetico. Per la caduta o problemi del cuoio, consulta un professionista.</p>"),
    ],
    faqs=[
        ("L'olio d'oliva fa bene ai capelli?",
         "Sì per uso cosmetico: riveste la fibra, ammorbidisce, riduce il crespo e limita la rottura, soprattutto su capelli secchi o rovinati. In impacco pre-shampoo è una cura semplice ed efficace."),
        ("Come fare un impacco all'olio d'oliva?",
         "Intiepidisci un po' d'olio, applica su lunghezze e punte, lascia 30 min o tutta la notte sotto un asciugamano, poi lava con lo shampoo (due volte se serve)."),
        ("L'olio d'oliva fa crescere i capelli?",
         "Non c'è prova solida che acceleri la crescita. Il beneficio è cosmetico. Per la caduta, consulta un professionista."),
        ("Olio d'oliva bio o normale per i capelli?",
         "Per i capelli la differenza è trascurabile: contano qualità e freschezza. Un buon extravergine va benissimo."),
        ("Come togliere l'olio d'oliva dai capelli?",
         "Applica lo shampoo su capelli asciutti o poco umidi per emulsionare l'olio, massaggia, poi risciacqua. Ripeti se restano grassi."),
    ],
)
R["el"] = dict(
    title="Ελαιόλαδο για τα μαλλιά: οφέλη, μάσκα πριν το λούσιμο και όρια",
    desc="Ελαιόλαδο στα μαλλιά: θεραπεία λαδιού πριν το σαμπουάν, άκρες, φριζάρισμα, τριχωτό. Μέθοδος, ποσότητες και τι να μην περιμένετε.",
    h1="Ελαιόλαδο για τα μαλλιά",
    lede="Το ελαιόλαδο είναι παραδοσιακή φροντίδα μαλλιών: επικαλύπτει την τρίχα, απαλύνει και δαμάζει το φριζάρισμα. Δείτε πώς να το χρησιμοποιείτε ως θεραπεία λαδιού και τι μπορεί — ή δεν μπορεί — να κάνει.",
    section="haircare", datePublished="2026-05-04", disclaimer=None,
    keywords="ελαιόλαδο μαλλιά, μάσκα ελαιόλαδου, θεραπεία ελαιόλαδου μαλλιά, ελαιόλαδο ξηρά μαλλιά, ελαιόλαδο άκρες",
    intro="Σε χρήση εδώ και καιρό για τα μαλλιά, το ελαιόλαδο επικαλύπτει την τρίχα και περιορίζει το σπάσιμο. Δεν είναι θαυματουργό, αλλά καλός μαλακτικός παράγοντας για ξηρά μαλλιά και ψαλίδα, με μέτρο.",
    key_facts=[
        "Το ελαιόλαδο επικαλύπτει την τρίχα: απαλύνει, μειώνει το φριζάρισμα και περιορίζει το σπάσιμο.",
        "Τυπική χρήση: θεραπεία λαδιού πριν το σαμπουάν σε μήκη και άκρες, 30 λεπτά ως όλη νύχτα, μετά σαμπουάν.",
        "Είναι βαρύ: αρκεί μικρή ποσότητα και ίσως χρειαστεί διπλό σαμπουάν.",
        "Καμία ισχυρή απόδειξη ότι κάνει τα μαλλιά να «μεγαλώνουν»· το όφελος είναι κοσμετικό.",
    ],
    sections=[
        ("Τι κάνει το ελαιόλαδο στα μαλλιά",
         "<p>Το ελαιόλαδο είναι μαλακτικό που <strong>επικαλύπτει την τρίχα</strong>. Λειαίνει τη λέπι, μειώνει το φριζάρισμα, δίνει ευλυγισία και περιορίζει το μηχανικό σπάσιμο στο ξεμπέρδεμα. Χρήσιμο ιδίως για ξηρά, χοντρά, σγουρά ή ταλαιπωρημένα μαλλιά.</p>"),
        ("Η θεραπεία λαδιού πριν το σαμπουάν",
         "<p>Η πιο αποτελεσματική μέθοδος: ζεστάνετε λίγο ελαιόλαδο, απλώστε σε μήκη και κυρίως άκρες (λίγο στις ρίζες αν το τριχωτό είναι λιπαρό), αφήστε 30 λεπτά ως όλη νύχτα κάτω από πετσέτα, μετά λούστε. Το προ-σαμπουάν λάδι μειώνει το πορώδες και προστατεύει την τρίχα στο λούσιμο.</p>"),
        ("Τριχωτό και άκρες",
         "<p>Ένα ελαφρύ μασάζ του τριχωτού με ελαιόλαδο μπορεί να μαλακώσει τις φολίδες και να απαλύνει την αίσθηση ξηρότητας. Στην ψαλίδα, το λάδι δεν «επιδιορθώνει» αλλά επικαλύπτει προσωρινά για πιο λεία όψη.</p>"),
        ("Ποσότητα και ξέβγαλμα",
         "<p>Το ελαιόλαδο είναι βαρύ: <strong>αρκεί λίγο</strong>, αλλιώς τα μαλλιά δείχνουν λιπαρά και θαμπά. Δουλέψτε το σαμπουάν πριν βρέξετε για καλύτερη αφαίρεση και προβλέψτε δεύτερο λούσιμο αν χρειαστεί.</p>"),
        ("Τι να μην περιμένετε",
         "<p>Σε αντίθεση με κάποιες υποσχέσεις, δεν υπάρχει ισχυρή απόδειξη ότι το ελαιόλαδο <strong>μεγαλώνει</strong> τα μαλλιά πιο γρήγορα. Το όφελος είναι κοσμετικό. Για τριχόπτωση ή θέμα τριχωτού, συμβουλευτείτε επαγγελματία.</p>"),
    ],
    faqs=[
        ("Κάνει καλό το ελαιόλαδο στα μαλλιά;",
         "Ναι για κοσμετική χρήση: επικαλύπτει την τρίχα, απαλύνει, μειώνει το φριζάρισμα και περιορίζει το σπάσιμο, ιδίως σε ξηρά ή ταλαιπωρημένα μαλλιά."),
        ("Πώς κάνω θεραπεία με ελαιόλαδο;",
         "Ζεστάνετε λίγο λάδι, απλώστε σε μήκη και άκρες, αφήστε 30 λεπτά ως όλη νύχτα κάτω από πετσέτα, μετά λούστε (δύο φορές αν χρειαστεί)."),
        ("Το ελαιόλαδο μεγαλώνει τα μαλλιά;",
         "Δεν υπάρχει ισχυρή απόδειξη ότι επιταχύνει την ανάπτυξη. Το όφελος είναι κοσμετικό. Για τριχόπτωση, δείτε επαγγελματία."),
        ("Βιολογικό ή κανονικό ελαιόλαδο για τα μαλλιά;",
         "Για τα μαλλιά η διαφορά είναι αμελητέα: μετράνε η ποιότητα και η φρεσκάδα. Ένα καλό έξτρα παρθένο είναι μια χαρά."),
        ("Πώς φεύγει το ελαιόλαδο από τα μαλλιά;",
         "Βάλτε σαμπουάν σε στεγνά ή λίγο νωπά μαλλιά για να γαλακτωματοποιηθεί το λάδι, κάντε μασάζ, ξεβγάλτε. Επαναλάβετε αν μένουν λιπαρά."),
    ],
)

if __name__ == "__main__":
    print("Batch 3b:")
    write_guide_cluster("complete-guide-extra-virgin-olive-oil-for-the-face", F)
    write_guide_cluster("complete-guide-extra-virgin-olive-oil-for-hair", R)
