# -*- coding: utf-8 -*-
"""Batch 5 guides: cold-pressed-for-health, unfiltered-for-health. x4 languages.
Explains what the terms really mean (honestly) + the health/polyphenol angle."""
from guide_render import write_guide_cluster

DISC = {
    "fr": "Information générale, pas un avis médical. Pour une question de santé, consultez un professionnel.",
    "en": "General information, not medical advice. For any health concern, consult a professional.",
    "it": "Informazione generale, non un parere medico. Per problemi di salute, consulta un professionista.",
    "el": "Γενική πληροφόρηση, όχι ιατρική συμβουλή. Για θέματα υγείας, συμβουλευτείτε επαγγελματία.",
}

# ============================================ COLD-PRESSED FOR HEALTH =========
CP = {}
CP["en"] = dict(
    title="Cold-Pressed Olive Oil: benefits, what it really means, and is it healthier?",
    desc="What cold-pressed (cold-extracted) olive oil really means, its polyphenol benefits, whether it's healthier, and how to choose it. An honest guide.",
    h1="Cold-Pressed Olive Oil: benefits and what it really means",
    lede="'Cold-pressed' is on every premium olive oil label. Here's what it actually means, why it matters for polyphenols and flavour, and where the term is really just marketing.",
    section="health", datePublished="2026-05-04", disclaimer=DISC["en"],
    keywords="cold pressed olive oil benefits, is cold pressed olive oil better, cold pressed olive oil, cold extracted olive oil, cold pressed olive oil healthy",
    intro="Cold-pressed (more accurately, cold-extracted) olive oil is oil produced without heat. Heat would raise yield but degrade the delicate polyphenols and aromas. This guide explains what the term really means, the health angle, and how to choose — without the hype.",
    key_facts=[
        "Cold extraction means the oil is produced below about 27 °C, preserving heat-sensitive polyphenols and aromas.",
        "It is these polyphenols (hydroxytyrosol, oleocanthal) that carry the antioxidant benefits linked to olive oil.",
        "Most genuine extra virgin olive oil is already cold-extracted, so the label is often redundant.",
        "What matters most is that the oil is real extra virgin, fresh, and well stored — more than the 'cold-pressed' wording.",
    ],
    sections=[
        ("What 'cold-pressed' really means",
         "<p>Historically, olives were pressed; today most oil is separated by centrifuge. 'Cold-pressed' or, in EU terms, 'cold extraction', means the process stays <strong>below about 27 °C</strong>. Heat increases the amount of oil extracted but degrades the fragile <strong>polyphenols</strong> and aromatic compounds — so quality producers keep it cold.</p>"),
        ("Why it matters for health",
         "<p>The health interest of olive oil rests largely on its <strong>polyphenols</strong>, which are heat-sensitive. Cold extraction preserves more of them, along with vitamin E and aroma. These polyphenols underlie the EU-authorised claim that olive oil polyphenols help protect blood lipids from oxidative stress. In that sense, cold-extracted oil retains more of what makes olive oil beneficial.</p>"),
        ("The honest catch: it's often redundant",
         "<p>Here's what labels won't tell you: <strong>genuine extra virgin olive oil is, by definition, already cold-extracted</strong> and mechanically produced. So 'cold-pressed' on an extra virgin bottle is frequently a marketing repetition rather than an extra guarantee. It does not, on its own, prove higher quality.</p>"),
        ("How to actually choose a good oil",
         "<p>Rather than chase the 'cold-pressed' label, look for: the words <strong>extra virgin</strong>, a recent <strong>harvest date</strong>, protective <strong>dark glass</strong>, an origin you can trace, and a peppery, fresh taste. A fresh, well-stored extra virgin olive oil delivers the polyphenol benefits whether or not the front label repeats 'cold-pressed'.</p>"),
    ],
    faqs=[
        ("Is cold-pressed olive oil better?",
         "Cold extraction preserves more polyphenols and aroma than hot processing, so it is preferable in principle. But genuine extra virgin olive oil is already cold-extracted, so the label alone doesn't guarantee superiority — freshness and real extra virgin quality matter more."),
        ("What are the benefits of cold-pressed olive oil?",
         "By avoiding heat, it retains more polyphenols (antioxidant, anti-inflammatory compounds), vitamin E and aroma. These are the components linked to olive oil's health benefits within a balanced diet."),
        ("Is cold-pressed olive oil healthy?",
         "Yes, as part of a balanced diet. It is a good source of monounsaturated fat and polyphenols. Its benefits come over time, not from any single dose."),
        ("Is cold-pressed the same as extra virgin?",
         "Not exactly. 'Extra virgin' is a graded quality category; 'cold-pressed' describes the low-temperature process. In practice, real extra virgin oil is already cold-extracted, so the two usually go together."),
        ("Can you cook with cold-pressed olive oil?",
         "Yes. Like any extra virgin olive oil, it is stable enough for most home cooking. To preserve its heat-sensitive polyphenols, keep some for raw finishing."),
    ],
)
# FR/IT/EL adapt the same content
CP["fr"] = dict(
    title="Huile d'olive pressée à froid : bienfaits, ce que ça signifie vraiment",
    desc="Ce que signifie vraiment l'huile d'olive pressée à froid (extraite à froid), ses bienfaits en polyphénols, est-elle meilleure, et comment la choisir. Un guide honnête.",
    h1="Huile d'olive pressée à froid : bienfaits et vérité sur le terme",
    lede="« Pressée à froid » figure sur toutes les huiles premium. Voici ce que cela signifie réellement, pourquoi c'est important pour les polyphénols et le goût, et où le terme relève surtout du marketing.",
    section="health", datePublished="2026-05-04", disclaimer=DISC["fr"],
    keywords="huile d'olive pressée à froid, extraction à froid huile d'olive, huile d'olive première pression à froid bienfaits, huile olive extraite à froid",
    intro="L'huile d'olive pressée à froid (plus exactement extraite à froid) est produite sans chaleur. La chaleur augmenterait le rendement mais dégraderait les polyphénols fragiles et les arômes. Ce guide explique ce que le terme signifie vraiment, l'aspect santé, et comment choisir — sans battage.",
    key_facts=[
        "L'extraction à froid signifie une production en dessous d'environ 27 °C, ce qui préserve les polyphénols et arômes sensibles à la chaleur.",
        "Ce sont ces polyphénols (hydroxytyrosol, oléocanthal) qui portent les bienfaits antioxydants associés à l'huile d'olive.",
        "La plupart des vraies huiles extra vierges sont déjà extraites à froid : la mention est souvent redondante.",
        "L'essentiel est une vraie extra vierge, fraîche et bien conservée, plus que le mot « pressée à froid ».",
    ],
    sections=[
        ("Ce que « pressée à froid » signifie vraiment",
         "<p>Autrefois on pressait les olives ; aujourd'hui l'huile est surtout séparée par centrifugation. « Pressée à froid » ou, en termes européens, « extraction à froid », signifie que le procédé reste <strong>en dessous d'environ 27 °C</strong>. La chaleur augmente la quantité extraite mais dégrade les <strong>polyphénols</strong> fragiles et les composés aromatiques.</p>"),
        ("Pourquoi c'est important pour la santé",
         "<p>L'intérêt santé de l'huile d'olive repose largement sur ses <strong>polyphénols</strong>, sensibles à la chaleur. L'extraction à froid en préserve davantage, avec la vitamine E et les arômes. Ces polyphénols sous-tendent l'allégation européenne selon laquelle ils aident à protéger les lipides sanguins du stress oxydatif.</p>"),
        ("Le point honnête : c'est souvent redondant",
         "<p>Ce que les étiquettes ne disent pas : <strong>une vraie huile d'olive extra vierge est, par définition, déjà extraite à froid</strong>. La mention « pressée à froid » sur une extra vierge est donc souvent une répétition marketing, pas une garantie supplémentaire de qualité.</p>"),
        ("Comment vraiment choisir",
         "<p>Plutôt que le label « pressée à froid », cherchez : la mention <strong>extra vierge</strong>, une <strong>date de récolte</strong> récente, un <strong>verre foncé</strong> protecteur, une origine traçable et un goût frais et poivré. Une extra vierge fraîche et bien conservée apporte les polyphénols, que l'étiquette répète ou non « pressée à froid ».</p>"),
    ],
    faqs=[
        ("L'huile d'olive pressée à froid est-elle meilleure ?",
         "L'extraction à froid préserve plus de polyphénols et d'arômes qu'un procédé chaud, donc c'est préférable en principe. Mais une vraie extra vierge est déjà extraite à froid : la mention seule ne garantit pas la supériorité ; la fraîcheur compte davantage."),
        ("Quels sont les bienfaits de l'huile d'olive pressée à froid ?",
         "En évitant la chaleur, elle conserve plus de polyphénols (antioxydants, anti-inflammatoires), de vitamine E et d'arômes — les composés liés aux bienfaits de l'huile d'olive dans une alimentation équilibrée."),
        ("L'huile d'olive pressée à froid est-elle bonne pour la santé ?",
         "Oui, dans le cadre d'une alimentation équilibrée. C'est une bonne source de graisses mono-insaturées et de polyphénols. Les bienfaits s'installent dans la durée."),
        ("Pressée à froid, est-ce pareil qu'extra vierge ?",
         "Pas exactement. « Extra vierge » est une catégorie de qualité ; « pressée à froid » décrit le procédé à basse température. En pratique, une vraie extra vierge est déjà extraite à froid."),
        ("Peut-on cuisiner à l'huile pressée à froid ?",
         "Oui. Comme toute extra vierge, elle est assez stable pour la plupart des cuissons domestiques. Gardez-en à cru pour préserver les polyphénols sensibles à la chaleur."),
    ],
)
CP["it"] = dict(
    title="Olio d'oliva spremuto a freddo: benefici e cosa significa davvero",
    desc="Cosa significa davvero l'olio d'oliva spremuto a freddo (estratto a freddo), i benefici dei polifenoli, se è più sano e come sceglierlo. Una guida onesta.",
    h1="Olio d'oliva spremuto a freddo: benefici e verità sul termine",
    lede="'Spremuto a freddo' è su ogni olio premium. Ecco cosa significa davvero, perché conta per polifenoli e gusto, e dove il termine è soprattutto marketing.",
    section="health", datePublished="2026-05-04", disclaimer=DISC["it"],
    keywords="olio d'oliva spremuto a freddo, estrazione a freddo olio d'oliva, benefici olio spremuto a freddo, olio estratto a freddo",
    intro="L'olio d'oliva spremuto a freddo (più correttamente estratto a freddo) è prodotto senza calore. Il calore aumenterebbe la resa ma degraderebbe i polifenoli fragili e gli aromi. Questa guida spiega cosa significa il termine, l'aspetto salute e come scegliere.",
    key_facts=[
        "L'estrazione a freddo significa produzione sotto i 27 °C circa, preservando polifenoli e aromi sensibili al calore.",
        "Sono questi polifenoli (idrossitirosolo, oleocantale) a portare i benefici antiossidanti dell'olio d'oliva.",
        "La maggior parte dei veri extravergini è già estratta a freddo: la dicitura è spesso ridondante.",
        "Conta di più un vero extravergine fresco e ben conservato che la scritta 'spremuto a freddo'.",
    ],
    sections=[
        ("Cosa significa davvero 'spremuto a freddo'",
         "<p>Un tempo le olive si premevano; oggi l'olio si separa per centrifuga. 'Spremuto a freddo' o, in termini UE, 'estrazione a freddo', significa che il processo resta <strong>sotto i 27 °C circa</strong>. Il calore aumenta la quantità estratta ma degrada i <strong>polifenoli</strong> fragili e i composti aromatici.</p>"),
        ("Perché conta per la salute",
         "<p>L'interesse per la salute dell'olio d'oliva si basa in gran parte sui <strong>polifenoli</strong>, sensibili al calore. L'estrazione a freddo ne preserva di più, con vitamina E e aromi. Questi polifenoli sono alla base del claim UE sulla protezione dei lipidi del sangue dall'ossidazione.</p>"),
        ("Il punto onesto: spesso è ridondante",
         "<p>Ciò che le etichette non dicono: <strong>un vero olio extravergine è, per definizione, già estratto a freddo</strong>. La dicitura 'spremuto a freddo' su un extravergine è quindi spesso una ripetizione di marketing, non una garanzia extra.</p>"),
        ("Come scegliere davvero",
         "<p>Più che l'etichetta 'spremuto a freddo', cerca: la dicitura <strong>extravergine</strong>, una <strong>data di raccolta</strong> recente, il <strong>vetro scuro</strong>, un'origine tracciabile e un gusto fresco e piccante. Un extravergine fresco e ben conservato apporta i polifenoli.</p>"),
    ],
    faqs=[
        ("L'olio spremuto a freddo è migliore?",
         "L'estrazione a freddo preserva più polifenoli e aromi del processo a caldo, quindi in linea di principio è preferibile. Ma un vero extravergine è già estratto a freddo: la dicitura da sola non garantisce superiorità."),
        ("Quali sono i benefici dell'olio spremuto a freddo?",
         "Evitando il calore conserva più polifenoli, vitamina E e aromi — i composti legati ai benefici dell'olio d'oliva in una dieta equilibrata."),
        ("L'olio spremuto a freddo fa bene?",
         "Sì, in una dieta equilibrata. È una buona fonte di grassi monoinsaturi e polifenoli. I benefici arrivano nel tempo."),
        ("Spremuto a freddo è come extravergine?",
         "Non esattamente. 'Extravergine' è una categoria di qualità; 'spremuto a freddo' descrive il processo a bassa temperatura. In pratica un vero extravergine è già estratto a freddo."),
        ("Si può cucinare con l'olio spremuto a freddo?",
         "Sì. Come ogni extravergine è abbastanza stabile per gran parte delle cotture. Tienine un po' a crudo per preservare i polifenoli."),
    ],
)
CP["el"] = dict(
    title="Ελαιόλαδο ψυχρής έκθλιψης: οφέλη και τι σημαίνει πραγματικά",
    desc="Τι σημαίνει πραγματικά το ελαιόλαδο ψυχρής έκθλιψης (ψυχρής εκχύλισης), τα οφέλη των πολυφαινολών, αν είναι πιο υγιεινό και πώς να το επιλέξετε.",
    h1="Ελαιόλαδο ψυχρής έκθλιψης: οφέλη και η αλήθεια για τον όρο",
    lede="Το «ψυχρής έκθλιψης» υπάρχει σε κάθε premium ελαιόλαδο. Δείτε τι σημαίνει πραγματικά, γιατί μετράει για πολυφαινόλες και γεύση, και πού ο όρος είναι κυρίως μάρκετινγκ.",
    section="health", datePublished="2026-05-04", disclaimer=DISC["el"],
    keywords="ελαιόλαδο ψυχρής έκθλιψης, ψυχρή εκχύλιση ελαιόλαδο, οφέλη ψυχρής έκθλιψης, ελαιόλαδο εκχύλιση εν ψυχρώ",
    intro="Το ελαιόλαδο ψυχρής έκθλιψης (πιο σωστά, ψυχρής εκχύλισης) παράγεται χωρίς θερμότητα. Η θερμότητα θα αύξανε την απόδοση αλλά θα υποβάθμιζε τις εύθραυστες πολυφαινόλες και τα αρώματα.",
    key_facts=[
        "Η ψυχρή εκχύλιση σημαίνει παραγωγή κάτω από ~27 °C, διατηρώντας πολυφαινόλες και αρώματα ευαίσθητα στη θερμότητα.",
        "Αυτές οι πολυφαινόλες (υδροξυτυροσόλη, ελαιοκανθάλη) φέρουν τα αντιοξειδωτικά οφέλη του ελαιόλαδου.",
        "Τα περισσότερα γνήσια έξτρα παρθένα είναι ήδη ψυχρής εκχύλισης: η ένδειξη είναι συχνά περιττή.",
        "Μετράει περισσότερο ένα γνήσιο, φρέσκο, καλά αποθηκευμένο έξτρα παρθένο παρά η φράση «ψυχρής έκθλιψης».",
    ],
    sections=[
        ("Τι σημαίνει πραγματικά «ψυχρής έκθλιψης»",
         "<p>Παλιά οι ελιές πιέζονταν· σήμερα το λάδι διαχωρίζεται με φυγοκέντρηση. «Ψυχρής έκθλιψης» ή, σε όρους ΕΕ, «ψυχρή εκχύλιση», σημαίνει ότι η διαδικασία μένει <strong>κάτω από ~27 °C</strong>. Η θερμότητα αυξάνει την ποσότητα αλλά υποβαθμίζει τις <strong>πολυφαινόλες</strong> και τα αρωματικά συστατικά.</p>"),
        ("Γιατί μετράει για την υγεία",
         "<p>Το ενδιαφέρον του ελαιόλαδου για την υγεία στηρίζεται σε μεγάλο βαθμό στις <strong>πολυφαινόλες</strong>, ευαίσθητες στη θερμότητα. Η ψυχρή εκχύλιση διατηρεί περισσότερες, μαζί με βιταμίνη E και αρώματα. Αυτές στηρίζουν τον ισχυρισμό της ΕΕ για προστασία των λιπιδίων του αίματος.</p>"),
        ("Το τίμιο σημείο: συχνά περιττό",
         "<p>Αυτό που δεν λένε οι ετικέτες: <strong>ένα γνήσιο έξτρα παρθένο ελαιόλαδο είναι εξ ορισμού ήδη ψυχρής εκχύλισης</strong>. Η ένδειξη «ψυχρής έκθλιψης» σε έξτρα παρθένο είναι συχνά επανάληψη μάρκετινγκ, όχι επιπλέον εγγύηση.</p>"),
        ("Πώς να επιλέξετε σωστά",
         "<p>Αντί για την ένδειξη «ψυχρής έκθλιψης», ψάξτε: τη λέξη <strong>έξτρα παρθένο</strong>, πρόσφατη <strong>ημερομηνία συγκομιδής</strong>, προστατευτικό <strong>σκούρο γυαλί</strong>, ιχνηλάσιμη προέλευση και φρέσκια, πικάντικη γεύση.</p>"),
    ],
    faqs=[
        ("Είναι καλύτερο το ελαιόλαδο ψυχρής έκθλιψης;",
         "Η ψυχρή εκχύλιση διατηρεί περισσότερες πολυφαινόλες και αρώματα από τη θερμή επεξεργασία, άρα κατ' αρχήν προτιμότερο. Όμως ένα γνήσιο έξτρα παρθένο είναι ήδη ψυχρής εκχύλισης."),
        ("Ποια τα οφέλη του;",
         "Αποφεύγοντας τη θερμότητα διατηρεί περισσότερες πολυφαινόλες, βιταμίνη E και αρώματα — τα συστατικά που συνδέονται με τα οφέλη του ελαιόλαδου."),
        ("Είναι υγιεινό;",
         "Ναι, σε ισορροπημένη διατροφή. Καλή πηγή μονοακόρεστων και πολυφαινολών. Τα οφέλη έρχονται με τον χρόνο."),
        ("Ψυχρής έκθλιψης είναι το ίδιο με έξτρα παρθένο;",
         "Όχι ακριβώς. «Έξτρα παρθένο» είναι κατηγορία ποιότητας· «ψυχρής έκθλιψης» περιγράφει τη διαδικασία. Στην πράξη το γνήσιο έξτρα παρθένο είναι ήδη ψυχρής εκχύλισης."),
        ("Μαγειρεύεται;",
         "Ναι. Όπως κάθε έξτρα παρθένο, είναι αρκετά σταθερό. Κρατήστε λίγο ωμό για τις πολυφαινόλες."),
    ],
)

# ============================================== UNFILTERED FOR HEALTH =========
UF = {}
UF["en"] = dict(
    title="Unfiltered Olive Oil: benefits, drawbacks, and is it better than filtered?",
    desc="What unfiltered (cloudy) olive oil is, its real benefits and drawbacks, whether it's healthier than filtered, and how to store it. An honest comparison.",
    h1="Unfiltered Olive Oil: benefits and the filtered-vs-unfiltered truth",
    lede="Cloudy 'unfiltered' olive oil is marketed as more natural and richer. There's truth in that — but also a real drawback most sellers skip. Here's the honest picture.",
    section="health", datePublished="2026-05-04", disclaimer=DISC["en"],
    keywords="unfiltered olive oil benefits, unfiltered olive oil uses, is unfiltered olive oil better, olive oil filtered or unfiltered, cloudy olive oil",
    intro="Unfiltered (or 'veiled') olive oil keeps the tiny olive fragments and moisture that filtering removes, which makes it cloudy. It can taste fuller and fresher, but that same sediment is also its weakness. Here's what unfiltered oil really offers, and when filtered is the smarter choice.",
    key_facts=[
        "Unfiltered olive oil retains micro-particles of olive pulp and a little water, giving a cloudy look and a fuller flavour.",
        "Fresh from harvest, it can have slightly more polyphenols and a vivid taste.",
        "The catch: that sediment and moisture speed up spoilage — unfiltered oil degrades and can ferment faster.",
        "Filtered oil is clearer and keeps longer; neither is simply 'healthier' — it's a trade-off of freshness vs shelf life.",
    ],
    sections=[
        ("What 'unfiltered' means",
         "<p>After extraction, olive oil can be filtered to remove suspended <strong>olive particles and water</strong>, or left unfiltered ('veiled', <em>grezzo</em>). Unfiltered oil is cloudy and often tastes fuller, greener and more 'just-pressed', which is why it appeals to enthusiasts, especially in the weeks right after harvest.</p>"),
        ("The benefits — while it's fresh",
         "<p>Right after pressing, unfiltered oil can carry <strong>slightly more polyphenols</strong> and a more intense flavour, because nothing has been stripped out. For a few weeks it can be a genuinely vibrant, aromatic oil — best enjoyed young, raw, on bread, soups and salads.</p>"),
        ("The honest drawback",
         "<p>Here's what marketing tends to omit: the suspended particles and residual water are a <strong>source of degradation</strong>. They can trigger fermentation and off-flavours, so unfiltered oil generally has a <strong>shorter shelf life</strong> and must be used quickly and stored cool and dark. Filtered oil is more stable over time.</p>"),
        ("Filtered vs unfiltered: which to choose",
         "<p>Choose <strong>unfiltered</strong> if you'll use it fresh, quickly, for its lively taste. Choose <strong>filtered</strong> if you want a cleaner, longer-lasting oil for everyday use. From a health standpoint both deliver olive oil's polyphenols and monounsaturated fat; the real difference is freshness versus stability, not one being categorically 'healthier'.</p>"),
    ],
    faqs=[
        ("What are the benefits of unfiltered olive oil?",
         "Fresh from harvest it can have slightly more polyphenols and a fuller, greener flavour, since nothing is stripped out. It's best enjoyed young and raw."),
        ("Is unfiltered olive oil better than filtered?",
         "Not categorically. Unfiltered can taste more vivid and fresh, but its sediment and moisture make it spoil faster. Filtered is clearer and lasts longer. It's a trade-off between freshness and shelf life."),
        ("Is unfiltered olive oil healthier?",
         "Both deliver olive oil's polyphenols and monounsaturated fat. Unfiltered may start slightly higher in polyphenols but degrades faster, so a fresh filtered oil can end up just as good. Freshness matters more than the filter."),
        ("How do you store unfiltered olive oil?",
         "Use it quickly and keep it cool, dark and sealed. Its sediment and moisture make it more prone to fermentation and off-flavours than filtered oil."),
        ("What are the uses of unfiltered olive oil?",
         "Best used raw and young: drizzled on bread, soups, grilled vegetables and salads, where its fuller, fresher flavour shines."),
    ],
)
UF["fr"] = dict(
    title="Huile d'olive non filtrée : bienfaits, inconvénients, mieux que filtrée ?",
    desc="Ce qu'est l'huile d'olive non filtrée (trouble), ses vrais bienfaits et inconvénients, est-elle meilleure que la filtrée, et comment la conserver. Comparaison honnête.",
    h1="Huile d'olive non filtrée : bienfaits et vérité filtrée/non filtrée",
    lede="L'huile d'olive « non filtrée » et trouble est vendue comme plus naturelle et plus riche. C'est en partie vrai — mais elle a aussi un vrai inconvénient que les vendeurs passent sous silence.",
    section="health", datePublished="2026-05-04", disclaimer=DISC["fr"],
    keywords="huile d'olive non filtrée, bienfaits huile d'olive non filtrée, huile d'olive filtrée ou non, huile d'olive trouble, huile d'olive brute",
    intro="L'huile d'olive non filtrée (ou « voilée ») conserve les fines particules d'olive et l'humidité que le filtrage retire, ce qui la rend trouble. Elle peut avoir un goût plus plein et plus frais, mais ce même dépôt est aussi sa faiblesse.",
    key_facts=[
        "L'huile non filtrée garde des micro-particules de pulpe et un peu d'eau, d'où son aspect trouble et un goût plus plein.",
        "Fraîche après récolte, elle peut contenir un peu plus de polyphénols et un goût vif.",
        "Le revers : ce dépôt et cette humidité accélèrent l'altération — elle se dégrade et fermente plus vite.",
        "La filtrée est plus claire et se conserve mieux ; aucune n'est simplement « plus saine » — c'est un compromis fraîcheur/conservation.",
    ],
    sections=[
        ("Ce que « non filtrée » signifie",
         "<p>Après extraction, l'huile peut être filtrée pour retirer les <strong>particules d'olive et l'eau</strong> en suspension, ou laissée non filtrée (« voilée »). L'huile non filtrée est trouble et a souvent un goût plus plein, plus vert et plus « fraîchement pressé », ce qui séduit les amateurs, surtout juste après la récolte.</p>"),
        ("Les bienfaits — tant qu'elle est fraîche",
         "<p>Juste après pressage, l'huile non filtrée peut porter <strong>un peu plus de polyphénols</strong> et un arôme plus intense, car rien n'a été retiré. Pendant quelques semaines, elle peut être une huile vraiment vibrante et parfumée — à savourer jeune, à cru, sur pain, soupes et salades.</p>"),
        ("L'inconvénient honnête",
         "<p>Ce que le marketing tait : les particules et l'eau résiduelle sont une <strong>source d'altération</strong>. Elles peuvent déclencher fermentation et faux-goûts, si bien que l'huile non filtrée a une <strong>durée de conservation plus courte</strong> et doit être consommée vite, au frais et à l'abri de la lumière. La filtrée est plus stable dans le temps.</p>"),
        ("Filtrée ou non filtrée : que choisir",
         "<p>Choisissez la <strong>non filtrée</strong> si vous la consommez fraîche et rapidement, pour son goût vif. Choisissez la <strong>filtrée</strong> pour une huile plus nette et durable au quotidien. Côté santé, les deux apportent les polyphénols et les graisses mono-insaturées ; la vraie différence est fraîcheur contre stabilité.</p>"),
    ],
    faqs=[
        ("Quels sont les bienfaits de l'huile d'olive non filtrée ?",
         "Fraîche après récolte, elle peut avoir un peu plus de polyphénols et un goût plus plein et plus vert, car rien n'a été retiré. À savourer jeune et à cru."),
        ("L'huile d'olive non filtrée est-elle meilleure que la filtrée ?",
         "Pas catégoriquement. La non filtrée peut sembler plus vive, mais son dépôt et son humidité la font s'altérer plus vite. La filtrée est plus claire et se conserve mieux. C'est un compromis."),
        ("L'huile non filtrée est-elle plus saine ?",
         "Les deux apportent polyphénols et graisses mono-insaturées. La non filtrée peut démarrer un peu plus haut en polyphénols mais se dégrade plus vite ; la fraîcheur compte plus que le filtrage."),
        ("Comment conserver l'huile d'olive non filtrée ?",
         "Consommez-la vite, au frais, à l'abri de la lumière et bien fermée. Son dépôt et son humidité la rendent plus sujette à la fermentation que la filtrée."),
        ("Quels usages pour l'huile non filtrée ?",
         "À cru et jeune de préférence : filet sur pain, soupes, légumes grillés et salades, où son goût plein et frais s'exprime."),
    ],
)
UF["it"] = dict(
    title="Olio d'oliva non filtrato: benefici, difetti ed è meglio del filtrato?",
    desc="Cos'è l'olio d'oliva non filtrato (velato), i suoi veri benefici e difetti, se è più sano del filtrato e come conservarlo. Un confronto onesto.",
    h1="Olio d'oliva non filtrato: benefici e verità filtrato/non filtrato",
    lede="L'olio 'non filtrato' e velato è venduto come più naturale e ricco. C'è del vero — ma ha anche un difetto reale che i venditori tacciono.",
    section="health", datePublished="2026-05-04", disclaimer=DISC["it"],
    keywords="olio d'oliva non filtrato, benefici olio non filtrato, olio d'oliva filtrato o non, olio d'oliva velato, olio grezzo",
    intro="L'olio d'oliva non filtrato (o 'velato') conserva le fini particelle di oliva e l'umidità che la filtrazione toglie, il che lo rende torbido. Può avere un gusto più pieno e fresco, ma quello stesso deposito è anche il suo punto debole.",
    key_facts=[
        "L'olio non filtrato conserva micro-particelle di polpa e un po' d'acqua, da cui l'aspetto velato e un gusto più pieno.",
        "Fresco dopo la raccolta, può avere qualche polifenolo in più e un gusto vivace.",
        "Il rovescio: deposito e umidità accelerano il deterioramento — si degrada e fermenta più in fretta.",
        "Il filtrato è più limpido e si conserva meglio; nessuno è semplicemente 'più sano' — è un compromesso freschezza/conservazione.",
    ],
    sections=[
        ("Cosa significa 'non filtrato'",
         "<p>Dopo l'estrazione, l'olio può essere filtrato per togliere <strong>particelle di oliva e acqua</strong> in sospensione, o lasciato non filtrato ('velato', grezzo). L'olio non filtrato è torbido e spesso ha un gusto più pieno, verde e 'appena franto', apprezzato dagli appassionati soprattutto subito dopo la raccolta.</p>"),
        ("I benefici — finché è fresco",
         "<p>Subito dopo la frangitura può avere <strong>qualche polifenolo in più</strong> e un aroma più intenso, perché nulla è stato tolto. Per qualche settimana può essere un olio davvero vibrante — da gustare giovane, a crudo, su pane, zuppe e insalate.</p>"),
        ("Il difetto onesto",
         "<p>Ciò che il marketing tace: particelle e acqua residua sono una <strong>fonte di deterioramento</strong>. Possono innescare fermentazione e difetti, quindi l'olio non filtrato ha in genere una <strong>durata più breve</strong> e va consumato in fretta, al fresco e al buio. Il filtrato è più stabile nel tempo.</p>"),
        ("Filtrato o non filtrato: quale scegliere",
         "<p>Scegli il <strong>non filtrato</strong> se lo usi fresco e in fretta, per il gusto vivace. Scegli il <strong>filtrato</strong> per un olio più limpido e duraturo. Sul piano della salute entrambi apportano polifenoli e grassi monoinsaturi; la differenza è freschezza contro stabilità.</p>"),
    ],
    faqs=[
        ("Quali sono i benefici dell'olio non filtrato?",
         "Fresco dopo la raccolta può avere qualche polifenolo in più e un gusto più pieno e verde, perché nulla è tolto. Da gustare giovane e a crudo."),
        ("L'olio non filtrato è migliore del filtrato?",
         "Non categoricamente. Il non filtrato può sembrare più vivace, ma deposito e umidità lo fanno deteriorare prima. Il filtrato è più limpido e dura di più. È un compromesso."),
        ("L'olio non filtrato è più sano?",
         "Entrambi apportano polifenoli e grassi monoinsaturi. Il non filtrato può partire un po' più alto ma si degrada prima; la freschezza conta più del filtro."),
        ("Come si conserva l'olio non filtrato?",
         "Consumalo in fretta, al fresco, al buio e ben chiuso. Deposito e umidità lo rendono più soggetto a fermentazione del filtrato."),
        ("Quali usi per l'olio non filtrato?",
         "A crudo e giovane: filo su pane, zuppe, verdure grigliate e insalate, dove il gusto pieno e fresco si esprime."),
    ],
)
UF["el"] = dict(
    title="Αδιύλιστο ελαιόλαδο: οφέλη, μειονεκτήματα και είναι καλύτερο από το διυλισμένο;",
    desc="Τι είναι το αδιύλιστο (θολό) ελαιόλαδο, τα πραγματικά οφέλη και μειονεκτήματα, αν είναι πιο υγιεινό από το διυλισμένο και πώς να το αποθηκεύετε.",
    h1="Αδιύλιστο ελαιόλαδο: οφέλη και η αλήθεια διυλισμένο/αδιύλιστο",
    lede="Το θολό «αδιύλιστο» ελαιόλαδο διαφημίζεται ως πιο φυσικό και πλούσιο. Υπάρχει αλήθεια σε αυτό — αλλά και ένα πραγματικό μειονέκτημα που οι πωλητές αποσιωπούν.",
    section="health", datePublished="2026-05-04", disclaimer=DISC["el"],
    keywords="αδιύλιστο ελαιόλαδο, οφέλη αδιύλιστου ελαιόλαδου, ελαιόλαδο διυλισμένο ή αδιύλιστο, θολό ελαιόλαδο, ανεπεξέργαστο ελαιόλαδο",
    intro="Το αδιύλιστο (ή «θολό») ελαιόλαδο διατηρεί τα μικρά σωματίδια ελιάς και την υγρασία που η διύλιση αφαιρεί, γι' αυτό είναι θολό. Μπορεί να έχει πληρέστερη, φρέσκια γεύση, αλλά το ίδιο ίζημα είναι και η αδυναμία του.",
    key_facts=[
        "Το αδιύλιστο διατηρεί μικρο-σωματίδια πούλπας και λίγο νερό, εξ ου η θολή όψη και η πληρέστερη γεύση.",
        "Φρέσκο μετά τη συγκομιδή, μπορεί να έχει λίγο περισσότερες πολυφαινόλες και ζωντανή γεύση.",
        "Το μειονέκτημα: το ίζημα και η υγρασία επιταχύνουν την αλλοίωση — υποβαθμίζεται και ζυμώνεται πιο γρήγορα.",
        "Το διυλισμένο είναι πιο διαυγές και διατηρείται περισσότερο· κανένα δεν είναι απλώς «πιο υγιεινό» — είναι συμβιβασμός.",
    ],
    sections=[
        ("Τι σημαίνει «αδιύλιστο»",
         "<p>Μετά την εκχύλιση, το λάδι μπορεί να διυλιστεί για να αφαιρεθούν <strong>σωματίδια ελιάς και νερό</strong> σε αιώρηση, ή να μείνει αδιύλιστο («θολό»). Το αδιύλιστο είναι θολό και συχνά έχει πληρέστερη, πράσινη, «μόλις πατημένη» γεύση, που αρέσει στους λάτρεις ιδίως αμέσως μετά τη συγκομιδή.</p>"),
        ("Τα οφέλη — όσο είναι φρέσκο",
         "<p>Αμέσως μετά την έκθλιψη μπορεί να έχει <strong>λίγο περισσότερες πολυφαινόλες</strong> και εντονότερο άρωμα, αφού τίποτα δεν αφαιρέθηκε. Για λίγες εβδομάδες μπορεί να είναι ένα πραγματικά ζωντανό λάδι — απολαυστικό νέο, ωμό, σε ψωμί, σούπες και σαλάτες.</p>"),
        ("Το τίμιο μειονέκτημα",
         "<p>Αυτό που αποσιωπά το μάρκετινγκ: τα σωματίδια και το υπολειπόμενο νερό είναι <strong>πηγή αλλοίωσης</strong>. Μπορούν να προκαλέσουν ζύμωση και ελαττώματα γεύσης, οπότε το αδιύλιστο έχει γενικά <strong>μικρότερη διάρκεια ζωής</strong> και πρέπει να καταναλωθεί γρήγορα, σε δροσερό, σκοτεινό μέρος.</p>"),
        ("Διυλισμένο ή αδιύλιστο: τι να επιλέξετε",
         "<p>Επιλέξτε <strong>αδιύλιστο</strong> αν το χρησιμοποιήσετε φρέσκο και γρήγορα, για τη ζωντανή γεύση. Επιλέξτε <strong>διυλισμένο</strong> για πιο διαυγές, ανθεκτικό λάδι καθημερινής χρήσης. Από πλευράς υγείας και τα δύο δίνουν πολυφαινόλες και μονοακόρεστα.</p>"),
    ],
    faqs=[
        ("Ποια τα οφέλη του αδιύλιστου ελαιόλαδου;",
         "Φρέσκο μετά τη συγκομιδή μπορεί να έχει λίγο περισσότερες πολυφαινόλες και πληρέστερη, πράσινη γεύση, αφού τίποτα δεν αφαιρείται. Απολαυστικό νέο και ωμό."),
        ("Είναι το αδιύλιστο καλύτερο από το διυλισμένο;",
         "Όχι κατηγορηματικά. Το αδιύλιστο μπορεί να είναι πιο ζωντανό, αλλά το ίζημα και η υγρασία το αλλοιώνουν πιο γρήγορα. Το διυλισμένο είναι πιο διαυγές και διαρκεί περισσότερο. Συμβιβασμός."),
        ("Είναι πιο υγιεινό το αδιύλιστο;",
         "Και τα δύο δίνουν πολυφαινόλες και μονοακόρεστα. Το αδιύλιστο ίσως ξεκινά λίγο ψηλότερα αλλά υποβαθμίζεται πιο γρήγορα· η φρεσκάδα μετράει πιο πολύ από το φιλτράρισμα."),
        ("Πώς αποθηκεύεται το αδιύλιστο;",
         "Καταναλώστε το γρήγορα, σε δροσερό, σκοτεινό μέρος, καλά κλεισμένο. Το ίζημα και η υγρασία το κάνουν πιο επιρρεπές στη ζύμωση."),
        ("Ποιες χρήσεις για το αδιύλιστο;",
         "Ωμό και νέο: σε ψωμί, σούπες, ψητά λαχανικά και σαλάτες, όπου λάμπει η πλήρης, φρέσκια γεύση."),
    ],
)

if __name__ == "__main__":
    print("Batch 5 guides:")
    write_guide_cluster("complete-guide-cold-pressed-olive-oil-for-health", CP)
    write_guide_cluster("complete-guide-unfiltered-olive-oil-for-health", UF)
