# -*- coding: utf-8 -*-
"""Authentic baked falafel (falafel au four) x4 languages."""
from recipe_render import write_cluster

C = {}
C["fr"] = dict(
    title="Falafels au four : recette croustillante et saine à l'huile d'olive",
    desc="Vrais falafels au four, croustillants dehors et moelleux dedans : pois chiches secs trempés, herbes, épices et huile d'olive. Astuce anti-émiettement, sauce tahini et cuisson.",
    h1="Falafels au four à l'huile d'olive",
    lede="Des falafels dorés au four, plus légers que frits mais tout aussi savoureux. Le secret tient à un détail : des pois chiches secs trempés (jamais en conserve), mixés crus avec des herbes et des épices, puis rôtis à l'huile d'olive.",
    info="<strong>Préparation :</strong> 20 min (+ trempage 12 h) · <strong>Cuisson :</strong> 30 min · <strong>Pour :</strong> 4 personnes · <strong>Cuisine :</strong> moyen-orientale · <strong>Difficulté :</strong> facile",
    intro="Le falafel réussi n'est pas une question de friture mais de base : des pois chiches secs, trempés puis mixés crus. Les pois chiches en conserve (déjà cuits) rendent une pâte humide qui s'émiette. Au four, avec un bon filet d'huile d'olive, on obtient une croûte dorée et un cœur moelleux, sans bain de friture.",
    ingredients=[
        "250 g de pois chiches secs (trempés 12 h, non cuits)",
        "1 oignon",
        "3 gousses d'ail",
        "1 bouquet de persil plat",
        "1 bouquet de coriandre",
        "1 c. à café de cumin moulu",
        "1 c. à café de coriandre moulue",
        "1/2 c. à café de bicarbonate de soude",
        "1 c. à soupe de farine (si besoin)",
        "Sel, poivre, huile d'olive extra vierge pour badigeonner",
    ],
    steps=[
        "<strong>Tremper.</strong> La veille, couvrez largement les pois chiches secs d'eau froide et laissez tremper 12 h. Égouttez : ils ne seront pas cuits, c'est normal.",
        "<strong>Mixer.</strong> Mixez les pois chiches avec l'oignon, l'ail, le persil, la coriandre, le cumin, la coriandre moulue, le sel et le poivre. Visez une texture sableuse et homogène, qui se tient quand on la presse — sans réduire en purée lisse.",
        "<strong>Reposer.</strong> Ajoutez le bicarbonate (et la farine si la pâte colle trop), mélangez et laissez reposer 30 min au frais.",
        "<strong>Façonner.</strong> Formez des boulettes ou de petits palets d'environ 4 cm. Posez-les sur une plaque avec papier cuisson.",
        "<strong>Cuire au four.</strong> Badigeonnez généreusement d'huile d'olive. Enfournez à 200 °C (chaleur tournante) 25 à 30 min, en retournant à mi-cuisson, jusqu'à ce qu'ils soient bien dorés.",
        "<strong>Servir.</strong> Servez chaud avec une sauce tahini, du pain pita, des crudités et un filet d'huile d'olive.",
    ],
    oil="Au four, l'huile d'olive remplace le bain de friture : elle dore la surface et apporte du moelleux. Badigeonnez les falafels avant et, si besoin, à mi-cuisson. Une <strong>extra vierge fruitée</strong> renforce le goût sans alourdir. Un filet à cru sur l'assiette réveille l'ensemble.",
    tips=[
        "Pois chiches SECS trempés, jamais en conserve : c'est la règle anti-émiettement.",
        "Ne mixez pas en purée lisse : une texture granuleuse tient mieux.",
        "Laissez reposer la pâte 30 min avant de façonner.",
        "Badigeonnez bien d'huile d'olive pour une croûte dorée au four.",
    ],
    variations=[
        "<strong>À la poêle :</strong> dorez les palets dans un peu d'huile d'olive, 3-4 min par face.",
        "<strong>Version verte :</strong> plus d'herbes pour des falafels bien verts à l'intérieur.",
        "<strong>Épicée :</strong> une pointe de piment ou de harissa dans la pâte.",
    ],
    serve="Servez les falafels en sandwich pita avec sauce tahini, tomate, concombre et salade, en mezze avec houmous et légumes grillés, ou en bowl avec céréales et crudités. Un filet d'huile d'olive et un peu de citron au moment de servir font la différence.",
    store="Ils se gardent 3 jours au réfrigérateur et se réchauffent au four pour retrouver leur croustillant. La pâte crue et les falafels cuits se congèlent très bien : réchauffez directement au four.",
    faqs=[
        ("Peut-on faire des falafels avec des pois chiches en conserve ?",
         "Ce n'est pas conseillé : les pois chiches en conserve sont déjà cuits et donnent une pâte humide qui s'émiette à la cuisson. Utilisez des pois chiches secs trempés 12 h et non cuits."),
        ("Comment éviter que les falafels s'émiettent ?",
         "Utilisez des pois chiches secs trempés, ne mixez pas en purée trop lisse, laissez reposer la pâte, et ajoutez un peu de farine si elle est trop humide. Le bicarbonate aide aussi à la tenue."),
        ("Falafels au four ou frits ?",
         "Frits, ils sont plus croustillants ; au four, plus légers et sans bain d'huile. Badigeonnés d'huile d'olive et cuits à 200 °C, les falafels au four dorent très bien."),
        ("Combien de temps cuire les falafels au four ?",
         "Environ 25 à 30 minutes à 200 °C (chaleur tournante), en les retournant à mi-cuisson, jusqu'à ce qu'ils soient dorés."),
        ("Quelle sauce avec les falafels ?",
         "La sauce tahini (crème de sésame, citron, ail, eau) est le classique. Un yaourt à l'ail et à la menthe ou une sauce à l'huile d'olive et au citron conviennent aussi."),
    ],
    schema_name="Falafels au four à l'huile d'olive",
    schema_desc="Vrais falafels au four : pois chiches secs trempés, herbes, épices et huile d'olive, croustillants dehors et moelleux dedans.",
    schema_ing=["250 g pois chiches secs trempés", "1 oignon", "3 gousses d'ail", "persil plat", "coriandre",
                "1 c. à café cumin", "1 c. à café coriandre moulue", "1/2 c. à café bicarbonate", "farine", "huile d'olive extra vierge"],
    schema_steps=[
        "Tremper les pois chiches secs 12 h et égoutter (non cuits).",
        "Mixer avec oignon, ail, herbes et épices en texture granuleuse.",
        "Ajouter le bicarbonate et laisser reposer 30 min.",
        "Former des boulettes.",
        "Badigeonner d'huile d'olive et cuire 25-30 min à 200 °C en retournant.",
        "Servir avec sauce tahini et pita."],
    keywords="falafel au four, falafels four, recette falafel, falafel pois chiches, falafel huile d'olive",
    cuisine="Middle Eastern", category="Plat", prep="PT20M", cook="PT30M", total="PT50M", yield_="4 servings",
    nutrition={"servingSize": "1 portion", "calories": "290 kcal", "fatContent": "12 g", "proteinContent": "13 g", "carbohydrateContent": "34 g"},
)
C["en"] = dict(
    title="Baked Falafel: crispy, healthy recipe with olive oil",
    desc="Real baked falafel, crisp outside and fluffy inside: soaked dried chickpeas, herbs, spices and olive oil. The anti-crumble trick, tahini sauce and baking time.",
    h1="Baked Falafel with olive oil",
    lede="Golden oven-baked falafel, lighter than fried but just as tasty. The secret is one detail: soaked dried chickpeas (never canned), blended raw with herbs and spices, then roasted with olive oil.",
    info="<strong>Prep:</strong> 20 min (+12 h soaking) · <strong>Cook:</strong> 30 min · <strong>Serves:</strong> 4 · <strong>Cuisine:</strong> Middle Eastern · <strong>Difficulty:</strong> easy",
    intro="Good falafel is not about frying but about the base: dried chickpeas, soaked then blended raw. Canned (already cooked) chickpeas make a wet paste that falls apart. Baked with a good drizzle of olive oil, you get a golden crust and a soft centre, with no deep-frying.",
    ingredients=[
        "250 g dried chickpeas (soaked 12 h, uncooked)",
        "1 onion",
        "3 garlic cloves",
        "1 bunch flat-leaf parsley",
        "1 bunch cilantro (coriander)",
        "1 tsp ground cumin",
        "1 tsp ground coriander",
        "1/2 tsp baking soda",
        "1 tbsp flour (if needed)",
        "Salt, pepper, extra virgin olive oil for brushing",
    ],
    steps=[
        "<strong>Soak.</strong> The night before, cover the dried chickpeas generously with cold water and soak 12 h. Drain: they will be raw, that's normal.",
        "<strong>Blend.</strong> Blend the chickpeas with onion, garlic, parsley, cilantro, cumin, ground coriander, salt and pepper. Aim for a sandy, even texture that holds when pressed — not a smooth purée.",
        "<strong>Rest.</strong> Add the baking soda (and flour if too sticky), mix and rest 30 min in the fridge.",
        "<strong>Shape.</strong> Form balls or small patties about 4 cm. Place on a lined baking tray.",
        "<strong>Bake.</strong> Brush generously with olive oil. Bake at 200 °C (fan) for 25–30 min, turning halfway, until well browned.",
        "<strong>Serve.</strong> Serve hot with tahini sauce, pita bread, crudités and a drizzle of olive oil.",
    ],
    oil="In the oven, olive oil replaces the fryer: it browns the surface and adds moisture. Brush the falafel before and, if needed, halfway. A <strong>fruity extra virgin</strong> boosts flavour without weighing it down. A raw drizzle on the plate lifts everything.",
    tips=[
        "DRIED soaked chickpeas, never canned: the anti-crumble rule.",
        "Don't blend to a smooth purée: a grainy texture holds better.",
        "Rest the mixture 30 min before shaping.",
        "Brush well with olive oil for a golden oven crust.",
    ],
    variations=[
        "<strong>Pan-fried:</strong> brown the patties in a little olive oil, 3–4 min per side.",
        "<strong>Green version:</strong> more herbs for a bright green inside.",
        "<strong>Spicy:</strong> a touch of chili or harissa in the mix.",
    ],
    serve="Serve falafel in a pita with tahini sauce, tomato, cucumber and salad, as a mezze with hummus and grilled vegetables, or in a bowl with grains and crudités. A drizzle of olive oil and a squeeze of lemon at serving make the difference.",
    store="They keep 3 days in the fridge and reheat in the oven to regain their crunch. Both the raw mix and cooked falafel freeze very well: reheat straight from the oven.",
    faqs=[
        ("Can you make falafel with canned chickpeas?",
         "Not recommended: canned chickpeas are already cooked and give a wet paste that crumbles when cooked. Use dried chickpeas soaked 12 h and uncooked."),
        ("How do I stop falafel falling apart?",
         "Use soaked dried chickpeas, don't blend to a smooth purée, rest the mix, and add a little flour if too wet. Baking soda also helps them hold."),
        ("Baked or fried falafel?",
         "Fried is crunchier; baked is lighter with no oil bath. Brushed with olive oil and baked at 200 °C, oven falafel browns very nicely."),
        ("How long do you bake falafel?",
         "About 25–30 minutes at 200 °C (fan), turning halfway, until golden brown."),
        ("What sauce goes with falafel?",
         "Tahini sauce (sesame paste, lemon, garlic, water) is the classic. Garlic-mint yogurt or an olive-oil-and-lemon dressing also work well."),
    ],
    schema_name="Baked Falafel with olive oil",
    schema_desc="Real baked falafel: soaked dried chickpeas, herbs, spices and olive oil, crisp outside and fluffy inside.",
    schema_ing=["250 g dried chickpeas soaked", "1 onion", "3 garlic cloves", "flat-leaf parsley", "cilantro",
                "1 tsp cumin", "1 tsp ground coriander", "1/2 tsp baking soda", "flour", "extra virgin olive oil"],
    schema_steps=[
        "Soak dried chickpeas 12 h and drain (uncooked).",
        "Blend with onion, garlic, herbs and spices to a grainy texture.",
        "Add baking soda and rest 30 min.",
        "Form balls.",
        "Brush with olive oil and bake 25-30 min at 200 °C, turning.",
        "Serve with tahini sauce and pita."],
    keywords="baked falafel, oven falafel, falafel recipe, chickpea falafel, falafel olive oil",
    cuisine="Middle Eastern", category="Main", prep="PT20M", cook="PT30M", total="PT50M", yield_="4 servings",
    nutrition={"servingSize": "1 serving", "calories": "290 kcal", "fatContent": "12 g", "proteinContent": "13 g", "carbohydrateContent": "34 g"},
)
C["it"] = dict(
    title="Falafel al forno: ricetta croccante e leggera all'olio d'oliva",
    desc="Veri falafel al forno, croccanti fuori e morbidi dentro: ceci secchi ammollati, erbe, spezie e olio d'oliva. Il trucco anti-sbriciolamento, la salsa tahini e i tempi.",
    h1="Falafel al forno all'olio d'oliva",
    lede="Falafel dorati al forno, più leggeri dei fritti ma altrettanto saporiti. Il segreto è un dettaglio: ceci secchi ammollati (mai in scatola), frullati crudi con erbe e spezie, poi arrostiti con olio d'oliva.",
    info="<strong>Preparazione:</strong> 20 min (+12 h ammollo) · <strong>Cottura:</strong> 30 min · <strong>Per:</strong> 4 persone · <strong>Cucina:</strong> mediorientale · <strong>Difficoltà:</strong> facile",
    intro="Un buon falafel non dipende dalla frittura ma dalla base: ceci secchi, ammollati e frullati crudi. I ceci in scatola (già cotti) danno un impasto umido che si sbriciola. Al forno, con un buon filo d'olio, si ottiene una crosticina dorata e un cuore morbido, senza friggere.",
    ingredients=[
        "250 g di ceci secchi (ammollati 12 h, crudi)",
        "1 cipolla",
        "3 spicchi d'aglio",
        "1 ciuffo di prezzemolo",
        "1 ciuffo di coriandolo",
        "1 cucchiaino di cumino",
        "1 cucchiaino di coriandolo macinato",
        "1/2 cucchiaino di bicarbonato",
        "1 cucchiaio di farina (se serve)",
        "Sale, pepe, olio extravergine d'oliva per spennellare",
    ],
    steps=[
        "<strong>Ammollare.</strong> La sera prima copri i ceci secchi con acqua fredda e lasciali 12 h. Scola: resteranno crudi, è normale.",
        "<strong>Frullare.</strong> Frulla i ceci con cipolla, aglio, prezzemolo, coriandolo, cumino, coriandolo macinato, sale e pepe. Punta a una consistenza sabbiosa che tiene se pressata — non una purea liscia.",
        "<strong>Riposare.</strong> Aggiungi il bicarbonato (e la farina se appiccica troppo), mescola e lascia riposare 30 min in frigo.",
        "<strong>Formare.</strong> Forma polpette o dischetti di circa 4 cm su una teglia con carta forno.",
        "<strong>Cuocere.</strong> Spennella bene d'olio d'oliva. Inforna a 200 °C (ventilato) per 25–30 min, girando a metà, fino a doratura.",
        "<strong>Servire.</strong> Servi caldi con salsa tahini, pane pita, verdure crude e un filo d'olio.",
    ],
    oil="Al forno l'olio d'oliva sostituisce la frittura: dora la superficie e dà morbidezza. Spennella prima e, se serve, a metà cottura. Un <strong>extravergine fruttato</strong> esalta il gusto senza appesantire. Un filo a crudo nel piatto ravviva tutto.",
    tips=[
        "Ceci SECCHI ammollati, mai in scatola: regola anti-sbriciolamento.",
        "Non frullare a purea liscia: la consistenza granulosa tiene meglio.",
        "Lascia riposare l'impasto 30 min prima di formare.",
        "Spennella bene d'olio per una crosta dorata al forno.",
    ],
    variations=[
        "<strong>In padella:</strong> rosola i dischetti in poco olio, 3–4 min per lato.",
        "<strong>Verdi:</strong> più erbe per un interno ben verde.",
        "<strong>Piccanti:</strong> una punta di peperoncino o harissa nell'impasto.",
    ],
    serve="Servi i falafel nel pita con salsa tahini, pomodoro, cetriolo e insalata, come mezze con hummus e verdure grigliate, o in una bowl con cereali e crudità. Un filo d'olio e una spruzzata di limone fanno la differenza.",
    store="Si conservano 3 giorni in frigo e si scaldano al forno per tornare croccanti. Sia l'impasto crudo sia i falafel cotti si congelano bene: riscalda direttamente in forno.",
    faqs=[
        ("Si possono fare i falafel con i ceci in scatola?",
         "Sconsigliato: i ceci in scatola sono già cotti e danno un impasto umido che si sbriciola. Usa ceci secchi ammollati 12 h e crudi."),
        ("Come evitare che i falafel si sbriciolino?",
         "Usa ceci secchi ammollati, non frullare a purea liscia, fai riposare l'impasto e aggiungi un po' di farina se troppo umido. Anche il bicarbonato aiuta."),
        ("Falafel al forno o fritti?",
         "Fritti sono più croccanti; al forno più leggeri e senza olio di frittura. Spennellati d'olio e cotti a 200 °C, i falafel al forno dorano molto bene."),
        ("Quanto cuocere i falafel al forno?",
         "Circa 25–30 minuti a 200 °C (ventilato), girando a metà, fino a doratura."),
        ("Quale salsa con i falafel?",
         "La salsa tahini (crema di sesamo, limone, aglio, acqua) è la classica. Vanno bene anche uno yogurt all'aglio e menta o una salsa olio-limone."),
    ],
    schema_name="Falafel al forno all'olio d'oliva",
    schema_desc="Veri falafel al forno: ceci secchi ammollati, erbe, spezie e olio d'oliva, croccanti fuori e morbidi dentro.",
    schema_ing=["250 g ceci secchi ammollati", "1 cipolla", "3 spicchi d'aglio", "prezzemolo", "coriandolo",
                "1 cucchiaino cumino", "1 cucchiaino coriandolo macinato", "1/2 cucchiaino bicarbonato", "farina", "olio extravergine d'oliva"],
    schema_steps=[
        "Ammollare i ceci secchi 12 h e scolare (crudi).",
        "Frullare con cipolla, aglio, erbe e spezie a consistenza granulosa.",
        "Aggiungere bicarbonato e riposare 30 min.",
        "Formare polpette.",
        "Spennellare d'olio e cuocere 25-30 min a 200 °C girando.",
        "Servire con salsa tahini e pita."],
    keywords="falafel al forno, falafel forno, ricetta falafel, falafel ceci, falafel olio d'oliva",
    cuisine="Middle Eastern", category="Piatto", prep="PT20M", cook="PT30M", total="PT50M", yield_="4 porzioni",
    nutrition={"servingSize": "1 porzione", "calories": "290 kcal", "fatContent": "12 g", "proteinContent": "13 g", "carbohydrateContent": "34 g"},
)
C["el"] = dict(
    title="Φαλάφελ στον φούρνο: τραγανή, ελαφριά συνταγή με ελαιόλαδο",
    desc="Αληθινά φαλάφελ φούρνου, τραγανά έξω και αφράτα μέσα: ξερά ρεβίθια μουλιασμένα, μυρωδικά, μπαχαρικά και ελαιόλαδο. Το κόλπο για να μη διαλύονται, σάλτσα ταχίνι και χρόνοι.",
    h1="Φαλάφελ στον φούρνο με ελαιόλαδο",
    lede="Χρυσαφένια φαλάφελ στον φούρνο, πιο ελαφριά από τα τηγανητά αλλά εξίσου νόστιμα. Το μυστικό είναι μια λεπτομέρεια: ξερά ρεβίθια μουλιασμένα (ποτέ κονσέρβα), χτυπημένα ωμά με μυρωδικά και μπαχαρικά, μετά ψημένα με ελαιόλαδο.",
    info="<strong>Προετοιμασία:</strong> 20 λεπτά (+12 ώρες μούλιασμα) · <strong>Ψήσιμο:</strong> 30 λεπτά · <strong>Μερίδες:</strong> 4 · <strong>Κουζίνα:</strong> μεσανατολική · <strong>Δυσκολία:</strong> εύκολη",
    intro="Τα καλά φαλάφελ δεν εξαρτώνται από το τηγάνισμα αλλά από τη βάση: ξερά ρεβίθια, μουλιασμένα και χτυπημένα ωμά. Τα ρεβίθια κονσέρβας (ήδη μαγειρεμένα) δίνουν υγρό μείγμα που διαλύεται. Στον φούρνο, με καλό ελαιόλαδο, βγαίνει χρυσή κρούστα και αφράτο εσωτερικό, χωρίς τηγάνισμα.",
    ingredients=[
        "250 g ξερά ρεβίθια (μουλιασμένα 12 ώρες, ωμά)",
        "1 κρεμμύδι",
        "3 σκελίδες σκόρδο",
        "1 ματσάκι μαϊντανός",
        "1 ματσάκι κόλιανδρος",
        "1 κ.γ. κύμινο",
        "1 κ.γ. κόλιανδρο τριμμένο",
        "1/2 κ.γ. μαγειρική σόδα",
        "1 κ.σ. αλεύρι (αν χρειάζεται)",
        "Αλάτι, πιπέρι, έξτρα παρθένο ελαιόλαδο για άλειμμα",
    ],
    steps=[
        "<strong>Μούλιασμα.</strong> Από το βράδυ σκεπάστε τα ξερά ρεβίθια με κρύο νερό για 12 ώρες. Στραγγίστε: θα είναι ωμά, φυσιολογικό.",
        "<strong>Χτύπημα.</strong> Χτυπήστε τα ρεβίθια με κρεμμύδι, σκόρδο, μαϊντανό, κόλιανδρο, κύμινο, κόλιανδρο τριμμένο, αλάτι και πιπέρι. Στοχεύστε σε υφή σαν άμμος που κρατά όταν πιεστεί — όχι λεία πουρέ.",
        "<strong>Ξεκούραση.</strong> Προσθέστε τη σόδα (και αλεύρι αν κολλά πολύ), ανακατέψτε και αφήστε 30 λεπτά στο ψυγείο.",
        "<strong>Πλάσιμο.</strong> Πλάστε μπαλάκια ή μικρά πιτάκια ~4 εκ. σε ταψί με λαδόκολλα.",
        "<strong>Ψήσιμο.</strong> Αλείψτε γενναιόδωρα με ελαιόλαδο. Ψήστε στους 200 °C (αέρα) 25–30 λεπτά, γυρίζοντας στη μέση, μέχρι να ροδίσουν.",
        "<strong>Σερβίρισμα.</strong> Σερβίρετε ζεστά με σάλτσα ταχίνι, πίτα, ωμά λαχανικά και λίγο ελαιόλαδο.",
    ],
    oil="Στον φούρνο το ελαιόλαδο αντικαθιστά το τηγάνισμα: ροδίζει την επιφάνεια και δίνει υγρασία. Αλείψτε πριν και, αν χρειαστεί, στη μέση. Ένα <strong>φρουτώδες έξτρα παρθένο</strong> ενισχύει τη γεύση χωρίς να βαραίνει.",
    tips=[
        "ΞΕΡΑ μουλιασμένα ρεβίθια, ποτέ κονσέρβα: ο κανόνας για να μη διαλύονται.",
        "Μη χτυπάτε σε λεία πουρέ: η κοκκώδης υφή κρατά καλύτερα.",
        "Αφήστε το μείγμα 30 λεπτά πριν το πλάσιμο.",
        "Αλείψτε καλά με ελαιόλαδο για χρυσή κρούστα.",
    ],
    variations=[
        "<strong>Στο τηγάνι:</strong> ροδίστε τα πιτάκια σε λίγο ελαιόλαδο, 3–4 λεπτά ανά πλευρά.",
        "<strong>Πράσινα:</strong> περισσότερα μυρωδικά για έντονο πράσινο εσωτερικό.",
        "<strong>Πικάντικα:</strong> λίγη καυτερή ή harissa στο μείγμα.",
    ],
    serve="Σερβίρετε τα φαλάφελ σε πίτα με ταχίνι, ντομάτα, αγγούρι και σαλάτα, ως μεζέ με χούμους και ψητά λαχανικά, ή σε bowl με δημητριακά. Λίγο ελαιόλαδο και λεμόνι στο σερβίρισμα κάνουν τη διαφορά.",
    store="Διατηρούνται 3 ημέρες στο ψυγείο και ζεσταίνονται στον φούρνο για να ξανατραγανίσουν. Και το ωμό μείγμα και τα ψημένα φαλάφελ καταψύχονται καλά.",
    faqs=[
        ("Γίνονται φαλάφελ με ρεβίθια κονσέρβας;",
         "Δεν συνιστάται: τα ρεβίθια κονσέρβας είναι ήδη μαγειρεμένα και δίνουν υγρό μείγμα που διαλύεται. Χρησιμοποιήστε ξερά ρεβίθια μουλιασμένα 12 ώρες, ωμά."),
        ("Πώς να μη διαλύονται τα φαλάφελ;",
         "Χρησιμοποιήστε ξερά μουλιασμένα ρεβίθια, μη χτυπάτε σε λεία πουρέ, αφήστε το μείγμα να ξεκουραστεί και προσθέστε λίγο αλεύρι αν είναι υγρό. Η σόδα βοηθά επίσης."),
        ("Φαλάφελ φούρνου ή τηγανητά;",
         "Τα τηγανητά είναι πιο τραγανά· του φούρνου πιο ελαφριά, χωρίς λάδι τηγανίσματος. Αλειμμένα με ελαιόλαδο στους 200 °C ροδίζουν πολύ ωραία."),
        ("Πόση ώρα ψήνονται;",
         "Περίπου 25–30 λεπτά στους 200 °C (αέρα), γυρίζοντας στη μέση, μέχρι να ροδίσουν."),
        ("Ποια σάλτσα με τα φαλάφελ;",
         "Η σάλτσα ταχίνι (ταχίνι, λεμόνι, σκόρδο, νερό) είναι η κλασική. Ταιριάζει και γιαούρτι με σκόρδο-δυόσμο ή σάλτσα ελαιόλαδου-λεμονιού."),
    ],
    schema_name="Φαλάφελ στον φούρνο με ελαιόλαδο",
    schema_desc="Αληθινά φαλάφελ φούρνου: ξερά ρεβίθια μουλιασμένα, μυρωδικά, μπαχαρικά και ελαιόλαδο, τραγανά έξω και αφράτα μέσα.",
    schema_ing=["250 g ξερά ρεβίθια μουλιασμένα", "1 κρεμμύδι", "3 σκελίδες σκόρδο", "μαϊντανός", "κόλιανδρος",
                "1 κ.γ. κύμινο", "1 κ.γ. κόλιανδρο", "1/2 κ.γ. σόδα", "αλεύρι", "έξτρα παρθένο ελαιόλαδο"],
    schema_steps=[
        "Μουλιάστε τα ξερά ρεβίθια 12 ώρες και στραγγίστε (ωμά).",
        "Χτυπήστε με κρεμμύδι, σκόρδο, μυρωδικά και μπαχαρικά σε κοκκώδη υφή.",
        "Προσθέστε σόδα και αφήστε 30 λεπτά.",
        "Πλάστε μπαλάκια.",
        "Αλείψτε με ελαιόλαδο και ψήστε 25-30 λεπτά στους 200 °C γυρίζοντας.",
        "Σερβίρετε με ταχίνι και πίτα."],
    keywords="φαλάφελ φούρνου, φαλάφελ στον φούρνο, συνταγή φαλάφελ, φαλάφελ ρεβίθια, φαλάφελ ελαιόλαδο",
    cuisine="Middle Eastern", category="Πιάτο", prep="PT20M", cook="PT30M", total="PT50M", yield_="4 μερίδες",
    nutrition={"servingSize": "1 μερίδα", "calories": "290 kcal", "fatContent": "12 g", "proteinContent": "13 g", "carbohydrateContent": "34 g"},
)

if __name__ == "__main__":
    write_cluster("falafels-four-huile-olive", C)
