# -*- coding: utf-8 -*-
"""Batch 1 authentic recipe rewrites: pesto alla genovese, carpaccio de boeuf,
salade de poulpe. Real ingredients, real technique, long-tail FAQ. x4 languages."""

from recipe_render import write_cluster

# ============================================================ PESTO GENOVESE ==
PESTO = {}
PESTO["fr"] = dict(
    title="Pesto alla Genovese : la vraie recette maison au mortier (huile d'olive)",
    desc="La vraie recette du pesto alla genovese : basilic, pignons, ail, parmesan, pecorino et huile d'olive extra vierge, au mortier. Méthode traditionnelle, astuce mixeur anti-oxydation et pâtes idéales.",
    h1="Pesto alla Genovese maison",
    lede="Le vrai pesto génois se fait à froid, au mortier de marbre : basilic, pignons, ail, parmesan, pecorino et une huile d'olive extra vierge douce. Voici la méthode traditionnelle, l'astuce pour un pesto qui reste vert et les pâtes qui lui vont le mieux.",
    info="<strong>Préparation :</strong> 15 min · <strong>Cuisson :</strong> 0 min · <strong>Pour :</strong> 4 personnes (400 g de pâtes) · <strong>Cuisine :</strong> italienne (Ligurie) · <strong>Difficulté :</strong> facile",
    intro="Le <em>pesto alla genovese</em> ne se cuit jamais et ne se mixe pas à chaud : c'est une émulsion crue où l'huile d'olive lie le basilic, les fruits secs et le fromage. Fait dans les règles, il reste vert vif et parfumé. La clé : des ingrédients de qualité, un basilic jeune et une huile d'olive douce qui ne domine pas.",
    ingredients=[
        "50 g de feuilles de basilic frais (petites feuilles, type Gênes)",
        "15 g de pignons de pin",
        "1 petite gousse d'ail (dégermée)",
        "30 g de Parmigiano Reggiano fraîchement râpé",
        "20 g de Pecorino (Fiore Sardo) râpé",
        "70 à 100 ml d'huile d'olive extra vierge douce (ligurienne de préférence)",
        "Gros sel",
    ],
    steps=[
        "<strong>Piler l'ail.</strong> Dans un mortier de marbre, écrasez l'ail avec quelques grains de gros sel jusqu'à obtenir une pâte.",
        "<strong>Ajouter les pignons.</strong> Incorporez les pignons et écrasez-les en pâte crémeuse.",
        "<strong>Le basilic.</strong> Ajoutez les feuilles de basilic (lavées et bien séchées) par petites poignées, en écrasant avec un mouvement rotatif contre les parois du mortier — sans frapper. Le basilic doit rendre un liquide vert vif.",
        "<strong>Les fromages.</strong> Incorporez le parmesan et le pecorino, mélangez en une crème.",
        "<strong>L'huile d'olive.</strong> Versez l'huile d'olive extra vierge en filet en tournant, jusqu'à une sauce lisse et brillante. Goûtez, rectifiez le sel.",
        "<strong>Servir.</strong> Détendez le pesto avec une cuillère d'eau de cuisson des pâtes, hors du feu. Ne le faites jamais bouillir.",
    ],
    oven="<strong>Version au mixeur (sans oxydation) :</strong> mettez le bol et les lames au congélateur 10 minutes. Mixez par à-coups très courts pour ne pas chauffer (la chaleur des lames noircit le basilic). Pour un vert durable, blanchissez le basilic 5 secondes puis plongez-le dans l'eau glacée avant de mixer. Terminez l'huile à la main.",
    oil="L'huile d'olive n'est pas qu'un liant : c'est elle qui porte le parfum du basilic et arrondit l'ail. Choisissez une <strong>extra vierge douce et fruitée</strong> (les huiles très amères et poivrées écrasent le basilic). Une huile ligurienne délicate est l'accord classique.",
    tips=[
        "Basilic jeune et sec : l'eau dilue et oxyde le pesto.",
        "Travaillez à froid, jamais au chaud : un pesto cuit devient gris et amer.",
        "Huile douce, pas robuste, pour laisser parler le basilic.",
        "Assaisonnez les pâtes hors du feu avec un peu d'eau de cuisson.",
        "Pour trofie, trenette ou gnocchi : ajoutez pommes de terre et haricots verts, à la génoise.",
    ],
    variations=[
        "<strong>Sans fruits à coque :</strong> remplacez les pignons par un peu plus d'huile (texture différente).",
        "<strong>Pesto de conservation :</strong> sans fromage (à ajouter au moment de servir), il se garde et se congèle mieux.",
    ],
    serve="Le pesto se sert cru sur des pâtes chaudes (trofie, trenette, linguine) détendu à l'eau de cuisson, sur des gnocchi, dans une soupe minestrone hors du feu, ou en tartine. Ne le cuisez jamais : la chaleur détruit le parfum et la couleur.",
    store="Au réfrigérateur 3 à 4 jours dans un bocal, recouvert d'une fine couche d'huile d'olive pour l'isoler de l'air. Se congèle bien, de préférence sans le fromage (à incorporer au moment de servir).",
    faqs=[
        ("Quels sont les vrais ingrédients du pesto alla genovese ?",
         "Basilic (idéalement de Gênes), pignons de pin, ail, Parmigiano Reggiano, Pecorino, huile d'olive extra vierge et gros sel. Rien d'autre : ni crème, ni noix de cajou, ni citron dans la recette traditionnelle."),
        ("Mortier ou mixeur pour le pesto ?",
         "Le mortier de marbre donne le meilleur résultat car il écrase sans chauffer. Le mixeur fonctionne si vous refroidissez le bol et mixez par à-coups très courts pour éviter que la chaleur des lames n'oxyde le basilic."),
        ("Pourquoi mon pesto devient-il gris ?",
         "À cause de l'oxydation : basilic mouillé, chaleur des lames ou exposition à l'air. Séchez bien le basilic, travaillez à froid, et couvrez le pesto d'huile d'olive. Blanchir le basilic 5 secondes fixe la couleur."),
        ("Quelles pâtes avec le pesto ?",
         "Les trofie et trenette (ou linguine) liguriennes, souvent avec des pommes de terre et des haricots verts cuits dans la même eau. Les gnocchi conviennent aussi très bien."),
        ("Peut-on congeler le pesto ?",
         "Oui, de préférence sans le fromage, dans un bac à glaçons ou un bocal couvert d'huile. Ajoutez le parmesan et le pecorino au moment de servir."),
    ],
    schema_name="Pesto alla Genovese maison",
    schema_desc="La vraie recette du pesto alla genovese au mortier : basilic, pignons, ail, parmesan, pecorino et huile d'olive extra vierge.",
    schema_ing=["50 g basilic frais", "15 g pignons de pin", "1 gousse d'ail",
                "30 g Parmigiano Reggiano", "20 g Pecorino", "70-100 ml huile d'olive extra vierge", "gros sel"],
    schema_steps=[
        "Piler l'ail avec du gros sel en pâte.", "Ajouter les pignons et écraser.",
        "Incorporer le basilic par poignées en écrasant contre les parois.",
        "Ajouter parmesan et pecorino.", "Verser l'huile d'olive en filet jusqu'à une sauce lisse.",
        "Détendre à l'eau de cuisson hors du feu, sans cuire."],
    keywords="pesto alla genovese, recette pesto genovese, pesto maison, pesto au mortier, pesto basilic huile d'olive",
    cuisine="Italian", category="Sauce", prep="PT15M", cook="PT0M", total="PT15M", yield_="4 servings",
    nutrition={"servingSize": "1 portion", "calories": "230 kcal", "fatContent": "23 g", "proteinContent": "5 g", "carbohydrateContent": "2 g"},
)
PESTO["en"] = dict(
    title="Pesto alla Genovese: the real homemade recipe (mortar & olive oil)",
    desc="The authentic pesto alla genovese: basil, pine nuts, garlic, Parmesan, Pecorino and extra virgin olive oil, made in a mortar. Traditional method, a blender trick to keep it green, and the best pasta pairings.",
    h1="Homemade Pesto alla Genovese",
    lede="Real Genoese pesto is made cold in a marble mortar: basil, pine nuts, garlic, Parmesan, Pecorino and a mild extra virgin olive oil. Here is the traditional method, the trick that keeps it bright green, and the pasta it loves.",
    info="<strong>Prep:</strong> 15 min · <strong>Cook:</strong> 0 min · <strong>Serves:</strong> 4 (400 g pasta) · <strong>Cuisine:</strong> Italian (Liguria) · <strong>Difficulty:</strong> easy",
    intro="<em>Pesto alla genovese</em> is never cooked and never blended hot: it is a raw emulsion in which olive oil binds basil, nuts and cheese. Made properly, it stays vivid green and fragrant. The keys: quality ingredients, young basil, and a mild olive oil that does not overpower.",
    ingredients=[
        "50 g fresh basil leaves (small, Genoese type)",
        "15 g pine nuts",
        "1 small garlic clove (germ removed)",
        "30 g freshly grated Parmigiano Reggiano",
        "20 g grated Pecorino (Fiore Sardo)",
        "70–100 ml mild extra virgin olive oil (ideally Ligurian)",
        "Coarse salt",
    ],
    steps=[
        "<strong>Pound the garlic.</strong> In a marble mortar, crush the garlic with a few grains of coarse salt into a paste.",
        "<strong>Add the pine nuts.</strong> Work them in until creamy.",
        "<strong>Basil.</strong> Add the washed, well-dried basil in small handfuls, crushing with a rotating motion against the sides of the mortar — never pounding. The basil should release a bright green liquid.",
        "<strong>Cheeses.</strong> Work in the Parmesan and Pecorino to a cream.",
        "<strong>Olive oil.</strong> Pour in the extra virgin olive oil in a thin stream, stirring, to a smooth, glossy sauce. Taste and adjust salt.",
        "<strong>Serve.</strong> Loosen with a spoon of pasta cooking water, off the heat. Never boil it.",
    ],
    oven="<strong>Blender version (no oxidation):</strong> chill the bowl and blades 10 minutes. Pulse in very short bursts so the blades don't heat up (heat blackens basil). For lasting green, blanch the basil 5 seconds then shock in ice water before blending. Finish the oil by hand.",
    oil="Olive oil is more than a binder: it carries the basil aroma and rounds the garlic. Choose a <strong>mild, fruity extra virgin</strong> (very bitter, peppery oils crush the basil). A delicate Ligurian oil is the classic match.",
    tips=[
        "Young, dry basil: water dilutes and oxidises pesto.",
        "Work cold, never hot: cooked pesto turns grey and bitter.",
        "Mild oil, not robust, to let the basil speak.",
        "Dress pasta off the heat with a little cooking water.",
        "For trofie, trenette or gnocchi: add potatoes and green beans, Genoa-style.",
    ],
    variations=[
        "<strong>Nut-free:</strong> replace pine nuts with a little more oil (different texture).",
        "<strong>Keeping pesto:</strong> without cheese (add when serving) it stores and freezes better.",
    ],
    serve="Serve pesto raw over hot pasta (trofie, trenette, linguine) loosened with cooking water, over gnocchi, stirred into minestrone off the heat, or on toast. Never cook it: heat destroys the aroma and colour.",
    store="In the fridge 3–4 days in a jar, topped with a thin layer of olive oil to seal it from air. It freezes well, ideally without the cheese (add when serving).",
    faqs=[
        ("What are the real ingredients of pesto alla genovese?",
         "Basil (ideally Genoese), pine nuts, garlic, Parmigiano Reggiano, Pecorino, extra virgin olive oil and coarse salt. Nothing else: no cream, no cashews, no lemon in the traditional recipe."),
        ("Mortar or blender for pesto?",
         "A marble mortar gives the best result because it crushes without heating. A blender works if you chill the bowl and pulse in very short bursts so blade heat doesn't oxidise the basil."),
        ("Why does my pesto turn grey?",
         "Oxidation: wet basil, blade heat or air exposure. Dry the basil well, work cold, and cover the pesto with olive oil. Blanching the basil for 5 seconds fixes the colour."),
        ("Which pasta with pesto?",
         "Ligurian trofie and trenette (or linguine), often with potatoes and green beans cooked in the same water. Gnocchi work very well too."),
        ("Can you freeze pesto?",
         "Yes, ideally without the cheese, in an ice-cube tray or a jar topped with oil. Add the Parmesan and Pecorino when serving."),
    ],
    schema_name="Homemade Pesto alla Genovese",
    schema_desc="The authentic pesto alla genovese made in a mortar: basil, pine nuts, garlic, Parmesan, Pecorino and extra virgin olive oil.",
    schema_ing=["50 g fresh basil", "15 g pine nuts", "1 garlic clove", "30 g Parmigiano Reggiano",
                "20 g Pecorino", "70-100 ml extra virgin olive oil", "coarse salt"],
    schema_steps=[
        "Pound garlic with coarse salt into a paste.", "Add pine nuts and crush.",
        "Crush basil in handfuls against the mortar sides.", "Work in Parmesan and Pecorino.",
        "Stream in olive oil to a smooth sauce.", "Loosen with pasta water off the heat; do not cook."],
    keywords="pesto alla genovese, pesto recipe, homemade pesto, mortar pesto, basil olive oil pesto",
    cuisine="Italian", category="Sauce", prep="PT15M", cook="PT0M", total="PT15M", yield_="4 servings",
    nutrition={"servingSize": "1 serving", "calories": "230 kcal", "fatContent": "23 g", "proteinContent": "5 g", "carbohydrateContent": "2 g"},
)
PESTO["it"] = dict(
    title="Pesto alla Genovese: la vera ricetta al mortaio (con olio d'oliva)",
    desc="La vera ricetta del pesto alla genovese: basilico, pinoli, aglio, parmigiano, pecorino e olio extravergine d'oliva, al mortaio. Metodo tradizionale, trucco per il frullatore e la pasta giusta.",
    h1="Pesto alla Genovese fatto in casa",
    lede="Il vero pesto genovese si fa a freddo, nel mortaio di marmo: basilico, pinoli, aglio, parmigiano, pecorino e un olio extravergine dolce. Ecco il metodo tradizionale, il trucco per tenerlo verde e la pasta ideale.",
    info="<strong>Preparazione:</strong> 15 min · <strong>Cottura:</strong> 0 min · <strong>Per:</strong> 4 persone (400 g pasta) · <strong>Cucina:</strong> italiana (Liguria) · <strong>Difficoltà:</strong> facile",
    intro="Il <em>pesto alla genovese</em> non si cuoce mai e non si frulla a caldo: è un'emulsione cruda in cui l'olio d'oliva lega basilico, frutta secca e formaggio. Fatto bene, resta verde brillante e profumato. Le chiavi: ingredienti di qualità, basilico giovane e un olio dolce che non copra.",
    ingredients=[
        "50 g di foglie di basilico fresco (piccole, genovese)",
        "15 g di pinoli",
        "1 piccolo spicchio d'aglio (senza anima)",
        "30 g di Parmigiano Reggiano grattugiato",
        "20 g di Pecorino (Fiore Sardo) grattugiato",
        "70–100 ml di olio extravergine d'oliva dolce (ligure)",
        "Sale grosso",
    ],
    steps=[
        "<strong>Pestare l'aglio.</strong> Nel mortaio di marmo, schiaccia l'aglio con qualche grano di sale grosso fino a una crema.",
        "<strong>Aggiungere i pinoli.</strong> Lavorali fino a renderli cremosi.",
        "<strong>Il basilico.</strong> Aggiungi le foglie lavate e ben asciutte a piccole manciate, schiacciando con movimento rotatorio contro le pareti — mai battendo. Il basilico deve rilasciare un liquido verde brillante.",
        "<strong>I formaggi.</strong> Incorpora parmigiano e pecorino fino a una crema.",
        "<strong>L'olio d'oliva.</strong> Versa l'extravergine a filo, mescolando, fino a una salsa liscia e lucida. Assaggia e regola il sale.",
        "<strong>Servire.</strong> Ammorbidisci con un cucchiaio di acqua di cottura, fuori dal fuoco. Non bollire mai.",
    ],
    oven="<strong>Versione al frullatore (senza ossidazione):</strong> metti bicchiere e lame in freezer 10 minuti. Frulla a impulsi brevissimi per non scaldare (il calore annerisce il basilico). Per un verde duraturo, sbollenta il basilico 5 secondi e passalo in acqua ghiacciata prima di frullare. Finisci l'olio a mano.",
    oil="L'olio d'oliva non è solo un legante: porta il profumo del basilico e arrotonda l'aglio. Scegli un <strong>extravergine dolce e fruttato</strong> (gli oli molto amari e piccanti coprono il basilico). Un olio ligure delicato è l'abbinamento classico.",
    tips=[
        "Basilico giovane e asciutto: l'acqua diluisce e ossida.",
        "Lavora a freddo, mai a caldo: il pesto cotto diventa grigio e amaro.",
        "Olio dolce, non robusto, per lasciar parlare il basilico.",
        "Condisci la pasta fuori dal fuoco con un po' d'acqua di cottura.",
        "Per trofie, trenette o gnocchi: aggiungi patate e fagiolini, alla genovese.",
    ],
    variations=[
        "<strong>Senza frutta secca:</strong> sostituisci i pinoli con un po' più d'olio.",
        "<strong>Pesto da conservare:</strong> senza formaggio (da aggiungere al momento) si conserva e congela meglio.",
    ],
    serve="Il pesto si serve crudo sulla pasta calda (trofie, trenette, linguine) ammorbidito con acqua di cottura, sugli gnocchi, nel minestrone fuori dal fuoco o su una fetta di pane. Non cuocerlo mai.",
    store="In frigorifero 3–4 giorni in un vasetto, coperto da un velo d'olio per isolarlo dall'aria. Si congela bene, meglio senza formaggio (da aggiungere al momento di servire).",
    faqs=[
        ("Quali sono i veri ingredienti del pesto alla genovese?",
         "Basilico (meglio genovese), pinoli, aglio, Parmigiano Reggiano, Pecorino, olio extravergine d'oliva e sale grosso. Nient'altro: niente panna, anacardi o limone nella ricetta tradizionale."),
        ("Mortaio o frullatore per il pesto?",
         "Il mortaio di marmo dà il risultato migliore perché schiaccia senza scaldare. Il frullatore va bene se raffreddi il bicchiere e frulli a impulsi brevissimi per evitare che il calore ossidi il basilico."),
        ("Perché il pesto diventa grigio?",
         "Per ossidazione: basilico bagnato, calore delle lame o esposizione all'aria. Asciuga bene il basilico, lavora a freddo e copri il pesto con olio. Sbollentare il basilico 5 secondi fissa il colore."),
        ("Quale pasta con il pesto?",
         "Trofie e trenette (o linguine) liguri, spesso con patate e fagiolini cotti nella stessa acqua. Anche gli gnocchi sono ottimi."),
        ("Si può congelare il pesto?",
         "Sì, meglio senza formaggio, in una vaschetta per ghiaccio o in un vasetto coperto d'olio. Aggiungi parmigiano e pecorino al momento di servire."),
    ],
    schema_name="Pesto alla Genovese fatto in casa",
    schema_desc="La vera ricetta del pesto alla genovese al mortaio: basilico, pinoli, aglio, parmigiano, pecorino e olio extravergine d'oliva.",
    schema_ing=["50 g basilico fresco", "15 g pinoli", "1 spicchio d'aglio", "30 g Parmigiano Reggiano",
                "20 g Pecorino", "70-100 ml olio extravergine d'oliva", "sale grosso"],
    schema_steps=[
        "Pestare l'aglio con sale grosso.", "Aggiungere i pinoli e schiacciare.",
        "Schiacciare il basilico contro le pareti del mortaio.", "Incorporare parmigiano e pecorino.",
        "Versare l'olio a filo fino a salsa liscia.", "Ammorbidire con acqua di cottura fuori dal fuoco."],
    keywords="pesto alla genovese, ricetta pesto genovese, pesto fatto in casa, pesto al mortaio, pesto basilico olio d'oliva",
    cuisine="Italian", category="Salsa", prep="PT15M", cook="PT0M", total="PT15M", yield_="4 porzioni",
    nutrition={"servingSize": "1 porzione", "calories": "230 kcal", "fatContent": "23 g", "proteinContent": "5 g", "carbohydrateContent": "2 g"},
)
PESTO["el"] = dict(
    title="Πέστο αλα Τζενοβέζε: η αυθεντική συνταγή στο γουδί (με ελαιόλαδο)",
    desc="Η αυθεντική συνταγή για πέστο genovese: βασιλικός, κουκουνάρι, σκόρδο, παρμεζάνα, πεκορίνο και έξτρα παρθένο ελαιόλαδο, στο γουδί. Παραδοσιακή μέθοδος, κόλπο για το μπλέντερ και η κατάλληλη πάστα.",
    h1="Πέστο αλα Τζενοβέζε σπιτικό",
    lede="Το αληθινό πέστο Γένοβας γίνεται κρύο, σε μαρμάρινο γουδί: βασιλικός, κουκουνάρι, σκόρδο, παρμεζάνα, πεκορίνο και ένα απαλό έξτρα παρθένο ελαιόλαδο. Δείτε την παραδοσιακή μέθοδο και το κόλπο για να μείνει πράσινο.",
    info="<strong>Προετοιμασία:</strong> 15 λεπτά · <strong>Μαγείρεμα:</strong> 0 λεπτά · <strong>Μερίδες:</strong> 4 (400 g πάστα) · <strong>Κουζίνα:</strong> ιταλική (Λιγουρία) · <strong>Δυσκολία:</strong> εύκολη",
    intro="Το <em>πέστο alla genovese</em> δεν μαγειρεύεται ποτέ και δεν χτυπιέται ζεστό: είναι ένα ωμό γαλάκτωμα όπου το ελαιόλαδο δένει βασιλικό, ξηρούς καρπούς και τυρί. Καμωμένο σωστά, μένει έντονα πράσινο και αρωματικό. Κλειδιά: ποιοτικά υλικά, νεαρός βασιλικός και απαλό ελαιόλαδο.",
    ingredients=[
        "50 g φρέσκα φύλλα βασιλικού (μικρά)",
        "15 g κουκουνάρι",
        "1 μικρή σκελίδα σκόρδο (χωρίς τη μέση)",
        "30 g Parmigiano Reggiano τριμμένο",
        "20 g Pecorino τριμμένο",
        "70–100 ml απαλό έξτρα παρθένο ελαιόλαδο",
        "Χοντρό αλάτι",
    ],
    steps=[
        "<strong>Λιώστε το σκόρδο.</strong> Στο μαρμάρινο γουδί, λιώστε το σκόρδο με λίγους κόκκους χοντρό αλάτι σε πάστα.",
        "<strong>Κουκουνάρι.</strong> Προσθέστε το κουκουνάρι και δουλέψτε το σε κρέμα.",
        "<strong>Βασιλικός.</strong> Προσθέστε τα πλυμένα και στεγνά φύλλα λίγα-λίγα, πιέζοντας με κυκλική κίνηση στα τοιχώματα — όχι χτυπώντας. Ο βασιλικός βγάζει ένα έντονα πράσινο υγρό.",
        "<strong>Τυριά.</strong> Ενσωματώστε παρμεζάνα και πεκορίνο σε κρέμα.",
        "<strong>Ελαιόλαδο.</strong> Ρίξτε το ελαιόλαδο σε λεπτή ροή ανακατεύοντας, μέχρι λεία, γυαλιστερή σάλτσα. Δοκιμάστε το αλάτι.",
        "<strong>Σερβίρισμα.</strong> Αραιώστε με μια κουταλιά νερό βρασίματος, εκτός φωτιάς. Μην το βράσετε ποτέ.",
    ],
    oven="<strong>Εκδοχή στο μπλέντερ (χωρίς οξείδωση):</strong> βάλτε το μπολ και τις λεπίδες στην κατάψυξη 10 λεπτά. Χτυπήστε με πολύ σύντομους παλμούς για να μη ζεσταθεί (η θερμότητα μαυρίζει τον βασιλικό). Για διαρκές πράσινο, ζεματίστε τον βασιλικό 5 δευτερόλεπτα και βυθίστε τον σε παγωμένο νερό.",
    oil="Το ελαιόλαδο δεν είναι απλός συνδετικός παράγοντας: μεταφέρει το άρωμα του βασιλικού και στρογγυλεύει το σκόρδο. Διαλέξτε ένα <strong>απαλό, φρουτώδες έξτρα παρθένο</strong> (τα πολύ πικρά, πικάντικα λάδια σκεπάζουν τον βασιλικό).",
    tips=[
        "Νεαρός, στεγνός βασιλικός: το νερό αραιώνει και οξειδώνει.",
        "Δουλέψτε κρύα, ποτέ ζεστά: το μαγειρεμένο πέστο γίνεται γκρι και πικρό.",
        "Απαλό λάδι, όχι δυνατό, για να μιλήσει ο βασιλικός.",
        "Ανακατέψτε την πάστα εκτός φωτιάς με λίγο νερό βρασίματος.",
        "Για trofie, trenette ή gnocchi: προσθέστε πατάτες και φασολάκια.",
    ],
    variations=[
        "<strong>Χωρίς ξηρούς καρπούς:</strong> αντικαταστήστε το κουκουνάρι με λίγο περισσότερο λάδι.",
        "<strong>Για διατήρηση:</strong> χωρίς τυρί (προσθέστε στο σερβίρισμα) διατηρείται και καταψύχεται καλύτερα.",
    ],
    serve="Το πέστο σερβίρεται ωμό πάνω σε ζεστή πάστα (trofie, trenette, linguine) αραιωμένο με νερό βρασίματος, σε gnocchi, σε μινεστρόνε εκτός φωτιάς ή σε ψωμί. Μην το μαγειρεύετε ποτέ.",
    store="Στο ψυγείο 3–4 ημέρες σε βαζάκι, με ένα στρώμα ελαιόλαδου από πάνω. Καταψύχεται καλά, κατά προτίμηση χωρίς το τυρί.",
    faqs=[
        ("Ποια είναι τα αληθινά υλικά του πέστο alla genovese;",
         "Βασιλικός, κουκουνάρι, σκόρδο, Parmigiano Reggiano, Pecorino, έξτρα παρθένο ελαιόλαδο και χοντρό αλάτι. Τίποτα άλλο: όχι κρέμα, κάσιους ή λεμόνι στην παραδοσιακή συνταγή."),
        ("Γουδί ή μπλέντερ;",
         "Το μαρμάρινο γουδί δίνει το καλύτερο αποτέλεσμα γιατί λιώνει χωρίς θερμότητα. Το μπλέντερ δουλεύει αν κρυώσετε το μπολ και χτυπήσετε με σύντομους παλμούς."),
        ("Γιατί γκριζάρει το πέστο μου;",
         "Από οξείδωση: βρεγμένος βασιλικός, θερμότητα λεπίδων ή έκθεση στον αέρα. Στεγνώστε καλά, δουλέψτε κρύα και σκεπάστε με λάδι. Το ζεμάτισμα 5 δευτερολέπτων σταθεροποιεί το χρώμα."),
        ("Ποια πάστα με πέστο;",
         "Trofie και trenette (ή linguine) Λιγουρίας, συχνά με πατάτες και φασολάκια. Και τα gnocchi ταιριάζουν."),
        ("Καταψύχεται το πέστο;",
         "Ναι, κατά προτίμηση χωρίς τυρί, σε παγοθήκη ή βαζάκι με λάδι. Προσθέστε τα τυριά στο σερβίρισμα."),
    ],
    schema_name="Πέστο αλα Τζενοβέζε σπιτικό",
    schema_desc="Η αυθεντική συνταγή για πέστο genovese στο γουδί: βασιλικός, κουκουνάρι, σκόρδο, παρμεζάνα, πεκορίνο και έξτρα παρθένο ελαιόλαδο.",
    schema_ing=["50 g φρέσκος βασιλικός", "15 g κουκουνάρι", "1 σκελίδα σκόρδο", "30 g Parmigiano",
                "20 g Pecorino", "70-100 ml έξτρα παρθένο ελαιόλαδο", "χοντρό αλάτι"],
    schema_steps=[
        "Λιώστε το σκόρδο με χοντρό αλάτι.", "Προσθέστε κουκουνάρι και λιώστε.",
        "Λιώστε τον βασιλικό στα τοιχώματα του γουδιού.", "Ενσωματώστε παρμεζάνα και πεκορίνο.",
        "Ρίξτε το λάδι σε ροή μέχρι λεία σάλτσα.", "Αραιώστε με νερό βρασίματος εκτός φωτιάς."],
    keywords="πέστο genovese, συνταγή πέστο, σπιτικό πέστο, πέστο βασιλικού, ελαιόλαδο",
    cuisine="Italian", category="Σάλτσα", prep="PT15M", cook="PT0M", total="PT15M", yield_="4 μερίδες",
    nutrition={"servingSize": "1 μερίδα", "calories": "230 kcal", "fatContent": "23 g", "proteinContent": "5 g", "carbohydrateContent": "2 g"},
)

if __name__ == "__main__":
    print("Batch 1:")
    write_cluster("pesto-alla-genovese-maison", PESTO)
