# -*- coding: utf-8 -*-
"""Authentic Carpaccio di manzo (beef carpaccio) x4 languages."""
from recipe_render import write_cluster

C = {}
C["fr"] = dict(
    title="Carpaccio de bœuf : la vraie recette à l'huile d'olive et parmesan",
    desc="Vrai carpaccio de bœuf : filet cru taillé finement, huile d'olive extra vierge, citron, copeaux de parmesan, roquette et câpres. Astuce pour trancher fin, choix de la viande et conseils de sécurité.",
    h1="Carpaccio de bœuf à l'huile d'olive",
    lede="Le carpaccio, né au Harry's Bar de Venise, est une viande de bœuf crue taillée en tranches translucides, assaisonnée simplement d'huile d'olive extra vierge, de citron, de parmesan et de câpres. La réussite tient à la fraîcheur de la viande et à la finesse de la coupe.",
    info="<strong>Préparation :</strong> 20 min (+ 40 min au congélateur) · <strong>Cuisson :</strong> 0 min · <strong>Pour :</strong> 4 personnes (entrée) · <strong>Cuisine :</strong> italienne · <strong>Difficulté :</strong> moyenne",
    intro="Un bon carpaccio ne demande presque rien à cuisiner, mais tout à choisir : une viande très fraîche, une lame bien aiguisée et une huile d'olive de caractère. La version classique à l'italienne se contente de citron, d'huile d'olive, de copeaux de parmesan et de roquette — l'inverse d'une sauce lourde.",
    ingredients=[
        "300 g de filet de bœuf très frais (ou tende de tranche)",
        "4 c. à soupe d'huile d'olive extra vierge fruitée",
        "1 citron (le jus)",
        "40 g de copeaux de Parmigiano Reggiano",
        "1 poignée de roquette",
        "1 c. à soupe de câpres",
        "Poivre noir du moulin, fleur de sel",
    ],
    steps=[
        "<strong>Raffermir la viande.</strong> Placez le filet 30 à 45 minutes au congélateur : ferme mais non gelé, il se tranche beaucoup plus finement.",
        "<strong>Trancher finement.</strong> Avec un couteau bien aiguisé, taillez des tranches les plus fines possible. Pour les affiner encore, placez chaque tranche entre deux feuilles de film et aplatissez délicatement au rouleau ou au plat d'un couteau.",
        "<strong>Dresser.</strong> Répartissez les tranches sans les superposer sur une assiette froide, en couvrant tout le fond.",
        "<strong>Assaisonner.</strong> Fouettez l'huile d'olive extra vierge avec le jus de citron et une pincée de sel ; arrosez la viande. Ajoutez poivre, copeaux de parmesan, roquette et câpres.",
        "<strong>Servir aussitôt.</strong> Le carpaccio se mange immédiatement, bien frais, avec du pain ou des gressins.",
    ],
    oil="Sur une viande crue, l'huile d'olive est l'assaisonnement principal : elle nappe, adoucit et relève. Choisissez une <strong>extra vierge fruitée, un peu poivrée</strong> : son amertume élégante équilibre le gras du bœuf et réveille l'ensemble. Ajoutez-la juste avant de servir.",
    tips=[
        "Viande très fraîche et de qualité, d'un boucher de confiance : c'est la règle numéro un pour du cru.",
        "Raffermir au froid avant de couper = tranches plus fines.",
        "Assiette froide et service immédiat : le carpaccio ne s'attend pas.",
        "Assaisonnez au dernier moment : le citron « cuit » et grise la viande s'il est ajouté trop tôt.",
    ],
    variations=[
        "<strong>Sauce à l'italienne :</strong> quelques gouttes de sauce crémeuse citronnée à la place du filet d'huile-citron.",
        "<strong>Autres carpaccios :</strong> même principe avec de la daurade, du thon, des Saint-Jacques ou, en version végétale, des courgettes ou des betteraves finement tranchées.",
    ],
    serve="Servez le carpaccio en entrée fraîche, nappé d'huile d'olive au dernier moment, avec du pain grillé, des gressins ou une petite salade de roquette. Un verre d'eau glacée et un citron à part permettent à chacun d'ajuster l'acidité.",
    store="Le carpaccio se prépare et se consomme le jour même. La viande crue tranchée ne se conserve pas : gardez-la au réfrigérateur jusqu'au service et ne la laissez jamais à température ambiante. Déconseillé aux femmes enceintes et aux personnes immunodéprimées (viande crue).",
    faqs=[
        ("Quelle viande pour un carpaccio de bœuf ?",
         "Un morceau maigre, tendre et très frais : filet de bœuf idéalement, ou tende de tranche (rumsteck). Achetez-le entier chez un boucher de confiance et tranchez-le vous-même le jour même."),
        ("Le carpaccio est-il cru ? Est-ce sans risque ?",
         "Oui, c'est de la viande crue. Le risque est maîtrisé avec une viande très fraîche et de qualité, gardée au froid et servie immédiatement. Il reste déconseillé aux femmes enceintes, aux jeunes enfants et aux personnes immunodéprimées."),
        ("Comment couper le carpaccio très finement ?",
         "Raffermissez la viande 30 à 45 minutes au congélateur, utilisez un couteau bien aiguisé, puis aplatissez chaque tranche entre deux films alimentaires si nécessaire."),
        ("Huile d'olive et citron, ou sauce ?",
         "La version italienne classique se fait à l'huile d'olive extra vierge et au citron, avec parmesan et roquette. La version d'origine du Harry's Bar utilisait une sauce crémeuse citronnée : c'est une question de goût."),
        ("Peut-on préparer le carpaccio à l'avance ?",
         "On peut trancher la viande quelques heures avant et la garder au froid entre des films, mais on ne l'assaisonne qu'au moment de servir, sinon le citron la fait griser."),
    ],
    schema_name="Carpaccio de bœuf à l'huile d'olive",
    schema_desc="Vrai carpaccio de bœuf : filet cru taillé finement, huile d'olive extra vierge, citron, parmesan, roquette et câpres.",
    schema_ing=["300 g filet de bœuf très frais", "4 c. à soupe huile d'olive extra vierge", "1 citron",
                "40 g copeaux de parmesan", "roquette", "1 c. à soupe câpres", "poivre noir, fleur de sel"],
    schema_steps=[
        "Raffermir le filet 30-45 min au congélateur.",
        "Trancher très finement au couteau, aplatir entre deux films si besoin.",
        "Disposer les tranches sur une assiette froide.",
        "Assaisonner d'huile d'olive, citron, sel, poivre, parmesan, roquette et câpres.",
        "Servir immédiatement, bien frais."],
    keywords="carpaccio de boeuf, carpaccio boeuf parmesan, recette carpaccio, carpaccio huile d'olive, viande crue",
    cuisine="Italian", category="Entrée", prep="PT20M", cook="PT0M", total="PT20M", yield_="4 servings",
    nutrition={"servingSize": "1 portion", "calories": "210 kcal", "fatContent": "15 g", "proteinContent": "17 g", "carbohydrateContent": "1 g"},
)
C["en"] = dict(
    title="Beef Carpaccio: the real recipe with olive oil and Parmesan",
    desc="Real beef carpaccio: raw fillet sliced paper-thin, extra virgin olive oil, lemon, shaved Parmesan, arugula and capers. How to slice it thin, which cut to choose, and food-safety tips.",
    h1="Beef Carpaccio with olive oil",
    lede="Carpaccio, born at Harry's Bar in Venice, is raw beef sliced into translucent sheets, dressed simply with extra virgin olive oil, lemon, Parmesan and capers. Success comes down to the freshness of the meat and the thinness of the cut.",
    info="<strong>Prep:</strong> 20 min (+40 min freezer) · <strong>Cook:</strong> 0 min · <strong>Serves:</strong> 4 (starter) · <strong>Cuisine:</strong> Italian · <strong>Difficulty:</strong> medium",
    intro="A good carpaccio asks almost nothing of the cook but everything of the shopping: very fresh meat, a sharp blade and a characterful olive oil. The classic Italian version needs only lemon, olive oil, shaved Parmesan and arugula — the opposite of a heavy sauce.",
    ingredients=[
        "300 g very fresh beef fillet (or eye of round)",
        "4 tbsp fruity extra virgin olive oil",
        "1 lemon (juice)",
        "40 g shaved Parmigiano Reggiano",
        "1 handful arugula (rocket)",
        "1 tbsp capers",
        "Freshly ground black pepper, flaky salt",
    ],
    steps=[
        "<strong>Firm the meat.</strong> Freeze the fillet for 30–45 minutes: firm but not frozen, it slices far thinner.",
        "<strong>Slice thin.</strong> With a very sharp knife, cut the thinnest slices you can. To thin them further, place each slice between two sheets of film and gently flatten with a rolling pin or the flat of a knife.",
        "<strong>Plate.</strong> Lay the slices in a single layer on a cold plate, covering the whole base.",
        "<strong>Dress.</strong> Whisk the extra virgin olive oil with the lemon juice and a pinch of salt; spoon over the meat. Add pepper, shaved Parmesan, arugula and capers.",
        "<strong>Serve at once.</strong> Carpaccio is eaten immediately, well chilled, with bread or grissini.",
    ],
    oil="On raw meat, olive oil is the main seasoning: it coats, softens and lifts. Choose a <strong>fruity, slightly peppery extra virgin</strong>: its elegant bitterness balances the richness of the beef and wakes the whole plate. Add it just before serving.",
    tips=[
        "Very fresh, high-quality meat from a trusted butcher: rule number one for anything raw.",
        "Firm in the freezer before cutting = thinner slices.",
        "Cold plate and immediate service: carpaccio does not wait.",
        "Season at the last moment: lemon 'cooks' and greys the meat if added too early.",
    ],
    variations=[
        "<strong>Harry's Bar sauce:</strong> a few drops of creamy lemon sauce instead of the oil-lemon dressing.",
        "<strong>Other carpaccios:</strong> same idea with sea bream, tuna, scallops or, plant-based, thinly sliced courgette or beetroot.",
    ],
    serve="Serve carpaccio as a chilled starter, dressed with olive oil at the last moment, with toasted bread, grissini or a small arugula salad. Iced water and a lemon on the side let everyone adjust the acidity.",
    store="Carpaccio is made and eaten the same day. Sliced raw meat does not keep: refrigerate until serving and never leave it at room temperature. Not recommended for pregnant women or immunocompromised people (raw meat).",
    faqs=[
        ("Which cut for beef carpaccio?",
         "A lean, tender, very fresh cut: beef fillet ideally, or eye of round. Buy it whole from a trusted butcher and slice it yourself on the day."),
        ("Is carpaccio raw? Is it safe?",
         "Yes, it is raw meat. The risk is controlled with very fresh, high-quality meat kept cold and served immediately. It remains inadvisable for pregnant women, young children and immunocompromised people."),
        ("How do I slice carpaccio very thin?",
         "Firm the meat for 30–45 minutes in the freezer, use a very sharp knife, then flatten each slice between two sheets of film if needed."),
        ("Olive oil and lemon, or a sauce?",
         "The classic Italian version uses extra virgin olive oil and lemon with Parmesan and arugula. The original Harry's Bar version used a creamy lemon sauce — it is a matter of taste."),
        ("Can carpaccio be prepared ahead?",
         "You can slice the meat a few hours ahead and keep it cold between films, but dress it only at serving time, otherwise the lemon greys it."),
    ],
    schema_name="Beef Carpaccio with olive oil",
    schema_desc="Real beef carpaccio: raw fillet sliced paper-thin, extra virgin olive oil, lemon, Parmesan, arugula and capers.",
    schema_ing=["300 g very fresh beef fillet", "4 tbsp extra virgin olive oil", "1 lemon",
                "40 g shaved Parmesan", "arugula", "1 tbsp capers", "black pepper, flaky salt"],
    schema_steps=[
        "Firm the fillet 30-45 min in the freezer.",
        "Slice paper-thin; flatten between film if needed.",
        "Lay slices on a cold plate.",
        "Dress with olive oil, lemon, salt, pepper, Parmesan, arugula and capers.",
        "Serve immediately, well chilled."],
    keywords="beef carpaccio, carpaccio recipe, carpaccio olive oil, beef carpaccio parmesan, raw beef",
    cuisine="Italian", category="Appetizer", prep="PT20M", cook="PT0M", total="PT20M", yield_="4 servings",
    nutrition={"servingSize": "1 serving", "calories": "210 kcal", "fatContent": "15 g", "proteinContent": "17 g", "carbohydrateContent": "1 g"},
)
C["it"] = dict(
    title="Carpaccio di manzo: la vera ricetta con olio d'oliva e parmigiano",
    desc="Vero carpaccio di manzo: filetto crudo tagliato sottilissimo, olio extravergine d'oliva, limone, scaglie di parmigiano, rucola e capperi. Come affettarlo sottile, quale taglio scegliere e consigli di sicurezza.",
    h1="Carpaccio di manzo all'olio d'oliva",
    lede="Il carpaccio, nato all'Harry's Bar di Venezia, è carne di manzo cruda tagliata in fette trasparenti, condita semplicemente con olio extravergine d'oliva, limone, parmigiano e capperi. La riuscita dipende dalla freschezza della carne e dalla finezza del taglio.",
    info="<strong>Preparazione:</strong> 20 min (+40 min freezer) · <strong>Cottura:</strong> 0 min · <strong>Per:</strong> 4 persone (antipasto) · <strong>Cucina:</strong> italiana · <strong>Difficoltà:</strong> media",
    intro="Un buon carpaccio non chiede quasi nulla al cuoco ma tutto alla spesa: carne freschissima, una lama affilata e un olio di carattere. La versione classica italiana usa solo limone, olio, scaglie di parmigiano e rucola.",
    ingredients=[
        "300 g di filetto di manzo freschissimo (o girello)",
        "4 cucchiai di olio extravergine d'oliva fruttato",
        "1 limone (succo)",
        "40 g di scaglie di Parmigiano Reggiano",
        "1 manciata di rucola",
        "1 cucchiaio di capperi",
        "Pepe nero macinato, sale in fiocchi",
    ],
    steps=[
        "<strong>Rassodare la carne.</strong> Metti il filetto in freezer 30–45 minuti: sodo ma non congelato si affetta molto più sottile.",
        "<strong>Affettare sottile.</strong> Con un coltello ben affilato taglia fette il più sottili possibile. Per assottigliarle ancora, mettile tra due fogli di pellicola e appiattiscile con il mattarello.",
        "<strong>Impiattare.</strong> Disponi le fette in un solo strato su un piatto freddo, coprendo tutto il fondo.",
        "<strong>Condire.</strong> Emulsiona l'olio extravergine con il succo di limone e un pizzico di sale; versa sulla carne. Aggiungi pepe, scaglie di parmigiano, rucola e capperi.",
        "<strong>Servire subito.</strong> Il carpaccio si mangia immediatamente, ben freddo, con pane o grissini.",
    ],
    oil="Sulla carne cruda l'olio d'oliva è il condimento principale: avvolge, ammorbidisce ed esalta. Scegli un <strong>extravergine fruttato, un po' piccante</strong>: l'amaro elegante bilancia il grasso del manzo. Aggiungilo appena prima di servire.",
    tips=[
        "Carne freschissima e di qualità, da un macellaio di fiducia: regola numero uno per il crudo.",
        "Rassodare al freddo prima di tagliare = fette più sottili.",
        "Piatto freddo e servizio immediato: il carpaccio non aspetta.",
        "Condire all'ultimo: il limone 'cuoce' e ingrigisce la carne se aggiunto troppo presto.",
    ],
    variations=[
        "<strong>Salsa Harry's Bar:</strong> qualche goccia di salsa cremosa al limone al posto di olio-limone.",
        "<strong>Altri carpacci:</strong> stesso principio con orata, tonno, capesante o, vegetale, zucchine o barbabietole a fette sottili.",
    ],
    serve="Servi il carpaccio come antipasto freddo, condito con olio all'ultimo, con pane tostato, grissini o una piccola insalata di rucola. Acqua ghiacciata e un limone a parte permettono a ciascuno di regolare l'acidità.",
    store="Il carpaccio si prepara e si consuma in giornata. La carne cruda affettata non si conserva: tienila in frigo fino al servizio e non lasciarla mai a temperatura ambiente. Sconsigliato a donne in gravidanza e persone immunodepresse (carne cruda).",
    faqs=[
        ("Quale taglio per il carpaccio di manzo?",
         "Un taglio magro, tenero e freschissimo: filetto idealmente, o girello. Compralo intero da un macellaio di fiducia e affettalo tu il giorno stesso."),
        ("Il carpaccio è crudo? È sicuro?",
         "Sì, è carne cruda. Il rischio è controllato con carne freschissima e di qualità, tenuta al freddo e servita subito. Resta sconsigliato a donne in gravidanza, bambini piccoli e persone immunodepresse."),
        ("Come affettare il carpaccio molto sottile?",
         "Rassoda la carne 30–45 minuti in freezer, usa un coltello affilato, poi appiattisci ogni fetta tra due fogli di pellicola se serve."),
        ("Olio e limone o salsa?",
         "La versione classica italiana usa olio extravergine e limone con parmigiano e rucola. L'originale dell'Harry's Bar usava una salsa cremosa al limone: è questione di gusto."),
        ("Si può preparare in anticipo?",
         "Puoi affettare la carne qualche ora prima e tenerla al freddo tra pellicole, ma condiscila solo al momento di servire, altrimenti il limone la ingrigisce."),
    ],
    schema_name="Carpaccio di manzo all'olio d'oliva",
    schema_desc="Vero carpaccio di manzo: filetto crudo sottilissimo, olio extravergine d'oliva, limone, parmigiano, rucola e capperi.",
    schema_ing=["300 g filetto di manzo freschissimo", "4 cucchiai olio extravergine d'oliva", "1 limone",
                "40 g scaglie di parmigiano", "rucola", "1 cucchiaio capperi", "pepe nero, sale in fiocchi"],
    schema_steps=[
        "Rassodare il filetto 30-45 min in freezer.",
        "Affettare sottilissimo; appiattire tra pellicola se serve.",
        "Disporre le fette su un piatto freddo.",
        "Condire con olio, limone, sale, pepe, parmigiano, rucola e capperi.",
        "Servire subito, ben freddo."],
    keywords="carpaccio di manzo, ricetta carpaccio, carpaccio olio d'oliva, carpaccio parmigiano, carne cruda",
    cuisine="Italian", category="Antipasto", prep="PT20M", cook="PT0M", total="PT20M", yield_="4 porzioni",
    nutrition={"servingSize": "1 porzione", "calories": "210 kcal", "fatContent": "15 g", "proteinContent": "17 g", "carbohydrateContent": "1 g"},
)
C["el"] = dict(
    title="Καρπάτσιο μοσχαρίσιο: η αυθεντική συνταγή με ελαιόλαδο και παρμεζάνα",
    desc="Αληθινό καρπάτσιο μοσχαριού: ωμό φιλέτο κομμένο πολύ λεπτά, έξτρα παρθένο ελαιόλαδο, λεμόνι, παρμεζάνα, ρόκα και κάπαρη. Πώς να το κόψετε λεπτό, ποιο κομμάτι και συμβουλές ασφάλειας.",
    h1="Καρπάτσιο μοσχαρίσιο με ελαιόλαδο",
    lede="Το καρπάτσιο, γεννημένο στο Harry's Bar της Βενετίας, είναι ωμό μοσχάρι κομμένο σε διάφανες φέτες, με απλό ντύσιμο από έξτρα παρθένο ελαιόλαδο, λεμόνι, παρμεζάνα και κάπαρη. Η επιτυχία εξαρτάται από τη φρεσκάδα του κρέατος και τη λεπτότητα της κοπής.",
    info="<strong>Προετοιμασία:</strong> 20 λεπτά (+40 λεπτά κατάψυξη) · <strong>Μαγείρεμα:</strong> 0 λεπτά · <strong>Μερίδες:</strong> 4 (ορεκτικό) · <strong>Κουζίνα:</strong> ιταλική · <strong>Δυσκολία:</strong> μέτρια",
    intro="Ένα καλό καρπάτσιο δεν ζητά σχεδόν τίποτα από τον μάγειρα, αλλά τα πάντα από τα ψώνια: φρεσκότατο κρέας, κοφτερή λεπίδα και ένα ελαιόλαδο με χαρακτήρα. Η κλασική ιταλική εκδοχή θέλει μόνο λεμόνι, ελαιόλαδο, παρμεζάνα και ρόκα.",
    ingredients=[
        "300 g φρεσκότατο μοσχαρίσιο φιλέτο",
        "4 κ.σ. φρουτώδες έξτρα παρθένο ελαιόλαδο",
        "1 λεμόνι (χυμός)",
        "40 g παρμεζάνα σε φλούδες",
        "1 χούφτα ρόκα",
        "1 κ.σ. κάπαρη",
        "Φρεσκοτριμμένο πιπέρι, αλάτι σε νιφάδες",
    ],
    steps=[
        "<strong>Σφίξτε το κρέας.</strong> Βάλτε το φιλέτο στην κατάψυξη 30–45 λεπτά: σφιχτό αλλά όχι παγωμένο κόβεται πολύ πιο λεπτό.",
        "<strong>Κόψτε λεπτά.</strong> Με κοφτερό μαχαίρι κόψτε όσο πιο λεπτές φέτες μπορείτε. Για ακόμη λεπτότερες, βάλτε κάθε φέτα ανάμεσα σε δύο μεμβράνες και πιέστε ελαφρά.",
        "<strong>Σερβίρετε στο πιάτο.</strong> Απλώστε τις φέτες σε μία στρώση σε κρύο πιάτο, καλύπτοντας όλο τον πάτο.",
        "<strong>Ντύστε.</strong> Χτυπήστε το ελαιόλαδο με τον χυμό λεμονιού και λίγο αλάτι· περιχύστε το κρέας. Προσθέστε πιπέρι, παρμεζάνα, ρόκα και κάπαρη.",
        "<strong>Σερβίρετε αμέσως.</strong> Το καρπάτσιο τρώγεται αμέσως, καλά παγωμένο, με ψωμί ή γκρισίνι.",
    ],
    oil="Στο ωμό κρέας το ελαιόλαδο είναι το κύριο καρύκευμα: αγκαλιάζει, απαλύνει και αναδεικνύει. Διαλέξτε ένα <strong>φρουτώδες, ελαφρώς πικάντικο έξτρα παρθένο</strong>: η κομψή πικράδα ισορροπεί το λίπος του μοσχαριού. Προσθέστε το λίγο πριν το σερβίρισμα.",
    tips=[
        "Φρεσκότατο, ποιοτικό κρέας από έμπιστο κρεοπώλη: κανόνας νούμερο ένα για το ωμό.",
        "Σφίξιμο στο κρύο πριν την κοπή = λεπτότερες φέτες.",
        "Κρύο πιάτο και άμεσο σερβίρισμα: το καρπάτσιο δεν περιμένει.",
        "Ντύστε την τελευταία στιγμή: το λεμόνι «μαγειρεύει» και γκριζάρει το κρέας αν μπει νωρίς.",
    ],
    variations=[
        "<strong>Σάλτσα Harry's Bar:</strong> λίγες σταγόνες κρεμώδους σάλτσας λεμονιού αντί για λάδι-λεμόνι.",
        "<strong>Άλλα καρπάτσιο:</strong> ίδια λογική με τσιπούρα, τόνο, χτένια ή, σε φυτική εκδοχή, κολοκυθάκι ή παντζάρι σε λεπτές φέτες.",
    ],
    serve="Σερβίρετε το καρπάτσιο ως κρύο ορεκτικό, με ελαιόλαδο την τελευταία στιγμή, με ψωμί, γκρισίνι ή μια μικρή σαλάτα ρόκας. Παγωμένο νερό και λεμόνι στο πλάι αφήνουν τον καθένα να ρυθμίσει την οξύτητα.",
    store="Το καρπάτσιο φτιάχνεται και τρώγεται την ίδια μέρα. Το ωμό κομμένο κρέας δεν διατηρείται: κρατήστε το στο ψυγείο μέχρι το σερβίρισμα. Δεν συνιστάται σε εγκύους και ανοσοκατεσταλμένους (ωμό κρέας).",
    faqs=[
        ("Ποιο κομμάτι για μοσχαρίσιο καρπάτσιο;",
         "Ένα άπαχο, τρυφερό, φρεσκότατο κομμάτι: φιλέτο ιδανικά. Αγοράστε το ολόκληρο από έμπιστο κρεοπώλη και κόψτε το την ίδια μέρα."),
        ("Είναι ωμό το καρπάτσιο; Είναι ασφαλές;",
         "Ναι, είναι ωμό κρέας. Ο κίνδυνος ελέγχεται με φρεσκότατο, ποιοτικό κρέας που μένει στο κρύο και σερβίρεται αμέσως. Παραμένει μη συνιστώμενο σε εγκύους, μικρά παιδιά και ανοσοκατεσταλμένους."),
        ("Πώς κόβω το καρπάτσιο πολύ λεπτό;",
         "Σφίξτε το κρέας 30–45 λεπτά στην κατάψυξη, χρησιμοποιήστε κοφτερό μαχαίρι και πιέστε κάθε φέτα ανάμεσα σε δύο μεμβράνες αν χρειάζεται."),
        ("Ελαιόλαδο και λεμόνι ή σάλτσα;",
         "Η κλασική ιταλική εκδοχή θέλει έξτρα παρθένο ελαιόλαδο και λεμόνι με παρμεζάνα και ρόκα. Το πρωτότυπο του Harry's Bar είχε κρεμώδη σάλτσα λεμονιού — θέμα γούστου."),
        ("Ετοιμάζεται από πριν;",
         "Μπορείτε να κόψετε το κρέας λίγες ώρες πριν και να το κρατήσετε στο κρύο ανάμεσα σε μεμβράνες, αλλά ντύστε το μόνο στο σερβίρισμα."),
    ],
    schema_name="Καρπάτσιο μοσχαρίσιο με ελαιόλαδο",
    schema_desc="Αληθινό καρπάτσιο μοσχαριού: ωμό φιλέτο πολύ λεπτό, έξτρα παρθένο ελαιόλαδο, λεμόνι, παρμεζάνα, ρόκα και κάπαρη.",
    schema_ing=["300 g φρέσκο μοσχαρίσιο φιλέτο", "4 κ.σ. έξτρα παρθένο ελαιόλαδο", "1 λεμόνι",
                "40 g παρμεζάνα σε φλούδες", "ρόκα", "1 κ.σ. κάπαρη", "πιπέρι, αλάτι σε νιφάδες"],
    schema_steps=[
        "Σφίξτε το φιλέτο 30-45 λεπτά στην κατάψυξη.",
        "Κόψτε πολύ λεπτά· πιέστε ανάμεσα σε μεμβράνη αν χρειάζεται.",
        "Απλώστε τις φέτες σε κρύο πιάτο.",
        "Ντύστε με ελαιόλαδο, λεμόνι, αλάτι, πιπέρι, παρμεζάνα, ρόκα και κάπαρη.",
        "Σερβίρετε αμέσως, καλά παγωμένο."],
    keywords="καρπάτσιο μοσχαρίσιο, καρπάτσιο μοσχάρι, συνταγή καρπάτσιο, καρπάτσιο ελαιόλαδο, ωμό κρέας",
    cuisine="Italian", category="Ορεκτικό", prep="PT20M", cook="PT0M", total="PT20M", yield_="4 μερίδες",
    nutrition={"servingSize": "1 μερίδα", "calories": "210 kcal", "fatContent": "15 g", "proteinContent": "17 g", "carbohydrateContent": "1 g"},
)

if __name__ == "__main__":
    write_cluster("carpaccio-boeuf-parmesan", C)
