# -*- coding: utf-8 -*-
"""Batch 3a: authentic EVOO guides — for health, in cooking. x4 languages.
Evidence-informed, cautious YMYL language, EU polyphenol health claim, PREDIMED."""
from guide_render import write_guide_cluster

DISC = {
    "fr": "Cet article est informatif et ne remplace pas un avis médical. Pour toute question de santé, consultez un professionnel.",
    "en": "This article is informational and is not a substitute for medical advice. For any health concern, consult a professional.",
    "it": "Questo articolo è informativo e non sostituisce un parere medico. Per qualsiasi problema di salute, consulta un professionista.",
    "el": "Το άρθρο είναι ενημερωτικό και δεν υποκαθιστά ιατρική συμβουλή. Για κάθε θέμα υγείας, συμβουλευτείτε επαγγελματία.",
}

# ================================================================== HEALTH ====
H = {}
H["fr"] = dict(
    title="Huile d'olive extra vierge et santé : bienfaits réels, preuves et dosage",
    desc="Que dit vraiment la science sur les bienfaits de l'huile d'olive extra vierge : acide oléique, polyphénols (hydroxytyrosol, oléocanthal), régime méditerranéen, allégation santé européenne et dose utile.",
    h1="Huile d'olive extra vierge et santé : ce que disent les preuves",
    lede="L'huile d'olive extra vierge est au cœur du régime méditerranéen. Voici, sans exagération, ce que la recherche établit sur ses bienfaits, grâce à quels composés, et comment en tirer parti au quotidien.",
    section="health", datePublished="2026-05-04", disclaimer=DISC["fr"],
    keywords="bienfaits huile d'olive, huile d'olive extra vierge santé, polyphénols huile d'olive, acide oléique, régime méditerranéen",
    intro="On prête beaucoup de vertus à l'huile d'olive. Certaines sont solidement documentées, d'autres relèvent du marketing. Cet article fait le tri : ce qui est établi, ce qui est probable, et ce qui reste incertain — avec les composés responsables et la dose réaliste.",
    key_facts=[
        "L'huile d'olive extra vierge est riche en acide oléique (graisse mono-insaturée) et en polyphénols antioxydants.",
        "L'Union européenne autorise une allégation santé : les polyphénols de l'huile d'olive contribuent à protéger les lipides sanguins du stress oxydatif (bénéfice avec 5 mg d'hydroxytyrosol et dérivés pour 20 g d'huile par jour).",
        "L'essai clinique PREDIMED a associé un régime méditerranéen enrichi en huile d'olive extra vierge à moins d'événements cardiovasculaires.",
        "Une cuillère à soupe apporte ~120 kcal : l'huile d'olive est bénéfique mais reste calorique.",
    ],
    sections=[
        ("Ce qui rend l'huile d'olive extra vierge différente",
         "<p>L'huile d'olive extra vierge est un jus de fruit gras, extrait à froid et non raffiné. Elle conserve donc deux familles de composés utiles : une majorité d'<strong>acide oléique</strong> (graisse mono-insaturée) et des <strong>polyphénols</strong> (hydroxytyrosol, tyrosol, oléuropéine, oléocanthal) que le raffinage détruit en grande partie. C'est cette combinaison qui distingue l'« extra vierge » des huiles d'olive raffinées ou « légères ».</p>"),
        ("Graisses mono-insaturées et cœur",
         "<p>Remplacer des graisses saturées (beurre, charcuterie) par des graisses mono-insaturées comme l'acide oléique est associé à un profil lipidique plus favorable. C'est l'un des mécanismes avancés pour expliquer le lien entre huile d'olive et santé cardiovasculaire dans les populations méditerranéennes.</p>"),
        ("Polyphénols et antioxydants",
         "<p>Les polyphénols de l'huile d'olive ont une activité antioxydante et anti-inflammatoire. L'<strong>oléocanthal</strong>, responsable du picotement en gorge des huiles jeunes, a montré in vitro un effet anti-inflammatoire comparable, à faible échelle, à celui de l'ibuprofène. L'<strong>hydroxytyrosol</strong> fait l'objet de la seule allégation santé européenne autorisée pour l'huile d'olive : ses polyphénols contribuent à protéger les lipides du sang contre le stress oxydatif.</p>"),
        ("La preuve par le régime méditerranéen",
         "<p>Le bénéfice le mieux documenté ne concerne pas l'huile d'olive isolée mais le <strong>régime méditerranéen</strong> dans son ensemble. L'essai contrôlé PREDIMED a suivi des milliers de personnes à risque : celles suivant un régime méditerranéen complété en huile d'olive extra vierge ont présenté moins d'accidents cardiovasculaires majeurs que le groupe témoin. L'huile d'olive y joue un rôle central, mais associée aux légumes, légumineuses, poisson et fruits à coque.</p>"),
        ("Comment en tirer parti",
         "<p>Pour profiter des polyphénols, privilégiez une <strong>huile d'olive extra vierge</strong> de qualité, récente et bien conservée (à l'abri de la lumière et de la chaleur), et utilisez-en une partie <strong>à cru</strong> (assaisonnements, filet de finition). Une consommation quotidienne d'environ 2 cuillères à soupe s'inscrit bien dans une alimentation équilibrée. L'huile d'olive n'est pas un médicament : elle agit dans la durée, au sein d'un régime globalement sain.</p>"),
    ],
    faqs=[
        ("Quels sont les bienfaits de l'huile d'olive extra vierge ?",
         "Elle apporte de l'acide oléique (graisse mono-insaturée) et des polyphénols antioxydants. La recherche l'associe, dans le cadre du régime méditerranéen, à une meilleure santé cardiovasculaire et à une protection des lipides sanguins contre l'oxydation."),
        ("L'huile d'olive est-elle bonne pour la santé ?",
         "Oui, dans le cadre d'une alimentation équilibrée. C'est une source de bonnes graisses et d'antioxydants, mieux valorisée en remplacement des graisses saturées, et non en simple ajout de calories."),
        ("Quelle quantité d'huile d'olive par jour ?",
         "Environ 2 cuillères à soupe par jour s'intègrent bien à un régime équilibré. L'allégation santé européenne repose sur 20 g d'huile riche en polyphénols par jour. Restez mesuré : une cuillère apporte environ 120 kcal."),
        ("Extra vierge ou raffinée pour la santé ?",
         "L'extra vierge est préférable : le raffinage détruit une grande partie des polyphénols. C'est cette fraction polyphénolique qui porte la plupart des effets antioxydants."),
        ("Faut-il consommer l'huile d'olive à cru ?",
         "En partie, oui. La cuisson dégrade progressivement certains polyphénols ; garder un filet cru pour la finition préserve mieux le parfum et les composés antioxydants."),
    ],
)
H["en"] = dict(
    title="Extra Virgin Olive Oil and Health: real benefits, evidence and dose",
    desc="What science actually says about the benefits of extra virgin olive oil: oleic acid, polyphenols (hydroxytyrosol, oleocanthal), the Mediterranean diet, the EU health claim and a useful daily amount.",
    h1="Extra Virgin Olive Oil and Health: what the evidence says",
    lede="Extra virgin olive oil is at the heart of the Mediterranean diet. Here, without exaggeration, is what research establishes about its benefits, through which compounds, and how to make the most of it day to day.",
    section="health", datePublished="2026-05-04", disclaimer=DISC["en"],
    keywords="olive oil benefits, extra virgin olive oil health, olive oil polyphenols, oleic acid, mediterranean diet",
    intro="Olive oil is credited with many virtues. Some are well documented, others are marketing. This article sorts them out: what is established, what is likely, and what remains uncertain — with the compounds responsible and a realistic dose.",
    key_facts=[
        "Extra virgin olive oil is rich in oleic acid (a monounsaturated fat) and antioxidant polyphenols.",
        "The EU authorises a health claim: olive oil polyphenols help protect blood lipids from oxidative stress (benefit at 5 mg hydroxytyrosol and derivatives per 20 g of oil daily).",
        "The PREDIMED clinical trial linked a Mediterranean diet enriched with extra virgin olive oil to fewer cardiovascular events.",
        "One tablespoon provides ~120 kcal: olive oil is beneficial but still calorie-dense.",
    ],
    sections=[
        ("What makes extra virgin olive oil different",
         "<p>Extra virgin olive oil is a cold-extracted, unrefined fruit juice. It therefore keeps two useful families of compounds: mostly <strong>oleic acid</strong> (a monounsaturated fat) and <strong>polyphenols</strong> (hydroxytyrosol, tyrosol, oleuropein, oleocanthal) that refining largely destroys. This combination is what sets 'extra virgin' apart from refined or 'light' olive oils.</p>"),
        ("Monounsaturated fats and the heart",
         "<p>Replacing saturated fats (butter, processed meat) with monounsaturated fats such as oleic acid is associated with a more favourable lipid profile. This is one of the proposed mechanisms behind the link between olive oil and cardiovascular health in Mediterranean populations.</p>"),
        ("Polyphenols and antioxidants",
         "<p>Olive oil polyphenols have antioxidant and anti-inflammatory activity. <strong>Oleocanthal</strong>, responsible for the throat sting of young oils, has shown in vitro an anti-inflammatory effect comparable, on a small scale, to ibuprofen. <strong>Hydroxytyrosol</strong> underlies the only EU-authorised health claim for olive oil: its polyphenols help protect blood lipids from oxidative stress.</p>"),
        ("The evidence from the Mediterranean diet",
         "<p>The best-documented benefit is not for olive oil alone but for the <strong>Mediterranean diet</strong> as a whole. The PREDIMED controlled trial followed thousands of at-risk people: those on a Mediterranean diet supplemented with extra virgin olive oil had fewer major cardiovascular events than the control group. Olive oil plays a central role there, but alongside vegetables, legumes, fish and nuts.</p>"),
        ("How to get the benefits",
         "<p>To benefit from the polyphenols, choose a quality <strong>extra virgin olive oil</strong>, fresh and well stored (away from light and heat), and use some of it <strong>raw</strong> (dressings, a finishing drizzle). About 2 tablespoons a day fits well within a balanced diet. Olive oil is not a medicine: it works over time, within an overall healthy diet.</p>"),
    ],
    faqs=[
        ("What are the benefits of extra virgin olive oil?",
         "It provides oleic acid (a monounsaturated fat) and antioxidant polyphenols. Within the Mediterranean diet, research associates it with better cardiovascular health and protection of blood lipids from oxidation."),
        ("Is olive oil good for you?",
         "Yes, as part of a balanced diet. It is a source of good fats and antioxidants, best used to replace saturated fats rather than simply adding calories."),
        ("How much olive oil per day?",
         "About 2 tablespoons a day fits a balanced diet well. The EU health claim is based on 20 g of polyphenol-rich oil per day. Stay moderate: one tablespoon is about 120 kcal."),
        ("Extra virgin or refined for health?",
         "Extra virgin is preferable: refining destroys much of the polyphenols. It is this polyphenol fraction that carries most of the antioxidant effects."),
        ("Should olive oil be eaten raw?",
         "Partly, yes. Cooking gradually degrades some polyphenols; keeping a raw drizzle for finishing better preserves the aroma and antioxidant compounds."),
    ],
)
H["it"] = dict(
    title="Olio extravergine d'oliva e salute: benefici reali, prove e dose",
    desc="Cosa dice davvero la scienza sui benefici dell'olio extravergine d'oliva: acido oleico, polifenoli (idrossitirosolo, oleocantale), dieta mediterranea, claim salutistico UE e dose utile.",
    h1="Olio extravergine d'oliva e salute: cosa dicono le prove",
    lede="L'olio extravergine d'oliva è al centro della dieta mediterranea. Ecco, senza esagerazioni, cosa stabilisce la ricerca sui suoi benefici, grazie a quali composti e come sfruttarli ogni giorno.",
    section="health", datePublished="2026-05-04", disclaimer=DISC["it"],
    keywords="benefici olio d'oliva, olio extravergine salute, polifenoli olio d'oliva, acido oleico, dieta mediterranea",
    intro="All'olio d'oliva si attribuiscono molte virtù. Alcune sono ben documentate, altre sono marketing. Questo articolo fa chiarezza: cosa è stabilito, cosa è probabile e cosa resta incerto — con i composti responsabili e una dose realistica.",
    key_facts=[
        "L'olio extravergine d'oliva è ricco di acido oleico (grasso monoinsaturo) e polifenoli antiossidanti.",
        "L'UE autorizza un claim salutistico: i polifenoli dell'olio d'oliva aiutano a proteggere i lipidi del sangue dallo stress ossidativo (beneficio con 5 mg di idrossitirosolo e derivati per 20 g di olio al giorno).",
        "Lo studio clinico PREDIMED ha collegato una dieta mediterranea arricchita con olio extravergine a meno eventi cardiovascolari.",
        "Un cucchiaio fornisce ~120 kcal: l'olio d'oliva è benefico ma resta calorico.",
    ],
    sections=[
        ("Cosa rende diverso l'olio extravergine d'oliva",
         "<p>L'olio extravergine d'oliva è un succo di frutta grasso, estratto a freddo e non raffinato. Conserva quindi due famiglie di composti utili: soprattutto <strong>acido oleico</strong> (grasso monoinsaturo) e <strong>polifenoli</strong> (idrossitirosolo, tirosolo, oleuropeina, oleocantale) che la raffinazione distrugge in gran parte. È questa combinazione a distinguere l'extravergine dagli oli raffinati o 'leggeri'.</p>"),
        ("Grassi monoinsaturi e cuore",
         "<p>Sostituire i grassi saturi (burro, salumi) con grassi monoinsaturi come l'acido oleico è associato a un profilo lipidico più favorevole. È uno dei meccanismi proposti per spiegare il legame tra olio d'oliva e salute cardiovascolare nelle popolazioni mediterranee.</p>"),
        ("Polifenoli e antiossidanti",
         "<p>I polifenoli dell'olio d'oliva hanno attività antiossidante e antinfiammatoria. L'<strong>oleocantale</strong>, responsabile del pizzicore in gola degli oli giovani, ha mostrato in vitro un effetto antinfiammatorio paragonabile, su piccola scala, all'ibuprofene. L'<strong>idrossitirosolo</strong> è alla base dell'unico claim salutistico UE autorizzato per l'olio d'oliva.</p>"),
        ("La prova della dieta mediterranea",
         "<p>Il beneficio meglio documentato non riguarda l'olio d'oliva isolato ma la <strong>dieta mediterranea</strong> nel suo insieme. Lo studio controllato PREDIMED ha seguito migliaia di persone a rischio: chi seguiva una dieta mediterranea con olio extravergine ha avuto meno eventi cardiovascolari maggiori del gruppo di controllo. L'olio vi gioca un ruolo centrale, ma insieme a verdure, legumi, pesce e frutta secca.</p>"),
        ("Come ottenere i benefici",
         "<p>Per i polifenoli, scegli un <strong>olio extravergine</strong> di qualità, recente e ben conservato (al riparo da luce e calore), e usane una parte <strong>a crudo</strong> (condimenti, filo di finitura). Circa 2 cucchiai al giorno rientrano bene in una dieta equilibrata. L'olio d'oliva non è un farmaco: agisce nel tempo, in una dieta complessivamente sana.</p>"),
    ],
    faqs=[
        ("Quali sono i benefici dell'olio extravergine d'oliva?",
         "Fornisce acido oleico (grasso monoinsaturo) e polifenoli antiossidanti. Nella dieta mediterranea la ricerca lo associa a una migliore salute cardiovascolare e alla protezione dei lipidi del sangue dall'ossidazione."),
        ("L'olio d'oliva fa bene?",
         "Sì, in una dieta equilibrata. È fonte di grassi buoni e antiossidanti, meglio se usato per sostituire i grassi saturi piuttosto che aggiungere calorie."),
        ("Quanto olio d'oliva al giorno?",
         "Circa 2 cucchiai al giorno si integrano bene in una dieta equilibrata. Il claim UE si basa su 20 g di olio ricco di polifenoli al giorno. Con moderazione: un cucchiaio è circa 120 kcal."),
        ("Extravergine o raffinato per la salute?",
         "Meglio l'extravergine: la raffinazione distrugge gran parte dei polifenoli, la frazione che porta la maggior parte degli effetti antiossidanti."),
        ("Bisogna consumarlo a crudo?",
         "In parte sì. La cottura degrada gradualmente alcuni polifenoli; tenere un filo a crudo per la finitura preserva meglio aroma e composti antiossidanti."),
    ],
)
H["el"] = dict(
    title="Έξτρα παρθένο ελαιόλαδο και υγεία: πραγματικά οφέλη, στοιχεία και δόση",
    desc="Τι λέει πραγματικά η επιστήμη για τα οφέλη του έξτρα παρθένου ελαιόλαδου: ελαϊκό οξύ, πολυφαινόλες (υδροξυτυροσόλη, ελαιοκανθάλη), μεσογειακή διατροφή, ισχυρισμός υγείας ΕΕ και χρήσιμη δόση.",
    h1="Έξτρα παρθένο ελαιόλαδο και υγεία: τι δείχνουν τα στοιχεία",
    lede="Το έξτρα παρθένο ελαιόλαδο βρίσκεται στον πυρήνα της μεσογειακής διατροφής. Δείτε, χωρίς υπερβολές, τι τεκμηριώνει η έρευνα για τα οφέλη του, χάρη σε ποιες ενώσεις και πώς να τα αξιοποιήσετε καθημερινά.",
    section="health", datePublished="2026-05-04", disclaimer=DISC["el"],
    keywords="οφέλη ελαιόλαδου, έξτρα παρθένο ελαιόλαδο υγεία, πολυφαινόλες ελαιόλαδου, ελαϊκό οξύ, μεσογειακή διατροφή",
    intro="Στο ελαιόλαδο αποδίδονται πολλές αρετές. Κάποιες είναι καλά τεκμηριωμένες, άλλες είναι μάρκετινγκ. Το άρθρο ξεχωρίζει: τι είναι τεκμηριωμένο, τι πιθανό και τι παραμένει αβέβαιο — με τις υπεύθυνες ενώσεις και ρεαλιστική δόση.",
    key_facts=[
        "Το έξτρα παρθένο ελαιόλαδο είναι πλούσιο σε ελαϊκό οξύ (μονοακόρεστο λίπος) και αντιοξειδωτικές πολυφαινόλες.",
        "Η ΕΕ επιτρέπει ισχυρισμό υγείας: οι πολυφαινόλες του ελαιόλαδου βοηθούν στην προστασία των λιπιδίων του αίματος από την οξείδωση (όφελος με 5 mg υδροξυτυροσόλης ανά 20 g ελαιόλαδου ημερησίως).",
        "Η κλινική μελέτη PREDIMED συνέδεσε μεσογειακή διατροφή με έξτρα παρθένο ελαιόλαδο με λιγότερα καρδιαγγειακά συμβάντα.",
        "Μία κουταλιά δίνει ~120 kcal: το ελαιόλαδο είναι ωφέλιμο αλλά θερμιδικό.",
    ],
    sections=[
        ("Τι κάνει διαφορετικό το έξτρα παρθένο ελαιόλαδο",
         "<p>Το έξτρα παρθένο ελαιόλαδο είναι ένας λιπαρός χυμός φρούτου, εκχυλισμένος εν ψυχρώ και μη ραφιναρισμένος. Διατηρεί δύο χρήσιμες οικογένειες ενώσεων: κυρίως <strong>ελαϊκό οξύ</strong> (μονοακόρεστο λίπος) και <strong>πολυφαινόλες</strong> (υδροξυτυροσόλη, τυροσόλη, ελευρωπαΐνη, ελαιοκανθάλη) που η ραφινάρισμα καταστρέφει σε μεγάλο βαθμό.</p>"),
        ("Μονοακόρεστα λίπη και καρδιά",
         "<p>Η αντικατάσταση κορεσμένων λιπών (βούτυρο, αλλαντικά) με μονοακόρεστα όπως το ελαϊκό οξύ συνδέεται με ευνοϊκότερο λιπιδικό προφίλ. Είναι ένας από τους προτεινόμενους μηχανισμούς για τη σχέση ελαιόλαδου και καρδιαγγειακής υγείας στους μεσογειακούς πληθυσμούς.</p>"),
        ("Πολυφαινόλες και αντιοξειδωτικά",
         "<p>Οι πολυφαινόλες του ελαιόλαδου έχουν αντιοξειδωτική και αντιφλεγμονώδη δράση. Η <strong>ελαιοκανθάλη</strong>, υπεύθυνη για το κάψιμο στον λαιμό των νεαρών ελαιόλαδων, έδειξε in vitro αντιφλεγμονώδη δράση συγκρίσιμη, σε μικρή κλίμακα, με την ιβουπροφαίνη. Η <strong>υδροξυτυροσόλη</strong> στηρίζει τον μόνο εγκεκριμένο ισχυρισμό υγείας της ΕΕ για το ελαιόλαδο.</p>"),
        ("Η απόδειξη της μεσογειακής διατροφής",
         "<p>Το καλύτερα τεκμηριωμένο όφελος δεν αφορά το ελαιόλαδο μόνο του αλλά τη <strong>μεσογειακή διατροφή</strong> συνολικά. Η ελεγχόμενη μελέτη PREDIMED παρακολούθησε χιλιάδες άτομα σε κίνδυνο: όσοι ακολουθούσαν μεσογειακή διατροφή με έξτρα παρθένο ελαιόλαδο είχαν λιγότερα μείζονα καρδιαγγειακά συμβάντα από την ομάδα ελέγχου.</p>"),
        ("Πώς να αποκομίσετε τα οφέλη",
         "<p>Για τις πολυφαινόλες, επιλέξτε ποιοτικό <strong>έξτρα παρθένο ελαιόλαδο</strong>, πρόσφατο και καλά αποθηκευμένο (μακριά από φως και θερμότητα), και χρησιμοποιήστε μέρος του <strong>ωμό</strong> (ντρέσινγκ, τελείωμα). Περίπου 2 κουταλιές τη μέρα ταιριάζουν σε ισορροπημένη διατροφή. Το ελαιόλαδο δεν είναι φάρμακο.</p>"),
    ],
    faqs=[
        ("Ποια είναι τα οφέλη του έξτρα παρθένου ελαιόλαδου;",
         "Παρέχει ελαϊκό οξύ (μονοακόρεστο λίπος) και αντιοξειδωτικές πολυφαινόλες. Στο πλαίσιο της μεσογειακής διατροφής η έρευνα το συνδέει με καλύτερη καρδιαγγειακή υγεία και προστασία των λιπιδίων του αίματος από την οξείδωση."),
        ("Κάνει καλό το ελαιόλαδο;",
         "Ναι, σε ισορροπημένη διατροφή. Είναι πηγή καλών λιπών και αντιοξειδωτικών, ιδανικά ως αντικατάσταση κορεσμένων λιπών παρά ως επιπλέον θερμίδες."),
        ("Πόσο ελαιόλαδο την ημέρα;",
         "Περίπου 2 κουταλιές τη μέρα ταιριάζουν σε ισορροπημένη διατροφή. Ο ισχυρισμός της ΕΕ βασίζεται σε 20 g πλούσιου σε πολυφαινόλες ελαιόλαδου. Με μέτρο: μια κουταλιά είναι ~120 kcal."),
        ("Έξτρα παρθένο ή ραφιναρισμένο για την υγεία;",
         "Προτιμότερο το έξτρα παρθένο: η ραφινάρισμα καταστρέφει μεγάλο μέρος των πολυφαινολών, της ένωσης που φέρει τα αντιοξειδωτικά οφέλη."),
        ("Πρέπει να καταναλώνεται ωμό;",
         "Εν μέρει ναι. Το μαγείρεμα υποβαθμίζει σταδιακά κάποιες πολυφαινόλες· ένα ωμό τελείωμα διατηρεί καλύτερα άρωμα και αντιοξειδωτικά."),
    ],
)

# ================================================================= COOKING ====
K = {}
K["fr"] = dict(
    title="Cuisiner à l'huile d'olive extra vierge : peut-on la chauffer et la faire frire ?",
    desc="Peut-on cuisiner et frire à l'huile d'olive extra vierge ? Point de fumée, stabilité, mythes, différence avec l'huile d'olive raffinée et bons usages en cuisine.",
    h1="Cuisiner à l'huile d'olive extra vierge : chaleur, friture et mythes",
    lede="Faut-il réserver l'huile d'olive extra vierge au cru ? Non. Voici ce que dit la science sur sa stabilité à la chaleur, la friture, et quand préférer une huile d'olive raffinée.",
    section="cooking", datePublished="2026-05-04", disclaimer=None,
    keywords="cuisiner huile d'olive, frire huile d'olive, huile d'olive extra vierge cuisson, point de fumée, huile d'olive vs extra vierge",
    intro="« On ne cuisine pas à l'huile d'olive extra vierge » : c'est l'un des mythes les plus tenaces de la cuisine. En réalité, l'huile d'olive extra vierge est l'une des matières grasses les plus stables à la chaleur. Voici pourquoi, et comment l'utiliser au mieux.",
    key_facts=[
        "Le point de fumée de l'huile d'olive extra vierge se situe vers 190–210 °C, adapté à la plupart des cuissons domestiques.",
        "Ses graisses mono-insaturées et ses antioxydants la rendent stable à la chaleur, souvent plus qu'on ne le croit.",
        "Pour une friture profonde et répétée à très haute température, une huile d'olive raffinée (point de fumée plus élevé) peut être plus économique.",
        "Les polyphénols se dégradent en partie à la cuisson : gardez un filet cru pour la finition.",
    ],
    sections=[
        ("Le mythe du point de fumée",
         "<p>On entend souvent qu'il ne faut pas chauffer l'huile d'olive extra vierge. Son point de fumée (≈ 190–210 °C selon la qualité) couvre pourtant la <strong>grande majorité des cuissons domestiques</strong> : revenu, sauté, rôti, poêlé, friture peu profonde. Ce qui compte autant que le point de fumée, c'est la <strong>stabilité oxydative</strong> de l'huile — et là, l'huile d'olive est excellente.</p>"),
        ("Pourquoi elle est stable à la chaleur",
         "<p>Deux raisons : une majorité d'acide oléique (une graisse mono-insaturée peu sensible à l'oxydation) et une richesse en antioxydants naturels (polyphénols, vitamine E) qui protègent l'huile pendant la cuisson. Des études sur la friture montrent que l'huile d'olive extra vierge résiste bien, souvent mieux que des huiles plus raffinées mais pauvres en antioxydants.</p>"),
        ("Friture : oui, mais avec discernement",
         "<p>On peut frire à l'huile d'olive extra vierge : elle donne du goût et tient la chaleur. L'inconvénient est le <strong>coût</strong> pour de gros volumes, et un parfum marqué qui ne convient pas à tous les plats. Pour une friture profonde, répétée et à très haute température, une <strong>huile d'olive raffinée</strong> (dite simplement « huile d'olive ») ou une huile neutre au point de fumée plus élevé peut être plus pratique.</p>"),
        ("Extra vierge, raffinée ou « légère » ?",
         "<p>L'« huile d'olive » (sans mention « vierge ») et l'huile d'olive « légère » sont des huiles <strong>raffinées</strong>, au goût neutre et sans polyphénols : pratiques pour une cuisson neutre à haute température, mais sans les bénéfices de l'extra vierge. L'<strong>extra vierge</strong> apporte goût, antioxydants et stabilité : c'est le meilleur choix pour la plupart des cuissons et pour tout usage à cru.</p>"),
        ("Les bons usages en cuisine",
         "<p>Utilisez l'extra vierge pour revenir légumes et aromates, rôtir, poêler, confire à basse température, et surtout <strong>à cru</strong> : vinaigrettes, filet de finition sur un plat chaud, tartines. Réservez une huile plus neutre ou raffinée aux fritures profondes et aux préparations où le goût d'olive n'est pas souhaité.</p>"),
    ],
    faqs=[
        ("Peut-on cuisiner avec de l'huile d'olive extra vierge ?",
         "Oui. Son point de fumée (≈ 190–210 °C) et sa stabilité couvrent la plupart des cuissons domestiques : sauté, rôti, poêlé, friture peu profonde. C'est un mythe de croire qu'elle doit rester crue."),
        ("Peut-on frire à l'huile d'olive ?",
         "Oui, l'huile d'olive extra vierge résiste bien à la friture grâce à ses antioxydants. Pour de gros volumes ou une friture très répétée à haute température, une huile d'olive raffinée peut être plus économique."),
        ("Quelle différence entre huile d'olive et extra vierge en cuisine ?",
         "L'extra vierge est non raffinée : elle apporte goût, polyphénols et une bonne stabilité. L'« huile d'olive » simple est raffinée, neutre et sans polyphénols, pratique pour une cuisson à haute température sans goût d'olive."),
        ("La chaleur détruit-elle les bienfaits de l'huile d'olive ?",
         "Elle dégrade progressivement une partie des polyphénols, mais l'huile reste une bonne source de graisses mono-insaturées. Pour préserver au mieux les antioxydants, gardez un filet cru en finition."),
        ("Quelle huile d'olive pour la friture ?",
         "L'extra vierge convient pour une friture occasionnelle et parfumée. Pour la friture profonde et fréquente, une huile d'olive raffinée au point de fumée plus élevé est plus pratique et économique."),
    ],
)
K["en"] = dict(
    title="Cooking with Extra Virgin Olive Oil: can you heat it and fry with it?",
    desc="Can you cook and fry with extra virgin olive oil? Smoke point, stability, myths, the difference from refined olive oil, and the best culinary uses.",
    h1="Cooking with Extra Virgin Olive Oil: heat, frying and myths",
    lede="Should extra virgin olive oil be kept for raw use only? No. Here's what science says about its heat stability, frying, and when to reach for a refined olive oil.",
    section="cooking", datePublished="2026-05-04", disclaimer=None,
    keywords="cooking with olive oil, frying olive oil, extra virgin olive oil cooking, smoke point, olive oil vs extra virgin",
    intro="'You can't cook with extra virgin olive oil' is one of the most stubborn kitchen myths. In reality, extra virgin olive oil is one of the most heat-stable cooking fats. Here's why, and how to use it best.",
    key_facts=[
        "Extra virgin olive oil's smoke point is around 190–210 °C, suitable for most home cooking.",
        "Its monounsaturated fat and antioxidants make it heat-stable, often more than people think.",
        "For deep, repeated frying at very high heat, a refined olive oil (higher smoke point) can be more economical.",
        "Polyphenols partly degrade with cooking: keep a raw drizzle for finishing.",
    ],
    sections=[
        ("The smoke-point myth",
         "<p>You often hear that extra virgin olive oil shouldn't be heated. Yet its smoke point (≈ 190–210 °C depending on quality) covers the <strong>vast majority of home cooking</strong>: sautéing, stir-frying, roasting, pan-frying, shallow frying. What matters as much as smoke point is the oil's <strong>oxidative stability</strong> — and here olive oil excels.</p>"),
        ("Why it's heat-stable",
         "<p>Two reasons: mostly oleic acid (a monounsaturated fat resistant to oxidation) and an abundance of natural antioxidants (polyphenols, vitamin E) that protect the oil during cooking. Frying studies show extra virgin olive oil holds up well, often better than more refined oils that lack antioxidants.</p>"),
        ("Frying: yes, but wisely",
         "<p>You can fry in extra virgin olive oil: it adds flavour and holds heat. The downsides are <strong>cost</strong> in large volumes and a pronounced flavour that doesn't suit every dish. For deep, repeated, very-high-heat frying, a <strong>refined olive oil</strong> (labelled simply 'olive oil') or a neutral high-smoke-point oil can be more practical.</p>"),
        ("Extra virgin, refined or 'light'?",
         "<p>'Olive oil' (without 'virgin') and 'light' olive oil are <strong>refined</strong> oils, neutral in taste and without polyphenols: handy for neutral high-heat cooking, but without the benefits of extra virgin. <strong>Extra virgin</strong> brings flavour, antioxidants and stability: the best choice for most cooking and all raw uses.</p>"),
        ("The best culinary uses",
         "<p>Use extra virgin to sauté vegetables and aromatics, roast, pan-fry, confit at low temperature, and above all <strong>raw</strong>: dressings, a finishing drizzle on a hot dish, toast. Reserve a more neutral or refined oil for deep frying and preparations where an olive flavour isn't wanted.</p>"),
    ],
    faqs=[
        ("Can you cook with extra virgin olive oil?",
         "Yes. Its smoke point (≈ 190–210 °C) and stability cover most home cooking: sautéing, roasting, pan-frying, shallow frying. It's a myth that it must stay raw."),
        ("Can you fry with olive oil?",
         "Yes, extra virgin olive oil holds up well to frying thanks to its antioxidants. For large volumes or very repeated high-heat frying, a refined olive oil can be more economical."),
        ("What's the difference between olive oil and extra virgin in cooking?",
         "Extra virgin is unrefined: it brings flavour, polyphenols and good stability. Plain 'olive oil' is refined, neutral and without polyphenols, handy for high-heat cooking without an olive taste."),
        ("Does heat destroy olive oil's benefits?",
         "It gradually degrades some polyphenols, but the oil remains a good source of monounsaturated fat. To best preserve antioxidants, keep a raw drizzle for finishing."),
        ("Which olive oil for frying?",
         "Extra virgin works for occasional, flavourful frying. For deep, frequent frying, a refined olive oil with a higher smoke point is more practical and economical."),
    ],
)
K["it"] = dict(
    title="Cucinare con olio extravergine d'oliva: si può scaldare e friggere?",
    desc="Si può cucinare e friggere con l'olio extravergine d'oliva? Punto di fumo, stabilità, miti, differenza con l'olio d'oliva raffinato e usi migliori in cucina.",
    h1="Cucinare con olio extravergine d'oliva: calore, frittura e miti",
    lede="L'olio extravergine va tenuto solo per il crudo? No. Ecco cosa dice la scienza sulla sua stabilità al calore, sulla frittura e su quando preferire un olio d'oliva raffinato.",
    section="cooking", datePublished="2026-05-04", disclaimer=None,
    keywords="cucinare con olio d'oliva, friggere olio d'oliva, olio extravergine cottura, punto di fumo, olio d'oliva vs extravergine",
    intro="'Non si cucina con l'extravergine' è uno dei miti più duri a morire. In realtà l'olio extravergine d'oliva è uno dei grassi da cucina più stabili al calore. Ecco perché e come usarlo al meglio.",
    key_facts=[
        "Il punto di fumo dell'extravergine è circa 190–210 °C, adatto alla maggior parte delle cotture domestiche.",
        "Grassi monoinsaturi e antiossidanti lo rendono stabile al calore, spesso più di quanto si creda.",
        "Per frittura profonda e ripetuta ad altissima temperatura, un olio d'oliva raffinato (punto di fumo più alto) può essere più economico.",
        "I polifenoli si degradano in parte con la cottura: tieni un filo a crudo per la finitura.",
    ],
    sections=[
        ("Il mito del punto di fumo",
         "<p>Si sente spesso che l'extravergine non va scaldato. Eppure il suo punto di fumo (≈ 190–210 °C secondo la qualità) copre la <strong>gran parte delle cotture domestiche</strong>: soffritto, saltato, arrosto, in padella, frittura poco profonda. Conta quanto il punto di fumo anche la <strong>stabilità ossidativa</strong> — e qui l'olio d'oliva eccelle.</p>"),
        ("Perché è stabile al calore",
         "<p>Due ragioni: soprattutto acido oleico (grasso monoinsaturo poco sensibile all'ossidazione) e ricchezza di antiossidanti naturali (polifenoli, vitamina E) che proteggono l'olio in cottura. Studi sulla frittura mostrano che l'extravergine regge bene, spesso meglio di oli più raffinati ma poveri di antiossidanti.</p>"),
        ("Frittura: sì, ma con criterio",
         "<p>Si può friggere con l'extravergine: dà gusto e regge il calore. Gli svantaggi sono il <strong>costo</strong> per grandi volumi e un aroma marcato non adatto a tutti i piatti. Per frittura profonda, ripetuta e ad altissima temperatura, un <strong>olio d'oliva raffinato</strong> o un olio neutro con punto di fumo più alto può essere più pratico.</p>"),
        ("Extravergine, raffinato o 'leggero'?",
         "<p>L'«olio d'oliva» (senza 'vergine') e l'olio 'leggero' sono oli <strong>raffinati</strong>, dal gusto neutro e senza polifenoli: comodi per cotture neutre ad alta temperatura, ma senza i benefici dell'extravergine. L'<strong>extravergine</strong> porta gusto, antiossidanti e stabilità: la scelta migliore per gran parte delle cotture e per il crudo.</p>"),
        ("Gli usi migliori in cucina",
         "<p>Usa l'extravergine per soffritti, arrosti, padella, confit a bassa temperatura e soprattutto <strong>a crudo</strong>: condimenti, filo di finitura su un piatto caldo, bruschette. Riserva un olio più neutro o raffinato alle fritture profonde e alle preparazioni senza gusto d'oliva.</p>"),
    ],
    faqs=[
        ("Si può cucinare con l'olio extravergine d'oliva?",
         "Sì. Il punto di fumo (≈ 190–210 °C) e la stabilità coprono gran parte delle cotture domestiche. È un mito che debba restare crudo."),
        ("Si può friggere con l'olio d'oliva?",
         "Sì, l'extravergine regge bene la frittura grazie agli antiossidanti. Per grandi volumi o frittura molto ripetuta ad alta temperatura, un olio raffinato può essere più economico."),
        ("Differenza tra olio d'oliva ed extravergine in cucina?",
         "L'extravergine è non raffinato: porta gusto, polifenoli e buona stabilità. L'«olio d'oliva» semplice è raffinato, neutro e senza polifenoli, comodo per alte temperature senza gusto d'oliva."),
        ("Il calore distrugge i benefici dell'olio d'oliva?",
         "Degrada gradualmente parte dei polifenoli, ma l'olio resta una buona fonte di grassi monoinsaturi. Per preservare gli antiossidanti, tieni un filo a crudo."),
        ("Quale olio d'oliva per friggere?",
         "L'extravergine va bene per fritture occasionali e saporite. Per frittura profonda e frequente, un olio raffinato con punto di fumo più alto è più pratico."),
    ],
)
K["el"] = dict(
    title="Μαγείρεμα με έξτρα παρθένο ελαιόλαδο: ζεσταίνεται και τηγανίζει;",
    desc="Μαγειρεύεται και τηγανίζεται το έξτρα παρθένο ελαιόλαδο; Σημείο καπνού, σταθερότητα, μύθοι, διαφορά με το ραφιναρισμένο και καλύτερες χρήσεις στην κουζίνα.",
    h1="Μαγείρεμα με έξτρα παρθένο ελαιόλαδο: θερμότητα, τηγάνισμα και μύθοι",
    lede="Πρέπει το έξτρα παρθένο ελαιόλαδο να μένει μόνο για ωμή χρήση; Όχι. Δείτε τι λέει η επιστήμη για τη σταθερότητά του στη θερμότητα, το τηγάνισμα και πότε να προτιμήσετε ραφιναρισμένο ελαιόλαδο.",
    section="cooking", datePublished="2026-05-04", disclaimer=None,
    keywords="μαγείρεμα με ελαιόλαδο, τηγάνισμα ελαιόλαδο, έξτρα παρθένο ελαιόλαδο μαγείρεμα, σημείο καπνού, ελαιόλαδο vs έξτρα παρθένο",
    intro="«Δεν μαγειρεύεις με έξτρα παρθένο» είναι ένας από τους πιο επίμονους μύθους της κουζίνας. Στην πραγματικότητα, το έξτρα παρθένο ελαιόλαδο είναι από τα πιο σταθερά στη θερμότητα λιπαρά. Δείτε γιατί και πώς να το χρησιμοποιείτε καλύτερα.",
    key_facts=[
        "Το σημείο καπνού του έξτρα παρθένου είναι περίπου 190–210 °C, κατάλληλο για τις περισσότερες οικιακές μαγειρικές.",
        "Τα μονοακόρεστα λίπη και τα αντιοξειδωτικά το κάνουν σταθερό στη θερμότητα, συχνά πιο πολύ απ' ό,τι νομίζουμε.",
        "Για βαθύ, επαναλαμβανόμενο τηγάνισμα σε πολύ υψηλή θερμοκρασία, ένα ραφιναρισμένο ελαιόλαδο μπορεί να είναι πιο οικονομικό.",
        "Οι πολυφαινόλες υποβαθμίζονται εν μέρει στο μαγείρεμα: κρατήστε λίγο ωμό για το τελείωμα.",
    ],
    sections=[
        ("Ο μύθος του σημείου καπνού",
         "<p>Ακούμε συχνά ότι το έξτρα παρθένο δεν πρέπει να ζεσταίνεται. Όμως το σημείο καπνού του (≈ 190–210 °C) καλύπτει τη <strong>μεγάλη πλειονότητα των οικιακών μαγειρικών</strong>: σοτάρισμα, ψήσιμο, τηγάνισμα ρηχό. Εξίσου σημαντική είναι η <strong>οξειδωτική σταθερότητα</strong> — και εδώ το ελαιόλαδο υπερέχει.</p>"),
        ("Γιατί είναι σταθερό στη θερμότητα",
         "<p>Δύο λόγοι: κυρίως ελαϊκό οξύ (μονοακόρεστο, ανθεκτικό στην οξείδωση) και πλήθος φυσικών αντιοξειδωτικών (πολυφαινόλες, βιταμίνη E) που προστατεύουν το λάδι στο μαγείρεμα. Μελέτες τηγανίσματος δείχνουν ότι το έξτρα παρθένο αντέχει καλά, συχνά καλύτερα από ραφιναρισμένα λάδια φτωχά σε αντιοξειδωτικά.</p>"),
        ("Τηγάνισμα: ναι, αλλά με κρίση",
         "<p>Μπορείτε να τηγανίσετε με έξτρα παρθένο: δίνει γεύση και αντέχει τη θερμότητα. Τα μειονεκτήματα είναι το <strong>κόστος</strong> σε μεγάλες ποσότητες και μια έντονη γεύση που δεν ταιριάζει παντού. Για βαθύ, επαναλαμβανόμενο τηγάνισμα, ένα <strong>ραφιναρισμένο ελαιόλαδο</strong> ή ουδέτερο λάδι με υψηλότερο σημείο καπνού είναι πιο πρακτικό.</p>"),
        ("Έξτρα παρθένο, ραφιναρισμένο ή 'ελαφρύ';",
         "<p>Το «ελαιόλαδο» (χωρίς 'παρθένο') και το 'ελαφρύ' είναι <strong>ραφιναρισμένα</strong> λάδια, ουδέτερα και χωρίς πολυφαινόλες: βολικά για ουδέτερο μαγείρεμα σε υψηλή θερμοκρασία, χωρίς όμως τα οφέλη του έξτρα παρθένου. Το <strong>έξτρα παρθένο</strong> δίνει γεύση, αντιοξειδωτικά και σταθερότητα.</p>"),
        ("Οι καλύτερες χρήσεις στην κουζίνα",
         "<p>Χρησιμοποιήστε το έξτρα παρθένο για σοτάρισμα, ψήσιμο, κομφί σε χαμηλή θερμοκρασία και κυρίως <strong>ωμό</strong>: ντρέσινγκ, τελείωμα σε ζεστό πιάτο, ψωμί. Κρατήστε ένα πιο ουδέτερο ή ραφιναρισμένο λάδι για βαθύ τηγάνισμα.</p>"),
    ],
    faqs=[
        ("Μαγειρεύεται το έξτρα παρθένο ελαιόλαδο;",
         "Ναι. Το σημείο καπνού (≈ 190–210 °C) και η σταθερότητα καλύπτουν τις περισσότερες οικιακές μαγειρικές. Είναι μύθος ότι πρέπει να μένει ωμό."),
        ("Τηγανίζεται το ελαιόλαδο;",
         "Ναι, το έξτρα παρθένο αντέχει καλά χάρη στα αντιοξειδωτικά. Για μεγάλες ποσότητες ή πολύ επαναλαμβανόμενο τηγάνισμα, ένα ραφιναρισμένο ελαιόλαδο μπορεί να είναι πιο οικονομικό."),
        ("Διαφορά ελαιόλαδου και έξτρα παρθένου στο μαγείρεμα;",
         "Το έξτρα παρθένο είναι μη ραφιναρισμένο: δίνει γεύση, πολυφαινόλες και καλή σταθερότητα. Το απλό «ελαιόλαδο» είναι ραφιναρισμένο, ουδέτερο και χωρίς πολυφαινόλες."),
        ("Καταστρέφει η θερμότητα τα οφέλη;",
         "Υποβαθμίζει σταδιακά κάποιες πολυφαινόλες, αλλά το λάδι παραμένει καλή πηγή μονοακόρεστων. Για τα αντιοξειδωτικά, κρατήστε λίγο ωμό στο τελείωμα."),
        ("Ποιο ελαιόλαδο για τηγάνισμα;",
         "Το έξτρα παρθένο για περιστασιακό, γευστικό τηγάνισμα. Για βαθύ, συχνό τηγάνισμα, ένα ραφιναρισμένο με υψηλότερο σημείο καπνού είναι πιο πρακτικό."),
    ],
)

if __name__ == "__main__":
    print("Batch 3a:")
    write_guide_cluster("complete-guide-extra-virgin-olive-oil-for-health", H)
    write_guide_cluster("complete-guide-extra-virgin-olive-oil-in-cooking", K)
