# -*- coding: utf-8 -*-
"""Authentic Labneh with za'atar and olive oil x4 languages."""
from recipe_render import write_cluster

C = {}
C["fr"] = dict(
    title="Labneh maison au zaatar et huile d'olive : la recette facile",
    desc="Labneh maison : yaourt égoutté crémeux, servi avec un généreux filet d'huile d'olive et du zaatar. Méthode d'égouttage, temps, billes de labneh conservées dans l'huile.",
    h1="Labneh au zaatar et huile d'olive",
    lede="Le labneh est un yaourt égoutté, épais et crémeux, star des mezze du Moyen-Orient. Il ne demande que du yaourt, du sel et du temps — puis un généreux filet d'huile d'olive et une pincée de zaatar au moment de servir.",
    info="<strong>Préparation :</strong> 10 min · <strong>Égouttage :</strong> 12 à 24 h · <strong>Pour :</strong> 4 personnes · <strong>Cuisine :</strong> levantine · <strong>Difficulté :</strong> très facile",
    intro="Le labneh (ou labneh) est simplement du yaourt dont on a retiré le petit-lait pour le rendre dense et onctueux, entre le fromage frais et le yaourt grec très épais. Servi en dôme, creusé d'un puits d'huile d'olive et saupoudré de zaatar, c'est un mezze incontournable, à déguster avec du pain.",
    ingredients=[
        "500 g de yaourt nature entier (type grec ou brassé)",
        "1/2 c. à café de sel",
    ],
    garnish=[
        "Huile d'olive extra vierge (généreusement)",
        "1 à 2 c. à soupe de zaatar",
        "Pain pita ou pain plat, pour servir",
        "Facultatif : menthe fraîche, ail écrasé",
    ],
    steps=[
        "<strong>Saler le yaourt.</strong> Mélangez le yaourt avec le sel : le sel aide à extraire l'eau et à conserver le labneh.",
        "<strong>Égoutter.</strong> Tapissez une passoire d'une étamine (ou d'un torchon fin propre), versez-y le yaourt, refermez le tissu et posez sur un bol pour recueillir le petit-lait.",
        "<strong>Laisser reposer au frais.</strong> Placez au réfrigérateur 12 à 24 h. Plus l'égouttage est long, plus le labneh est ferme (jusqu'à pouvoir être roulé en billes).",
        "<strong>Dresser.</strong> Étalez le labneh dans une assiette creuse, lissez et creusez un puits au dos d'une cuillère.",
        "<strong>Finir à l'huile d'olive.</strong> Arrosez généreusement d'huile d'olive extra vierge et saupoudrez de zaatar. Servez frais avec du pain.",
    ],
    oil="Sur le labneh, l'huile d'olive n'est pas un détail : c'est elle qui lie la fraîcheur acidulée du yaourt et les herbes du zaatar. Utilisez une <strong>extra vierge fruitée</strong>, sans compter — un vrai puits d'huile — et gardez-en pour les billes de labneh conservées.",
    tips=[
        "Un yaourt entier donne un labneh plus onctueux ; l'allégé rend une texture plus sèche.",
        "Ne sautez pas le sel : il aide à l'égouttage et à la conservation.",
        "Égouttez plus longtemps (24-48 h) pour un labneh à rouler en billes.",
        "Gardez le petit-lait : il s'utilise dans les pâtes à pain, marinades ou smoothies.",
    ],
    variations=[
        "<strong>Billes de labneh :</strong> égouttez 48 h, roulez en billes, conservez dans un bocal recouvert d'huile d'olive (avec herbes).",
        "<strong>Aromatisé :</strong> incorporez ail écrasé, menthe ou zeste de citron au yaourt.",
        "<strong>Zaatar maison :</strong> thym séché, sumac, graines de sésame et sel.",
    ],
    serve="Servez le labneh en mezze avec du pain pita, des crudités et d'autres petits plats (houmous, olives, poivrons grillés). En version sucrée-salée, il accompagne aussi le miel et les fruits. Toujours avec un généreux filet d'huile d'olive.",
    store="Le labneh se conserve 4 à 5 jours au réfrigérateur dans un contenant hermétique. Les billes de labneh conservées dans l'huile d'olive se gardent plusieurs semaines au frais, entièrement recouvertes d'huile.",
    faqs=[
        ("Qu'est-ce que le labneh ?",
         "Le labneh est un yaourt égoutté, épais et crémeux, typique du Levant. On retire le petit-lait du yaourt pour obtenir une texture entre le yaourt grec très épais et le fromage frais, servie avec de l'huile d'olive et du zaatar."),
        ("Comment faire du labneh maison ?",
         "Mélangez du yaourt entier avec un peu de sel, versez dans une étamine posée sur une passoire, et laissez égoutter au réfrigérateur 12 à 24 h. Plus c'est long, plus c'est ferme."),
        ("Combien de temps faut-il égoutter le labneh ?",
         "12 à 24 h pour une texture à tartiner ; 48 h pour un labneh assez ferme pour être roulé en billes et conservé dans l'huile d'olive."),
        ("Qu'est-ce que le zaatar ?",
         "Le zaatar est un mélange d'épices du Moyen-Orient à base de thym séché, de sumac, de graines de sésame et de sel. Il se marie parfaitement au labneh et à l'huile d'olive."),
        ("Avec quoi manger le labneh ?",
         "Avec du pain pita ou plat, en mezze, avec des crudités, des olives et d'autres petits plats. On le sert toujours nappé d'huile d'olive et souvent de zaatar."),
    ],
    schema_name="Labneh au zaatar et huile d'olive",
    schema_desc="Labneh maison : yaourt égoutté crémeux servi avec un généreux filet d'huile d'olive extra vierge et du zaatar.",
    schema_ing=["500 g yaourt nature entier", "1/2 c. à café de sel", "huile d'olive extra vierge",
                "1-2 c. à soupe de zaatar", "pain pita"],
    schema_steps=[
        "Mélanger le yaourt avec le sel.",
        "Verser dans une étamine posée sur une passoire au-dessus d'un bol.",
        "Égoutter au réfrigérateur 12 à 24 h.",
        "Étaler dans une assiette et creuser un puits.",
        "Arroser généreusement d'huile d'olive et saupoudrer de zaatar."],
    keywords="labneh, labneh zaatar, recette labneh, labneh maison, yaourt égoutté huile d'olive",
    cuisine="Middle Eastern", category="Mezze", prep="PT10M", cook="PT0M", total="PT12H", yield_="4 servings",
    nutrition={"servingSize": "1 portion", "calories": "150 kcal", "fatContent": "11 g", "proteinContent": "7 g", "carbohydrateContent": "5 g"},
)
C["en"] = dict(
    title="Homemade Labneh with Za'atar and Olive Oil: the easy recipe",
    desc="Homemade labneh: creamy strained yogurt served with a generous drizzle of olive oil and za'atar. Straining method, timing, and labneh balls preserved in oil.",
    h1="Labneh with Za'atar and Olive Oil",
    lede="Labneh is strained yogurt — thick and creamy, a star of Middle Eastern mezze. It needs only yogurt, salt and time, then a generous pool of olive oil and a sprinkle of za'atar to serve.",
    info="<strong>Prep:</strong> 10 min · <strong>Straining:</strong> 12–24 h · <strong>Serves:</strong> 4 · <strong>Cuisine:</strong> Levantine · <strong>Difficulty:</strong> very easy",
    intro="Labneh is simply yogurt with the whey drained off to make it dense and silky, somewhere between fresh cheese and very thick Greek yogurt. Served in a swirl with a well of olive oil and a dusting of za'atar, it's an essential mezze, eaten with bread.",
    ingredients=[
        "500 g plain full-fat yogurt (Greek or natural)",
        "1/2 tsp salt",
    ],
    garnish=[
        "Extra virgin olive oil (generously)",
        "1–2 tbsp za'atar",
        "Pita or flatbread, to serve",
        "Optional: fresh mint, crushed garlic",
    ],
    steps=[
        "<strong>Salt the yogurt.</strong> Mix the yogurt with the salt: salt helps draw out water and preserves the labneh.",
        "<strong>Strain.</strong> Line a sieve with cheesecloth (or a clean thin cloth), pour in the yogurt, fold the cloth over and set over a bowl to catch the whey.",
        "<strong>Chill and drain.</strong> Refrigerate 12–24 h. The longer it strains, the firmer the labneh (up to firm enough to roll into balls).",
        "<strong>Plate.</strong> Spread the labneh in a shallow bowl, smooth it and make a well with the back of a spoon.",
        "<strong>Finish with olive oil.</strong> Drizzle generously with extra virgin olive oil and sprinkle with za'atar. Serve cool with bread.",
    ],
    oil="On labneh, olive oil is no afterthought: it links the tangy freshness of the yogurt with the herbs of the za'atar. Use a <strong>fruity extra virgin</strong>, without stinting — a real pool of oil — and keep some for preserved labneh balls.",
    tips=[
        "Full-fat yogurt gives creamier labneh; low-fat turns out drier.",
        "Don't skip the salt: it aids draining and preservation.",
        "Strain longer (24–48 h) for labneh you can roll into balls.",
        "Keep the whey: use it in bread doughs, marinades or smoothies.",
    ],
    variations=[
        "<strong>Labneh balls:</strong> strain 48 h, roll into balls, keep in a jar covered with olive oil (with herbs).",
        "<strong>Flavoured:</strong> stir crushed garlic, mint or lemon zest into the yogurt.",
        "<strong>Homemade za'atar:</strong> dried thyme, sumac, sesame seeds and salt.",
    ],
    serve="Serve labneh as a mezze with pita, crudités and other small plates (hummus, olives, grilled peppers). Sweet-savoury, it also pairs with honey and fruit. Always with a generous drizzle of olive oil.",
    store="Labneh keeps 4–5 days in the fridge in an airtight container. Labneh balls preserved in olive oil last several weeks refrigerated, fully covered with oil.",
    faqs=[
        ("What is labneh?",
         "Labneh is strained yogurt — thick and creamy, typical of the Levant. The whey is drained from yogurt to give a texture between very thick Greek yogurt and fresh cheese, served with olive oil and za'atar."),
        ("How do you make labneh at home?",
         "Mix full-fat yogurt with a little salt, pour into cheesecloth set over a sieve, and let it drain in the fridge for 12–24 h. The longer, the firmer."),
        ("How long should you strain labneh?",
         "12–24 h for a spreadable texture; 48 h for labneh firm enough to roll into balls and preserve in olive oil."),
        ("What is za'atar?",
         "Za'atar is a Middle Eastern spice blend of dried thyme, sumac, sesame seeds and salt. It pairs perfectly with labneh and olive oil."),
        ("What do you eat labneh with?",
         "With pita or flatbread, as a mezze, with crudités, olives and other small plates. It's always served drizzled with olive oil and often za'atar."),
    ],
    schema_name="Labneh with Za'atar and Olive Oil",
    schema_desc="Homemade labneh: creamy strained yogurt served with a generous drizzle of extra virgin olive oil and za'atar.",
    schema_ing=["500 g plain full-fat yogurt", "1/2 tsp salt", "extra virgin olive oil",
                "1-2 tbsp za'atar", "pita bread"],
    schema_steps=[
        "Mix the yogurt with the salt.",
        "Pour into cheesecloth set over a sieve above a bowl.",
        "Strain in the fridge 12-24 h.",
        "Spread in a bowl and make a well.",
        "Drizzle generously with olive oil and sprinkle with za'atar."],
    keywords="labneh, labneh zaatar, labneh recipe, homemade labneh, strained yogurt olive oil",
    cuisine="Middle Eastern", category="Mezze", prep="PT10M", cook="PT0M", total="PT12H", yield_="4 servings",
    nutrition={"servingSize": "1 serving", "calories": "150 kcal", "fatContent": "11 g", "proteinContent": "7 g", "carbohydrateContent": "5 g"},
)
C["it"] = dict(
    title="Labneh fatto in casa con za'atar e olio d'oliva: la ricetta facile",
    desc="Labneh fatto in casa: yogurt colato cremoso servito con un generoso filo d'olio d'oliva e za'atar. Metodo di colatura, tempi e palline di labneh sott'olio.",
    h1="Labneh con za'atar e olio d'oliva",
    lede="Il labneh è yogurt colato — denso e cremoso, star dei mezze mediorientali. Servono solo yogurt, sale e tempo, poi un generoso lago d'olio d'oliva e una spolverata di za'atar.",
    info="<strong>Preparazione:</strong> 10 min · <strong>Colatura:</strong> 12–24 h · <strong>Per:</strong> 4 persone · <strong>Cucina:</strong> levantina · <strong>Difficoltà:</strong> molto facile",
    intro="Il labneh è semplicemente yogurt privato del siero per renderlo denso e vellutato, tra il formaggio fresco e lo yogurt greco molto denso. Servito con un pozzo d'olio d'oliva e za'atar, è un mezze immancabile, da gustare con il pane.",
    ingredients=[
        "500 g di yogurt bianco intero (greco o naturale)",
        "1/2 cucchiaino di sale",
    ],
    garnish=[
        "Olio extravergine d'oliva (generosamente)",
        "1–2 cucchiai di za'atar",
        "Pane pita o pane piatto, per servire",
        "Facoltativo: menta fresca, aglio schiacciato",
    ],
    steps=[
        "<strong>Salare lo yogurt.</strong> Mescola lo yogurt con il sale: il sale aiuta a estrarre l'acqua e a conservare il labneh.",
        "<strong>Colare.</strong> Fodera un colino con una garza (o un panno sottile pulito), versa lo yogurt, chiudi il panno e appoggia su una ciotola per raccogliere il siero.",
        "<strong>Riposare al fresco.</strong> Metti in frigo 12–24 h. Più lunga è la colatura, più fermo è il labneh (fino a poterlo arrotolare in palline).",
        "<strong>Impiattare.</strong> Stendi il labneh in una ciotola bassa, liscia e crea un pozzo con il dorso di un cucchiaio.",
        "<strong>Finire con l'olio.</strong> Condisci generosamente con olio extravergine e spolvera di za'atar. Servi fresco con il pane.",
    ],
    oil="Sul labneh l'olio d'oliva non è un dettaglio: lega la freschezza acidula dello yogurt con le erbe dello za'atar. Usa un <strong>extravergine fruttato</strong>, senza risparmiare — un vero pozzo d'olio — e tienine per le palline sott'olio.",
    tips=[
        "Lo yogurt intero dà un labneh più cremoso; il magro risulta più asciutto.",
        "Non saltare il sale: aiuta colatura e conservazione.",
        "Cola più a lungo (24–48 h) per un labneh da arrotolare in palline.",
        "Conserva il siero: si usa in impasti da pane, marinate o smoothie.",
    ],
    variations=[
        "<strong>Palline di labneh:</strong> cola 48 h, arrotola in palline, conserva in un vasetto coperto d'olio (con erbe).",
        "<strong>Aromatizzato:</strong> incorpora aglio schiacciato, menta o scorza di limone nello yogurt.",
        "<strong>Za'atar fatto in casa:</strong> timo secco, sommacco, semi di sesamo e sale.",
    ],
    serve="Servi il labneh come mezze con pita, verdure crude e altri piattini (hummus, olive, peperoni grigliati). In versione dolce-salata accompagna anche miele e frutta. Sempre con un generoso filo d'olio.",
    store="Il labneh si conserva 4–5 giorni in frigo in un contenitore ermetico. Le palline sott'olio durano diverse settimane in frigo, completamente coperte d'olio.",
    faqs=[
        ("Cos'è il labneh?",
         "Il labneh è yogurt colato — denso e cremoso, tipico del Levante. Si scola il siero dallo yogurt per una consistenza tra lo yogurt greco molto denso e il formaggio fresco, servito con olio d'oliva e za'atar."),
        ("Come fare il labneh in casa?",
         "Mescola yogurt intero con un po' di sale, versa in una garza su un colino e lascia colare in frigo 12–24 h. Più a lungo, più fermo."),
        ("Quanto tempo colare il labneh?",
         "12–24 h per una consistenza spalmabile; 48 h per un labneh abbastanza fermo da arrotolare in palline e conservare sott'olio."),
        ("Cos'è lo za'atar?",
         "Lo za'atar è una miscela mediorientale di timo secco, sommacco, semi di sesamo e sale. Si sposa perfettamente con labneh e olio d'oliva."),
        ("Con cosa si mangia il labneh?",
         "Con pita o pane piatto, come mezze, con verdure crude, olive e altri piattini. Si serve sempre con un filo d'olio d'oliva e spesso za'atar."),
    ],
    schema_name="Labneh con za'atar e olio d'oliva",
    schema_desc="Labneh fatto in casa: yogurt colato cremoso servito con un generoso filo d'olio extravergine e za'atar.",
    schema_ing=["500 g yogurt bianco intero", "1/2 cucchiaino di sale", "olio extravergine d'oliva",
                "1-2 cucchiai di za'atar", "pane pita"],
    schema_steps=[
        "Mescolare lo yogurt con il sale.",
        "Versare in una garza su un colino sopra una ciotola.",
        "Colare in frigo 12-24 h.",
        "Stendere in una ciotola e creare un pozzo.",
        "Condire generosamente con olio d'oliva e spolverare di za'atar."],
    keywords="labneh, labneh za'atar, ricetta labneh, labneh fatto in casa, yogurt colato olio d'oliva",
    cuisine="Middle Eastern", category="Mezze", prep="PT10M", cook="PT0M", total="PT12H", yield_="4 porzioni",
    nutrition={"servingSize": "1 porzione", "calories": "150 kcal", "fatContent": "11 g", "proteinContent": "7 g", "carbohydrateContent": "5 g"},
)
C["el"] = dict(
    title="Λαμπνέ σπιτικό με ζάαταρ και ελαιόλαδο: η εύκολη συνταγή",
    desc="Σπιτικό λαμπνέ: κρεμώδες στραγγιστό γιαούρτι με γενναιόδωρο ελαιόλαδο και ζάαταρ. Μέθοδος στραγγίσματος, χρόνοι και μπαλάκια λαμπνέ σε λάδι.",
    h1="Λαμπνέ με ζάαταρ και ελαιόλαδο",
    lede="Το λαμπνέ είναι στραγγιστό γιαούρτι — πηχτό και κρεμώδες, σταρ των μεσανατολικών μεζέδων. Θέλει μόνο γιαούρτι, αλάτι και χρόνο, μετά μια γενναιόδωρη λιμνούλα ελαιόλαδου και λίγο ζάαταρ.",
    info="<strong>Προετοιμασία:</strong> 10 λεπτά · <strong>Στράγγισμα:</strong> 12–24 ώρες · <strong>Μερίδες:</strong> 4 · <strong>Κουζίνα:</strong> λεβαντίνικη · <strong>Δυσκολία:</strong> πολύ εύκολη",
    intro="Το λαμπνέ είναι απλώς γιαούρτι από το οποίο έχει στραγγιστεί ο ορός για να γίνει πυκνό και βελούδινο, κάτι ανάμεσα σε φρέσκο τυρί και πολύ πηχτό στραγγιστό γιαούρτι. Σερβίρεται με ένα πηγάδι ελαιόλαδου και ζάαταρ, ένας απαραίτητος μεζές με ψωμί.",
    ingredients=[
        "500 g γιαούρτι πλήρες (στραγγιστό ή απλό)",
        "1/2 κ.γ. αλάτι",
    ],
    garnish=[
        "Έξτρα παρθένο ελαιόλαδο (γενναιόδωρα)",
        "1–2 κ.σ. ζάαταρ",
        "Πίτα ή λαγάνα, για σερβίρισμα",
        "Προαιρετικά: φρέσκος δυόσμος, λιωμένο σκόρδο",
    ],
    steps=[
        "<strong>Αλατίστε το γιαούρτι.</strong> Ανακατέψτε το γιαούρτι με το αλάτι: βοηθά να βγει το νερό και συντηρεί το λαμπνέ.",
        "<strong>Στραγγίστε.</strong> Στρώστε ένα σουρωτήρι με τουλπάνι (ή καθαρό λεπτό πανί), ρίξτε το γιαούρτι, κλείστε το πανί και βάλτε πάνω από μπολ για να μαζευτεί ο ορός.",
        "<strong>Ξεκουράστε στο ψυγείο.</strong> Βάλτε στο ψυγείο 12–24 ώρες. Όσο πιο πολύ στραγγίζει, τόσο πιο σφιχτό γίνεται (μέχρι να πλάθεται σε μπαλάκια).",
        "<strong>Σερβίρετε στο πιάτο.</strong> Απλώστε το λαμπνέ σε ρηχό μπολ, λειάνετε και κάντε ένα πηγαδάκι με το πίσω μέρος κουταλιού.",
        "<strong>Ολοκληρώστε με ελαιόλαδο.</strong> Περιχύστε γενναιόδωρα με έξτρα παρθένο ελαιόλαδο και πασπαλίστε ζάαταρ. Σερβίρετε δροσερό με ψωμί.",
    ],
    oil="Στο λαμπνέ το ελαιόλαδο δεν είναι λεπτομέρεια: δένει τη δροσερή οξύτητα του γιαουρτιού με τα μυρωδικά του ζάαταρ. Χρησιμοποιήστε ένα <strong>φρουτώδες έξτρα παρθένο</strong>, χωρίς φειδώ — ένα πραγματικό πηγάδι λαδιού — και κρατήστε για τα μπαλάκια σε λάδι.",
    tips=[
        "Το πλήρες γιαούρτι δίνει πιο κρεμώδες λαμπνέ· το άπαχο βγαίνει πιο στεγνό.",
        "Μην παραλείψετε το αλάτι: βοηθά στράγγισμα και συντήρηση.",
        "Στραγγίστε περισσότερο (24–48 ώρες) για λαμπνέ που πλάθεται σε μπαλάκια.",
        "Κρατήστε τον ορό: μπαίνει σε ζύμες ψωμιού, μαρινάδες ή smoothies.",
    ],
    variations=[
        "<strong>Μπαλάκια λαμπνέ:</strong> στραγγίστε 48 ώρες, πλάστε μπαλάκια, φυλάξτε σε βαζάκι σκεπασμένα με ελαιόλαδο (με μυρωδικά).",
        "<strong>Αρωματισμένο:</strong> προσθέστε λιωμένο σκόρδο, δυόσμο ή ξύσμα λεμονιού στο γιαούρτι.",
        "<strong>Σπιτικό ζάαταρ:</strong> ξερό θυμάρι, σουμάκ, σουσάμι και αλάτι.",
    ],
    serve="Σερβίρετε το λαμπνέ ως μεζέ με πίτα, ωμά λαχανικά και άλλα πιατάκια (χούμους, ελιές, ψητές πιπεριές). Σε γλυκο-αλμυρή εκδοχή ταιριάζει και με μέλι και φρούτα. Πάντα με γενναιόδωρο ελαιόλαδο.",
    store="Το λαμπνέ διατηρείται 4–5 ημέρες στο ψυγείο σε αεροστεγές δοχείο. Τα μπαλάκια σε ελαιόλαδο κρατούν αρκετές εβδομάδες στο ψυγείο, πλήρως σκεπασμένα με λάδι.",
    faqs=[
        ("Τι είναι το λαμπνέ;",
         "Το λαμπνέ είναι στραγγιστό γιαούρτι — πηχτό και κρεμώδες, τυπικό του Λεβάντε. Στραγγίζεται ο ορός για υφή ανάμεσα σε πολύ πηχτό στραγγιστό γιαούρτι και φρέσκο τυρί, με ελαιόλαδο και ζάαταρ."),
        ("Πώς φτιάχνεται σπιτικό λαμπνέ;",
         "Ανακατέψτε πλήρες γιαούρτι με λίγο αλάτι, ρίξτε σε τουλπάνι πάνω σε σουρωτήρι και αφήστε να στραγγίσει στο ψυγείο 12–24 ώρες. Όσο πιο πολύ, τόσο πιο σφιχτό."),
        ("Πόση ώρα στραγγίζει το λαμπνέ;",
         "12–24 ώρες για υφή για άλειμμα· 48 ώρες για λαμπνέ αρκετά σφιχτό ώστε να πλάθεται σε μπαλάκια και να φυλάσσεται σε λάδι."),
        ("Τι είναι το ζάαταρ;",
         "Το ζάαταρ είναι μεσανατολικό μείγμα από ξερό θυμάρι, σουμάκ, σουσάμι και αλάτι. Ταιριάζει τέλεια με λαμπνέ και ελαιόλαδο."),
        ("Με τι τρώγεται το λαμπνέ;",
         "Με πίτα ή λαγάνα, ως μεζές, με ωμά λαχανικά, ελιές και άλλα πιατάκια. Σερβίρεται πάντα με ελαιόλαδο και συχνά ζάαταρ."),
    ],
    schema_name="Λαμπνέ με ζάαταρ και ελαιόλαδο",
    schema_desc="Σπιτικό λαμπνέ: κρεμώδες στραγγιστό γιαούρτι με γενναιόδωρο έξτρα παρθένο ελαιόλαδο και ζάαταρ.",
    schema_ing=["500 g πλήρες γιαούρτι", "1/2 κ.γ. αλάτι", "έξτρα παρθένο ελαιόλαδο",
                "1-2 κ.σ. ζάαταρ", "πίτα"],
    schema_steps=[
        "Ανακατέψτε το γιαούρτι με το αλάτι.",
        "Ρίξτε σε τουλπάνι πάνω σε σουρωτήρι πάνω από μπολ.",
        "Στραγγίστε στο ψυγείο 12-24 ώρες.",
        "Απλώστε σε μπολ και κάντε πηγαδάκι.",
        "Περιχύστε γενναιόδωρα με ελαιόλαδο και πασπαλίστε ζάαταρ."],
    keywords="λαμπνέ, λαμπνέ ζάαταρ, συνταγή λαμπνέ, σπιτικό λαμπνέ, στραγγιστό γιαούρτι ελαιόλαδο",
    cuisine="Middle Eastern", category="Μεζές", prep="PT10M", cook="PT0M", total="PT12H", yield_="4 μερίδες",
    nutrition={"servingSize": "1 μερίδα", "calories": "150 kcal", "fatContent": "11 g", "proteinContent": "7 g", "carbohydrateContent": "5 g"},
)

if __name__ == "__main__":
    write_cluster("labneh-huile-olive-zaatar", C)
