# -*- coding: utf-8 -*-
"""Batch 4: authentic health-topic guides — eczema/psoriasis, constipation,
baby diversification. x4 languages. Careful, balanced YMYL content + disclaimers."""
from guide_render import write_guide_cluster

MED = {
    "fr": "Information générale, pas un avis médical. Pour un problème de santé, un traitement en cours ou un nourrisson, demandez conseil à un médecin ou un pharmacien.",
    "en": "General information, not medical advice. For a health problem, an ongoing treatment or an infant, consult a doctor or pharmacist.",
    "it": "Informazione generale, non un parere medico. Per un problema di salute, una terapia in corso o un neonato, consulta un medico o un farmacista.",
    "el": "Γενική πληροφόρηση, όχι ιατρική συμβουλή. Για πρόβλημα υγείας, θεραπεία σε εξέλιξη ή βρέφος, συμβουλευτείτε γιατρό ή φαρμακοποιό.",
}

# ==================================================== ECZEMA / PSORIASIS ======
E = {}
E["fr"] = dict(
    title="Huile d'olive contre l'eczéma et le psoriasis : ce qui est vrai (et prudent)",
    desc="Huile d'olive pour l'eczéma et le psoriasis : émollient traditionnel, mais preuves limitées et risque pour la barrière cutanée. Usage prudent, précautions et alternatives.",
    h1="Huile d'olive, eczéma et psoriasis : le point honnête",
    lede="L'huile d'olive est un remède de grand-mère courant contre les peaux sèches et squameuses. Sur l'eczéma et le psoriasis, la réalité est plus nuancée : émolliente, oui, mais avec des limites qu'il faut connaître.",
    section="skincare", datePublished="2026-05-04", disclaimer=MED["fr"],
    keywords="huile d'olive eczéma, huile d'olive psoriasis, eczéma huile olive, huile pour eczema, soin peau sèche huile d'olive",
    intro="Beaucoup de sites présentent l'huile d'olive comme une solution contre l'eczéma et le psoriasis. La vérité est plus mesurée : c'est un bon corps gras hydratant, mais les preuves sont limitées et, pour l'eczéma en particulier, certaines études pointent un risque pour la barrière de la peau. Voici un usage prudent.",
    key_facts=[
        "L'huile d'olive est un émollient : elle adoucit et limite la perte en eau des peaux sèches et squameuses.",
        "Sur l'eczéma (dermatite atopique), des études suggèrent que l'acide oléique de l'huile d'olive peut fragiliser la barrière cutanée — la prudence s'impose.",
        "Elle ne traite ni ne guérit l'eczéma ou le psoriasis, qui relèvent d'un suivi dermatologique.",
        "N'appliquez jamais sur une peau lésée, suintante ou infectée sans avis médical, et faites un test.",
    ],
    sections=[
        ("Pourquoi on l'utilise sur les peaux sèches",
         "<p>L'huile d'olive est un émollient riche en acide oléique, en squalène et en vitamine E. Sur une peau sèche, épaisse ou squameuse, elle forme un film qui adoucit et limite l'évaporation de l'eau. C'est ce qui explique son usage traditionnel sur les plaques du psoriasis et les zones sèches.</p>"),
        ("Le point important sur l'eczéma",
         "<p>Pour la dermatite atopique (eczéma), il faut être honnête : plusieurs études suggèrent que l'huile d'olive, du fait de sa richesse en <strong>acide oléique</strong>, peut <strong>altérer la barrière cutanée</strong> et n'est pas idéale sur une peau eczémateuse fragile. Des émollients formulés pour l'atopie sont généralement préférés. Autrement dit, le remède populaire ne fait pas consensus scientifique.</p>"),
        ("Psoriasis : un usage d'appoint",
         "<p>Sur le psoriasis, l'huile d'olive peut aider à assouplir les squames et à hydrater, en complément — jamais en remplacement — d'un traitement prescrit. Un massage doux à l'huile tiède sur les plaques épaisses peut faciliter le décollement des squames, mais cela ne traite pas la maladie de fond.</p>"),
        ("Précautions",
         "<p>Faites toujours un test sur une petite zone. N'appliquez pas sur une peau <strong>lésée, fissurée, suintante ou infectée</strong> sans avis médical. Si les lésions s'aggravent, arrêtez. L'eczéma et le psoriasis sont des maladies chroniques qui nécessitent un suivi dermatologique : l'huile d'olive ne remplace ni une crème émolliente adaptée, ni un traitement médical.</p>"),
    ],
    faqs=[
        ("L'huile d'olive est-elle bonne pour l'eczéma ?",
         "Elle hydrate, mais son intérêt sur l'eczéma est discuté : riche en acide oléique, elle peut fragiliser la barrière cutanée déjà altérée par la dermatite atopique. Des émollients adaptés à l'atopie sont souvent préférés. Demandez conseil à un dermatologue."),
        ("L'huile d'olive soigne-t-elle le psoriasis ?",
         "Non. Elle peut aider à assouplir et hydrater les plaques en complément, mais elle ne traite pas le psoriasis, qui nécessite un suivi médical et souvent un traitement spécifique."),
        ("Comment appliquer l'huile d'olive sur une peau sèche ?",
         "En petite quantité, sur peau propre et de préférence encore humide, en massage doux. Évitez les zones lésées ou infectées et faites d'abord un test de tolérance."),
        ("Quelle huile pour l'eczéma si ce n'est pas l'huile d'olive ?",
         "Les recommandations dermatologiques privilégient souvent des émollients formulés pour l'atopie. Certaines huiles plus riches en acide linoléique sont considérées comme plus respectueuses de la barrière. Demandez conseil à un professionnel."),
        ("Peut-on mettre de l'huile d'olive sur une plaie ou une peau qui suinte ?",
         "Non, pas sans avis médical. Sur une peau lésée, fissurée ou infectée, l'application peut aggraver la situation. Consultez un médecin."),
    ],
)
E["en"] = dict(
    title="Olive Oil for Eczema and Psoriasis: what's true (and cautious)",
    desc="Olive oil for eczema and psoriasis: a traditional emollient, but limited evidence and a skin-barrier risk. Cautious use, precautions and alternatives.",
    h1="Olive Oil, Eczema and Psoriasis: the honest picture",
    lede="Olive oil is a common folk remedy for dry, scaly skin. For eczema and psoriasis, the reality is more nuanced: emollient, yes, but with limits worth knowing.",
    section="skincare", datePublished="2026-05-04", disclaimer=MED["en"],
    keywords="olive oil eczema, olive oil psoriasis, olive oil for eczema, olive oil dry skin, emollient olive oil",
    intro="Many sites present olive oil as a solution for eczema and psoriasis. The truth is more measured: it's a good moisturising fat, but the evidence is limited and, for eczema in particular, some studies point to a skin-barrier risk. Here's a cautious approach.",
    key_facts=[
        "Olive oil is an emollient: it softens and limits water loss from dry, scaly skin.",
        "For eczema (atopic dermatitis), studies suggest olive oil's oleic acid may weaken the skin barrier — caution is warranted.",
        "It does not treat or cure eczema or psoriasis, which require dermatological care.",
        "Never apply to broken, weeping or infected skin without medical advice, and patch-test first.",
    ],
    sections=[
        ("Why it's used on dry skin",
         "<p>Olive oil is an emollient rich in oleic acid, squalene and vitamin E. On dry, thick or scaly skin, it forms a film that softens and limits water evaporation. This explains its traditional use on psoriasis plaques and dry areas.</p>"),
        ("The important point about eczema",
         "<p>For atopic dermatitis (eczema), honesty is needed: several studies suggest that olive oil, because it is high in <strong>oleic acid</strong>, can <strong>impair the skin barrier</strong> and is not ideal on fragile eczematous skin. Emollients formulated for atopy are generally preferred. In other words, the popular remedy is not a scientific consensus.</p>"),
        ("Psoriasis: a supportive use",
         "<p>On psoriasis, olive oil can help soften scales and moisturise, alongside — never instead of — prescribed treatment. A gentle massage with warm oil on thick plaques may help lift scales, but it does not treat the underlying disease.</p>"),
        ("Precautions",
         "<p>Always patch-test on a small area. Do not apply to <strong>broken, cracked, weeping or infected skin</strong> without medical advice. If lesions worsen, stop. Eczema and psoriasis are chronic conditions needing dermatological care: olive oil replaces neither a suitable emollient cream nor medical treatment.</p>"),
    ],
    faqs=[
        ("Is olive oil good for eczema?",
         "It moisturises, but its value for eczema is debated: high in oleic acid, it may weaken the skin barrier already impaired by atopic dermatitis. Emollients designed for atopy are often preferred. Ask a dermatologist."),
        ("Does olive oil cure psoriasis?",
         "No. It can help soften and moisturise plaques as a supportive measure, but it does not treat psoriasis, which requires medical care and often specific treatment."),
        ("How do you apply olive oil to dry skin?",
         "In a small amount, on clean and preferably still-damp skin, with a gentle massage. Avoid broken or infected areas and do a tolerance test first."),
        ("Which oil for eczema if not olive oil?",
         "Dermatology guidance often favours emollients formulated for atopy. Some oils higher in linoleic acid are considered more barrier-friendly. Ask a professional."),
        ("Can you put olive oil on a wound or weeping skin?",
         "No, not without medical advice. On broken, cracked or infected skin, applying it can make things worse. See a doctor."),
    ],
)
E["it"] = dict(
    title="Olio d'oliva contro eczema e psoriasi: cosa è vero (e prudente)",
    desc="Olio d'oliva per eczema e psoriasi: emolliente tradizionale, ma prove limitate e un rischio per la barriera cutanea. Uso prudente, precauzioni e alternative.",
    h1="Olio d'oliva, eczema e psoriasi: il quadro onesto",
    lede="L'olio d'oliva è un rimedio comune per la pelle secca e squamosa. Su eczema e psoriasi la realtà è più sfumata: emolliente sì, ma con limiti da conoscere.",
    section="skincare", datePublished="2026-05-04", disclaimer=MED["it"],
    keywords="olio d'oliva eczema, olio d'oliva psoriasi, olio d'oliva pelle secca, emolliente olio d'oliva",
    intro="Molti siti presentano l'olio d'oliva come soluzione per eczema e psoriasi. La verità è più misurata: è un buon grasso idratante, ma le prove sono limitate e, per l'eczema in particolare, alcuni studi indicano un rischio per la barriera cutanea.",
    key_facts=[
        "L'olio d'oliva è un emolliente: ammorbidisce e limita la perdita d'acqua della pelle secca e squamosa.",
        "Per l'eczema (dermatite atopica), studi suggeriscono che l'acido oleico può indebolire la barriera cutanea — serve prudenza.",
        "Non tratta né cura eczema o psoriasi, che richiedono cure dermatologiche.",
        "Non applicare mai su pelle lesa, essudante o infetta senza parere medico, e fai un test.",
    ],
    sections=[
        ("Perché si usa sulla pelle secca",
         "<p>L'olio d'oliva è un emolliente ricco di acido oleico, squalene e vitamina E. Su pelle secca, spessa o squamosa forma un film che ammorbidisce e limita l'evaporazione dell'acqua. Da qui l'uso tradizionale sulle placche di psoriasi e sulle zone secche.</p>"),
        ("Il punto importante sull'eczema",
         "<p>Per la dermatite atopica (eczema) serve onestà: diversi studi suggeriscono che l'olio d'oliva, ricco di <strong>acido oleico</strong>, può <strong>compromettere la barriera cutanea</strong> e non è ideale sulla pelle eczematosa fragile. Si preferiscono emollienti formulati per l'atopia. Il rimedio popolare non è un consenso scientifico.</p>"),
        ("Psoriasi: un uso di supporto",
         "<p>Sulla psoriasi l'olio d'oliva può aiutare ad ammorbidire le squame e idratare, a supporto — mai al posto — di un trattamento prescritto. Un massaggio delicato con olio tiepido sulle placche spesse può facilitare il distacco delle squame, ma non cura la malattia.</p>"),
        ("Precauzioni",
         "<p>Fai sempre un test su una piccola zona. Non applicare su pelle <strong>lesa, screpolata, essudante o infetta</strong> senza parere medico. Se le lesioni peggiorano, interrompi. Eczema e psoriasi sono malattie croniche che richiedono cure dermatologiche.</p>"),
    ],
    faqs=[
        ("L'olio d'oliva fa bene all'eczema?",
         "Idrata, ma il suo valore sull'eczema è discusso: ricco di acido oleico, può indebolire la barriera già compromessa dalla dermatite atopica. Spesso si preferiscono emollienti per l'atopia. Chiedi a un dermatologo."),
        ("L'olio d'oliva cura la psoriasi?",
         "No. Può aiutare ad ammorbidire e idratare le placche come supporto, ma non tratta la psoriasi, che richiede cure mediche."),
        ("Come applicare l'olio d'oliva sulla pelle secca?",
         "In piccola quantità, su pelle pulita e preferibilmente ancora umida, con massaggio delicato. Evita zone lese o infette e fai prima un test."),
        ("Quale olio per l'eczema se non l'olio d'oliva?",
         "Le linee guida dermatologiche preferiscono spesso emollienti per l'atopia. Alcuni oli più ricchi di acido linoleico sono considerati più rispettosi della barriera. Chiedi a un professionista."),
        ("Si può mettere olio d'oliva su una ferita o pelle essudante?",
         "No, non senza parere medico. Su pelle lesa o infetta può peggiorare la situazione. Consulta un medico."),
    ],
)
E["el"] = dict(
    title="Ελαιόλαδο για έκζεμα και ψωρίαση: τι ισχύει (και τι είναι συνετό)",
    desc="Ελαιόλαδο για έκζεμα και ψωρίαση: παραδοσιακός μαλακτικός παράγοντας, αλλά περιορισμένα στοιχεία και κίνδυνος για τον φραγμό του δέρματος. Συνετή χρήση και προφυλάξεις.",
    h1="Ελαιόλαδο, έκζεμα και ψωρίαση: η τίμια εικόνα",
    lede="Το ελαιόλαδο είναι κοινή λαϊκή θεραπεία για ξηρό, φολιδωτό δέρμα. Στο έκζεμα και την ψωρίαση η πραγματικότητα είναι πιο σύνθετη: μαλακτικό ναι, αλλά με όρια που αξίζει να ξέρετε.",
    section="skincare", datePublished="2026-05-04", disclaimer=MED["el"],
    keywords="ελαιόλαδο έκζεμα, ελαιόλαδο ψωρίαση, ελαιόλαδο ξηρό δέρμα, μαλακτικό ελαιόλαδο",
    intro="Πολλά sites παρουσιάζουν το ελαιόλαδο ως λύση για έκζεμα και ψωρίαση. Η αλήθεια είναι πιο μετρημένη: είναι καλό ενυδατικό λιπαρό, αλλά τα στοιχεία είναι περιορισμένα και, ειδικά για το έκζεμα, κάποιες μελέτες δείχνουν κίνδυνο για τον φραγμό του δέρματος.",
    key_facts=[
        "Το ελαιόλαδο είναι μαλακτικό: απαλύνει και περιορίζει την απώλεια νερού από ξηρό, φολιδωτό δέρμα.",
        "Για το έκζεμα (ατοπική δερματίτιδα), μελέτες δείχνουν ότι το ελαϊκό οξύ μπορεί να αποδυναμώσει τον φραγμό — χρειάζεται προσοχή.",
        "Δεν θεραπεύει έκζεμα ή ψωρίαση, που χρειάζονται δερματολογική φροντίδα.",
        "Ποτέ σε πληγωμένο, υγρό ή μολυσμένο δέρμα χωρίς ιατρική συμβουλή· κάντε τεστ.",
    ],
    sections=[
        ("Γιατί χρησιμοποιείται στο ξηρό δέρμα",
         "<p>Το ελαιόλαδο είναι μαλακτικό πλούσιο σε ελαϊκό οξύ, σκουαλένιο και βιταμίνη E. Σε ξηρό, παχύ ή φολιδωτό δέρμα σχηματίζει φιλμ που απαλύνει και περιορίζει την εξάτμιση νερού. Από εκεί η παραδοσιακή χρήση σε πλάκες ψωρίασης.</p>"),
        ("Το σημαντικό σημείο για το έκζεμα",
         "<p>Για την ατοπική δερματίτιδα (έκζεμα) χρειάζεται ειλικρίνεια: αρκετές μελέτες δείχνουν ότι το ελαιόλαδο, πλούσιο σε <strong>ελαϊκό οξύ</strong>, μπορεί να <strong>βλάψει τον φραγμό του δέρματος</strong> και δεν είναι ιδανικό σε εύθραυστο εκζεματικό δέρμα. Προτιμώνται μαλακτικά για την ατοπία.</p>"),
        ("Ψωρίαση: υποστηρικτική χρήση",
         "<p>Στην ψωρίαση το ελαιόλαδο μπορεί να μαλακώσει τις φολίδες και να ενυδατώσει, ως συμπλήρωμα — ποτέ αντικατάσταση — της συνταγογραφημένης θεραπείας. Απαλό μασάζ με χλιαρό λάδι σε παχιές πλάκες βοηθά, αλλά δεν θεραπεύει τη νόσο.</p>"),
        ("Προφυλάξεις",
         "<p>Κάντε πάντα τεστ σε μικρή περιοχή. Μην εφαρμόζετε σε <strong>πληγωμένο, σκασμένο, υγρό ή μολυσμένο δέρμα</strong> χωρίς ιατρική συμβουλή. Αν οι βλάβες χειροτερεύουν, σταματήστε. Έκζεμα και ψωρίαση χρειάζονται δερματολογική παρακολούθηση.</p>"),
    ],
    faqs=[
        ("Κάνει καλό το ελαιόλαδο στο έκζεμα;",
         "Ενυδατώνει, αλλά η αξία του στο έκζεμα είναι υπό συζήτηση: πλούσιο σε ελαϊκό οξύ, μπορεί να αποδυναμώσει τον ήδη επηρεασμένο φραγμό. Συχνά προτιμώνται μαλακτικά για την ατοπία. Ρωτήστε δερματολόγο."),
        ("Θεραπεύει το ελαιόλαδο την ψωρίαση;",
         "Όχι. Μπορεί να μαλακώσει και να ενυδατώσει τις πλάκες ως υποστήριξη, αλλά δεν θεραπεύει την ψωρίαση, που χρειάζεται ιατρική φροντίδα."),
        ("Πώς εφαρμόζεται σε ξηρό δέρμα;",
         "Σε μικρή ποσότητα, σε καθαρό και κατά προτίμηση νωπό δέρμα, με απαλό μασάζ. Αποφύγετε πληγωμένες ή μολυσμένες περιοχές και κάντε τεστ."),
        ("Ποιο λάδι για το έκζεμα αν όχι το ελαιόλαδο;",
         "Οι δερματολογικές οδηγίες προτιμούν συχνά μαλακτικά για την ατοπία. Κάποια λάδια πλουσιότερα σε λινελαϊκό οξύ θεωρούνται πιο φιλικά στον φραγμό. Ρωτήστε επαγγελματία."),
        ("Βάζουμε ελαιόλαδο σε πληγή ή υγρό δέρμα;",
         "Όχι, χωρίς ιατρική συμβουλή. Σε πληγωμένο ή μολυσμένο δέρμα μπορεί να χειροτερέψει. Δείτε γιατρό."),
    ],
)

# ======================================================== CONSTIPATION ========
CO = {}
CO["fr"] = dict(
    title="Huile d'olive contre la constipation : est-ce que ça marche et comment ?",
    desc="Huile d'olive et constipation : effet lubrifiant, cuillère à jeun, dose et preuves. Comment l'utiliser, avec quoi l'associer et quand consulter.",
    h1="Huile d'olive contre la constipation",
    lede="Une cuillère d'huile d'olive contre la constipation est un remède traditionnel. Il a une logique — l'huile lubrifie et stimule la digestion — mais il a aussi ses limites. Voici comment l'utiliser sensément.",
    section="digestion", datePublished="2026-05-04", disclaimer=MED["fr"],
    keywords="huile d'olive constipation, huile d'olive contre la constipation, huile olive à jeun constipation, cuillère huile d'olive transit",
    intro="L'huile d'olive figure parmi les remèdes maison les plus cités contre la constipation occasionnelle. Elle agit comme un léger lubrifiant et stimule la vésicule biliaire, ce qui peut faciliter le transit. Les preuves restent limitées, mais l'usage est simple et généralement sans risque en petite quantité.",
    key_facts=[
        "L'huile d'olive agit comme un lubrifiant doux et stimule la sécrétion de bile, ce qui peut ramollir les selles et faciliter le transit.",
        "Usage courant : 1 cuillère à soupe d'huile d'olive extra vierge, souvent à jeun le matin, parfois avec un peu de jus de citron.",
        "De petites études (notamment chez des patients dialysés) ont trouvé un effet comparable à l'huile minérale sur la constipation.",
        "Ce n'est pas un traitement de la constipation chronique : eau, fibres et activité physique restent la base.",
    ],
    sections=[
        ("Pourquoi l'huile d'olive peut aider",
         "<p>L'huile d'olive apporte des corps gras qui <strong>lubrifient</strong> le contenu intestinal et rendent les selles plus glissantes. Elle stimule aussi la <strong>sécrétion de bile</strong>, qui participe à la digestion des graisses et au transit. Sur une constipation occasionnelle, une petite dose peut donc donner un coup de pouce.</p>"),
        ("Comment l'utiliser",
         "<p>La façon la plus courante : <strong>1 cuillère à soupe d'huile d'olive extra vierge</strong>, le matin à jeun, éventuellement mélangée à un peu de jus de citron. Certains la prennent le soir. Buvez de l'eau et intégrez-la dans une alimentation riche en fibres (fruits, légumes, céréales complètes).</p>"),
        ("Ce que disent les études",
         "<p>Les données sont limitées mais encourageantes. Des essais chez des patients hémodialysés, souvent sujets à la constipation, ont montré que l'huile d'olive pouvait améliorer la consistance et la fréquence des selles, de façon comparable à l'huile minérale. Chez la population générale, l'effet est plausible mais moins documenté.</p>"),
        ("Limites et quand consulter",
         "<p>L'huile d'olive n'est pas un laxatif puissant ni un traitement de fond. Une cuillère apporte ~120 kcal, à prendre en compte. Consultez un médecin si la constipation est <strong>chronique, douloureuse, récente et inexpliquée</strong>, ou accompagnée de sang, de perte de poids ou de vomissements. Ne donnez pas d'huile à un nourrisson dans ce but sans avis pédiatrique.</p>"),
    ],
    faqs=[
        ("L'huile d'olive aide-t-elle vraiment contre la constipation ?",
         "Elle peut aider sur une constipation occasionnelle : elle lubrifie le contenu intestinal et stimule la bile. De petites études suggèrent un effet réel, comparable à l'huile minérale, mais ce n'est pas un laxatif puissant."),
        ("Combien d'huile d'olive prendre contre la constipation ?",
         "En général 1 cuillère à soupe d'huile d'olive extra vierge, souvent à jeun le matin. Inutile d'en prendre davantage : au-delà, on ajoute surtout des calories."),
        ("Faut-il prendre l'huile d'olive à jeun pour le transit ?",
         "Beaucoup la prennent le matin à jeun, parfois avec du citron, car l'estomac vide peut favoriser l'effet. Il n'y a pas de preuve stricte que le moment change fondamentalement le résultat."),
        ("Huile d'olive et citron contre la constipation, ça marche ?",
         "Le mélange est populaire : l'huile lubrifie, le citron apporte de la fraîcheur et un peu d'acidité. L'effet vient surtout de l'huile ; le citron améliore surtout le goût."),
        ("Quand consulter pour une constipation ?",
         "Si elle est chronique, douloureuse, d'apparition récente et inexpliquée, ou accompagnée de sang, de fièvre, de vomissements ou d'une perte de poids. Un médecin doit alors évaluer la cause."),
    ],
)
CO["en"] = dict(
    title="Olive Oil for Constipation: does it work and how?",
    desc="Olive oil and constipation: lubricating effect, a spoon on an empty stomach, dose and evidence. How to use it, what to pair it with, and when to see a doctor.",
    h1="Olive Oil for Constipation",
    lede="A spoonful of olive oil for constipation is a traditional remedy. It has a rationale — oil lubricates and stimulates digestion — but also limits. Here's how to use it sensibly.",
    section="digestion", datePublished="2026-05-04", disclaimer=MED["en"],
    keywords="olive oil constipation, olive oil for constipation, olive oil empty stomach, tablespoon olive oil bowel",
    intro="Olive oil is among the most cited home remedies for occasional constipation. It acts as a mild lubricant and stimulates the gallbladder, which can ease transit. Evidence is limited, but the practice is simple and generally low-risk in small amounts.",
    key_facts=[
        "Olive oil acts as a gentle lubricant and stimulates bile secretion, which can soften stool and ease transit.",
        "Common use: 1 tablespoon of extra virgin olive oil, often on an empty stomach in the morning, sometimes with a little lemon juice.",
        "Small studies (notably in dialysis patients) found an effect comparable to mineral oil on constipation.",
        "It is not a treatment for chronic constipation: water, fibre and physical activity remain the basis.",
    ],
    sections=[
        ("Why olive oil can help",
         "<p>Olive oil provides fats that <strong>lubricate</strong> the intestinal contents and make stool more slippery. It also stimulates <strong>bile secretion</strong>, which aids fat digestion and transit. For occasional constipation, a small dose can therefore give a helpful nudge.</p>"),
        ("How to use it",
         "<p>The most common way: <strong>1 tablespoon of extra virgin olive oil</strong>, in the morning on an empty stomach, optionally mixed with a little lemon juice. Some take it in the evening. Drink water and include it within a fibre-rich diet (fruit, vegetables, whole grains).</p>"),
        ("What the studies say",
         "<p>The data are limited but encouraging. Trials in haemodialysis patients, who are often prone to constipation, showed olive oil could improve stool consistency and frequency, comparably to mineral oil. In the general population, the effect is plausible but less documented.</p>"),
        ("Limits and when to see a doctor",
         "<p>Olive oil is not a strong laxative or a root-cause treatment. One tablespoon is ~120 kcal, worth noting. See a doctor if constipation is <strong>chronic, painful, newly appeared and unexplained</strong>, or comes with blood, weight loss or vomiting. Do not give oil to an infant for this purpose without paediatric advice.</p>"),
    ],
    faqs=[
        ("Does olive oil really help with constipation?",
         "It can help with occasional constipation: it lubricates the intestinal contents and stimulates bile. Small studies suggest a real effect, comparable to mineral oil, but it is not a strong laxative."),
        ("How much olive oil for constipation?",
         "Usually 1 tablespoon of extra virgin olive oil, often on an empty stomach in the morning. There's no need for more: beyond that, you mainly add calories."),
        ("Should you take olive oil on an empty stomach for transit?",
         "Many take it in the morning on an empty stomach, sometimes with lemon, as an empty stomach may favour the effect. There's no strict evidence that timing fundamentally changes the result."),
        ("Does olive oil and lemon work for constipation?",
         "The mix is popular: the oil lubricates, the lemon adds freshness and a little acidity. The effect comes mainly from the oil; the lemon mostly improves the taste."),
        ("When should you see a doctor for constipation?",
         "If it is chronic, painful, newly appeared and unexplained, or comes with blood, fever, vomiting or weight loss. A doctor should then assess the cause."),
    ],
)
CO["it"] = dict(
    title="Olio d'oliva contro la stitichezza: funziona e come?",
    desc="Olio d'oliva e stitichezza: effetto lubrificante, un cucchiaio a stomaco vuoto, dose e prove. Come usarlo, con cosa abbinarlo e quando consultare un medico.",
    h1="Olio d'oliva contro la stitichezza",
    lede="Un cucchiaio di olio d'oliva contro la stitichezza è un rimedio tradizionale. Ha una logica — l'olio lubrifica e stimola la digestione — ma anche dei limiti. Ecco come usarlo con criterio.",
    section="digestion", datePublished="2026-05-04", disclaimer=MED["it"],
    keywords="olio d'oliva stitichezza, olio d'oliva contro la stitichezza, olio d'oliva a stomaco vuoto, cucchiaio olio d'oliva intestino",
    intro="L'olio d'oliva è tra i rimedi casalinghi più citati per la stitichezza occasionale. Agisce come lubrificante leggero e stimola la cistifellea, il che può facilitare il transito. Le prove sono limitate, ma l'uso è semplice e in genere a basso rischio in piccole quantità.",
    key_facts=[
        "L'olio d'oliva agisce come lubrificante delicato e stimola la secrezione di bile, ammorbidendo le feci.",
        "Uso comune: 1 cucchiaio di olio extravergine, spesso a stomaco vuoto al mattino, a volte con succo di limone.",
        "Piccoli studi (in pazienti dializzati) hanno trovato un effetto paragonabile all'olio minerale.",
        "Non è una cura per la stitichezza cronica: acqua, fibre e attività fisica restano la base.",
    ],
    sections=[
        ("Perché l'olio d'oliva può aiutare",
         "<p>L'olio d'oliva apporta grassi che <strong>lubrificano</strong> il contenuto intestinale e rendono le feci più scivolose. Stimola anche la <strong>secrezione di bile</strong>, utile alla digestione dei grassi e al transito. Su una stitichezza occasionale, una piccola dose può dare una spinta.</p>"),
        ("Come usarlo",
         "<p>Il modo più comune: <strong>1 cucchiaio di olio extravergine</strong>, al mattino a stomaco vuoto, eventualmente con un po' di succo di limone. Alcuni lo prendono la sera. Bevi acqua e inseriscilo in una dieta ricca di fibre.</p>"),
        ("Cosa dicono gli studi",
         "<p>I dati sono limitati ma incoraggianti. Studi in pazienti in emodialisi, spesso soggetti a stitichezza, hanno mostrato che l'olio d'oliva può migliorare consistenza e frequenza delle feci, in modo paragonabile all'olio minerale. Nella popolazione generale l'effetto è plausibile ma meno documentato.</p>"),
        ("Limiti e quando consultare",
         "<p>L'olio d'oliva non è un lassativo potente né una cura di fondo. Un cucchiaio è ~120 kcal. Consulta un medico se la stitichezza è <strong>cronica, dolorosa, recente e inspiegata</strong>, o con sangue, perdita di peso o vomito. Non dare olio a un neonato a questo scopo senza parere pediatrico.</p>"),
    ],
    faqs=[
        ("L'olio d'oliva aiuta davvero contro la stitichezza?",
         "Può aiutare su una stitichezza occasionale: lubrifica il contenuto intestinale e stimola la bile. Piccoli studi suggeriscono un effetto reale, ma non è un lassativo potente."),
        ("Quanto olio d'oliva contro la stitichezza?",
         "In genere 1 cucchiaio di olio extravergine, spesso a stomaco vuoto al mattino. Non serve di più: oltre, si aggiungono soprattutto calorie."),
        ("Va preso a stomaco vuoto per il transito?",
         "Molti lo prendono al mattino a stomaco vuoto, a volte con limone. Non c'è prova rigorosa che il momento cambi in modo sostanziale il risultato."),
        ("Olio d'oliva e limone funzionano?",
         "Il mix è popolare: l'olio lubrifica, il limone aggiunge freschezza. L'effetto viene soprattutto dall'olio; il limone migliora il gusto."),
        ("Quando consultare per la stitichezza?",
         "Se è cronica, dolorosa, recente e inspiegata, o con sangue, febbre, vomito o perdita di peso. Un medico deve valutarne la causa."),
    ],
)
CO["el"] = dict(
    title="Ελαιόλαδο για τη δυσκοιλιότητα: λειτουργεί και πώς;",
    desc="Ελαιόλαδο και δυσκοιλιότητα: λιπαντική δράση, μια κουταλιά με άδειο στομάχι, δόση και στοιχεία. Πώς να το χρησιμοποιείτε και πότε να δείτε γιατρό.",
    h1="Ελαιόλαδο για τη δυσκοιλιότητα",
    lede="Μια κουταλιά ελαιόλαδο για τη δυσκοιλιότητα είναι παραδοσιακή θεραπεία. Έχει λογική — το λάδι λιπαίνει και διεγείρει την πέψη — αλλά και όρια. Δείτε πώς να το χρησιμοποιείτε συνετά.",
    section="digestion", datePublished="2026-05-04", disclaimer=MED["el"],
    keywords="ελαιόλαδο δυσκοιλιότητα, ελαιόλαδο για δυσκοιλιότητα, ελαιόλαδο άδειο στομάχι, κουταλιά ελαιόλαδο έντερο",
    intro="Το ελαιόλαδο είναι από τις πιο γνωστές σπιτικές θεραπείες για περιστασιακή δυσκοιλιότητα. Δρα ως ήπιο λιπαντικό και διεγείρει τη χοληδόχο κύστη, κάτι που μπορεί να διευκολύνει τη διέλευση. Τα στοιχεία είναι περιορισμένα, αλλά η χρήση απλή και γενικά χαμηλού κινδύνου σε μικρές ποσότητες.",
    key_facts=[
        "Το ελαιόλαδο δρα ως ήπιο λιπαντικό και διεγείρει την έκκριση χολής, μαλακώνοντας τα κόπρανα.",
        "Συνήθης χρήση: 1 κουταλιά έξτρα παρθένο, συχνά με άδειο στομάχι το πρωί, ενίοτε με λεμόνι.",
        "Μικρές μελέτες (σε αιμοκαθαιρόμενους) βρήκαν δράση συγκρίσιμη με το ορυκτέλαιο.",
        "Δεν είναι θεραπεία για χρόνια δυσκοιλιότητα: νερό, φυτικές ίνες και άσκηση είναι η βάση.",
    ],
    sections=[
        ("Γιατί μπορεί να βοηθήσει",
         "<p>Το ελαιόλαδο δίνει λιπαρά που <strong>λιπαίνουν</strong> το εντερικό περιεχόμενο και κάνουν τα κόπρανα πιο ολισθηρά. Διεγείρει επίσης την <strong>έκκριση χολής</strong>, που βοηθά στην πέψη και τη διέλευση. Σε περιστασιακή δυσκοιλιότητα, μια μικρή δόση μπορεί να δώσει ώθηση.</p>"),
        ("Πώς να το χρησιμοποιείτε",
         "<p>Ο πιο κοινός τρόπος: <strong>1 κουταλιά έξτρα παρθένο ελαιόλαδο</strong>, το πρωί με άδειο στομάχι, προαιρετικά με λίγο λεμόνι. Κάποιοι το παίρνουν το βράδυ. Πιείτε νερό και εντάξτε το σε διατροφή πλούσια σε φυτικές ίνες.</p>"),
        ("Τι λένε οι μελέτες",
         "<p>Τα δεδομένα είναι περιορισμένα αλλά ενθαρρυντικά. Μελέτες σε αιμοκαθαιρόμενους, συχνά επιρρεπείς στη δυσκοιλιότητα, έδειξαν ότι το ελαιόλαδο μπορεί να βελτιώσει τη σύσταση και τη συχνότητα των κοπράνων, συγκρίσιμα με το ορυκτέλαιο.</p>"),
        ("Όρια και πότε να δείτε γιατρό",
         "<p>Το ελαιόλαδο δεν είναι ισχυρό καθαρτικό ούτε θεραπεία αιτίας. Μια κουταλιά είναι ~120 kcal. Δείτε γιατρό αν η δυσκοιλιότητα είναι <strong>χρόνια, επώδυνη, πρόσφατη και ανεξήγητη</strong>, ή με αίμα, απώλεια βάρους ή εμετό. Μη δίνετε λάδι σε βρέφος για αυτόν τον σκοπό χωρίς παιδιατρική συμβουλή.</p>"),
    ],
    faqs=[
        ("Βοηθά πραγματικά το ελαιόλαδο στη δυσκοιλιότητα;",
         "Μπορεί να βοηθήσει σε περιστασιακή δυσκοιλιότητα: λιπαίνει το εντερικό περιεχόμενο και διεγείρει τη χολή. Μικρές μελέτες δείχνουν πραγματική δράση, αλλά δεν είναι ισχυρό καθαρτικό."),
        ("Πόσο ελαιόλαδο για τη δυσκοιλιότητα;",
         "Συνήθως 1 κουταλιά έξτρα παρθένο, συχνά με άδειο στομάχι το πρωί. Δεν χρειάζεται περισσότερο: πέρα από αυτό προσθέτετε κυρίως θερμίδες."),
        ("Με άδειο στομάχι για το έντερο;",
         "Πολλοί το παίρνουν το πρωί με άδειο στομάχι, ενίοτε με λεμόνι. Δεν υπάρχει αυστηρή απόδειξη ότι η ώρα αλλάζει ουσιαστικά το αποτέλεσμα."),
        ("Ελαιόλαδο και λεμόνι λειτουργεί;",
         "Το μείγμα είναι δημοφιλές: το λάδι λιπαίνει, το λεμόνι δίνει φρεσκάδα. Η δράση προέρχεται κυρίως από το λάδι."),
        ("Πότε να δείτε γιατρό;",
         "Αν είναι χρόνια, επώδυνη, πρόσφατη και ανεξήγητη, ή με αίμα, πυρετό, εμετό ή απώλεια βάρους. Ο γιατρός πρέπει να εκτιμήσει την αιτία."),
    ],
)

# ================================================ BABY / DIVERSIFICATION =======
BB = {}
BB["fr"] = dict(
    title="Huile d'olive pour bébé : à partir de quel âge et comment l'utiliser ?",
    desc="Huile d'olive pour bébé : à partir de la diversification (vers 6 mois), un filet cru dans les purées. Quantité, intérêt nutritionnel, comment varier les matières grasses.",
    h1="Huile d'olive pour bébé : à partir de quel âge ?",
    lede="Ajouter un peu d'huile d'olive dans les purées de bébé est souvent recommandé dès le début de la diversification. Voici à partir de quand, en quelle quantité, et pourquoi les matières grasses sont importantes pour le nourrisson.",
    section="nutrition", datePublished="2026-05-04", disclaimer=MED["fr"],
    keywords="huile d'olive bébé, huile olive bebe quel age, matière grasse bébé diversification, huile d'olive purée bébé",
    intro="Contrairement aux idées reçues, les bébés ont besoin de matières grasses : elles apportent de l'énergie et des acides gras essentiels au développement. L'huile d'olive est l'une des options recommandées, ajoutée crue dans les purées dès la diversification. Voici comment faire, en s'en tenant aux repères pédiatriques.",
    key_facts=[
        "L'huile d'olive peut être introduite dès le début de la diversification, généralement vers 6 mois (selon l'avis de votre pédiatre).",
        "On l'ajoute crue, une cuillère à café environ, dans la purée de légumes une fois cuite.",
        "Elle apporte de l'énergie, des acides gras insaturés et de la vitamine E, utiles à la croissance.",
        "Variez les matières grasses (huile d'olive, huile de colza, un peu de beurre) plutôt que d'en utiliser une seule.",
    ],
    sections=[
        ("Pourquoi ajouter des matières grasses aux repas de bébé",
         "<p>Le cerveau et le corps du nourrisson se développent vite et ont besoin d'<strong>énergie</strong> et d'<strong>acides gras</strong>. Les purées de légumes maison sont pauvres en gras : y ajouter une matière grasse comme l'huile d'olive augmente l'apport énergétique et fournit des acides gras insaturés utiles au développement.</p>"),
        ("À partir de quel âge",
         "<p>L'huile d'olive peut être introduite <strong>dès le début de la diversification alimentaire</strong>, souvent autour de 6 mois, en même temps que les premiers légumes. Le moment exact de la diversification est individuel : suivez les recommandations de votre pédiatre ou des autorités de santé de votre pays.</p>"),
        ("Quelle quantité et comment",
         "<p>Ajoutez environ <strong>une cuillère à café d'huile d'olive crue</strong> dans la purée de légumes, une fois celle-ci cuite et tiédie. On ne fait pas frire les aliments de bébé : l'huile s'ajoute à froid, au moment de servir. Une texture lisse et un filet d'huile suffisent.</p>"),
        ("Varier les matières grasses",
         "<p>Les recommandations conseillent d'<strong>alterner les sources de matières grasses</strong> : huile d'olive, huile de colza (riche en oméga-3), et parfois un peu de beurre. Cette variété couvre mieux les besoins en différents acides gras que l'usage d'une seule huile.</p>"),
    ],
    faqs=[
        ("À partir de quel âge peut-on donner de l'huile d'olive à un bébé ?",
         "Généralement dès le début de la diversification, souvent vers 6 mois, ajoutée crue dans les purées. Le moment précis dépend de votre enfant : suivez l'avis de votre pédiatre."),
        ("Quelle quantité d'huile d'olive pour un bébé ?",
         "Environ une cuillère à café d'huile d'olive crue par purée de légumes suffit. L'objectif est d'enrichir le repas en bonnes graisses, pas d'en mettre beaucoup."),
        ("Faut-il cuire l'huile d'olive pour bébé ?",
         "Non. On l'ajoute crue dans la purée déjà cuite et tiédie, au moment de servir. On ne fait pas frire les repas des nourrissons."),
        ("Quelle huile choisir pour les repas de bébé ?",
         "L'huile d'olive extra vierge est une bonne option. Les recommandations conseillent de varier avec l'huile de colza (oméga-3) et un peu de beurre, plutôt qu'une seule matière grasse."),
        ("L'huile d'olive aide-t-elle bébé en cas de constipation ?",
         "Ne donnez pas d'huile d'olive à un nourrisson comme laxatif sans avis médical. En cas de constipation du bébé, parlez-en d'abord à votre pédiatre."),
    ],
)
BB["en"] = dict(
    title="Olive Oil for Babies: from what age and how to use it?",
    desc="Olive oil for babies: from the start of weaning (around 6 months), a raw drizzle in purées. Amount, nutritional value, and how to vary the fats.",
    h1="Olive Oil for Babies: from what age?",
    lede="Adding a little olive oil to a baby's purées is often recommended from the start of weaning. Here's from when, how much, and why fats matter for infants.",
    section="nutrition", datePublished="2026-05-04", disclaimer=MED["en"],
    keywords="olive oil for babies, olive oil baby age, fat baby weaning, olive oil baby purée",
    intro="Contrary to common belief, babies need fats: they provide energy and essential fatty acids for development. Olive oil is one of the recommended options, added raw to purées from the start of weaning. Here's how, keeping to paediatric guidance.",
    key_facts=[
        "Olive oil can be introduced from the start of weaning, generally around 6 months (per your paediatrician's advice).",
        "Add it raw, about a teaspoon, to the vegetable purée once cooked.",
        "It provides energy, unsaturated fatty acids and vitamin E, useful for growth.",
        "Vary the fats (olive oil, rapeseed/canola oil, a little butter) rather than using only one.",
    ],
    sections=[
        ("Why add fat to a baby's meals",
         "<p>An infant's brain and body develop fast and need <strong>energy</strong> and <strong>fatty acids</strong>. Homemade vegetable purées are low in fat: adding a fat such as olive oil raises the energy content and provides unsaturated fatty acids useful for development.</p>"),
        ("From what age",
         "<p>Olive oil can be introduced <strong>from the start of complementary feeding</strong>, often around 6 months, alongside the first vegetables. The exact timing of weaning is individual: follow the recommendations of your paediatrician or your country's health authorities.</p>"),
        ("How much and how",
         "<p>Add about <strong>a teaspoon of raw olive oil</strong> to the vegetable purée once it is cooked and cooled to warm. You don't fry baby food: the oil is added cold, at serving time. A smooth texture and a drizzle of oil are enough.</p>"),
        ("Varying the fats",
         "<p>Guidance advises <strong>alternating fat sources</strong>: olive oil, rapeseed/canola oil (rich in omega-3), and sometimes a little butter. This variety covers the needs for different fatty acids better than using a single oil.</p>"),
    ],
    faqs=[
        ("From what age can you give a baby olive oil?",
         "Generally from the start of weaning, often around 6 months, added raw to purées. The precise timing depends on your child: follow your paediatrician's advice."),
        ("How much olive oil for a baby?",
         "About a teaspoon of raw olive oil per vegetable purée is enough. The goal is to enrich the meal with good fats, not to add a lot."),
        ("Should olive oil for a baby be cooked?",
         "No. Add it raw to the already-cooked, warm purée at serving time. You don't fry infant meals."),
        ("Which oil to choose for baby meals?",
         "Extra virgin olive oil is a good option. Guidance advises varying with rapeseed/canola oil (omega-3) and a little butter, rather than a single fat."),
        ("Does olive oil help a baby with constipation?",
         "Do not give olive oil to an infant as a laxative without medical advice. For a baby's constipation, speak to your paediatrician first."),
    ],
)
BB["it"] = dict(
    title="Olio d'oliva per il neonato: da che età e come usarlo?",
    desc="Olio d'oliva per il bambino: dall'inizio dello svezzamento (verso 6 mesi), un filo a crudo nelle pappe. Quantità, valore nutrizionale e come variare i grassi.",
    h1="Olio d'oliva per il neonato: da che età?",
    lede="Aggiungere un po' d'olio d'oliva alle pappe è spesso consigliato dall'inizio dello svezzamento. Ecco da quando, quanto e perché i grassi sono importanti per il lattante.",
    section="nutrition", datePublished="2026-05-04", disclaimer=MED["it"],
    keywords="olio d'oliva neonato, olio d'oliva bambino età, grassi svezzamento, olio d'oliva pappa",
    intro="Contrariamente a quanto si crede, i bambini hanno bisogno di grassi: forniscono energia e acidi grassi essenziali per lo sviluppo. L'olio d'oliva è una delle opzioni consigliate, aggiunto a crudo nelle pappe dall'inizio dello svezzamento.",
    key_facts=[
        "L'olio d'oliva si può introdurre dall'inizio dello svezzamento, in genere verso 6 mesi (secondo il pediatra).",
        "Si aggiunge a crudo, circa un cucchiaino, nella pappa di verdure già cotta.",
        "Fornisce energia, acidi grassi insaturi e vitamina E, utili alla crescita.",
        "Varia i grassi (olio d'oliva, olio di colza, un po' di burro) invece di usarne uno solo.",
    ],
    sections=[
        ("Perché aggiungere grassi ai pasti del bambino",
         "<p>Il cervello e il corpo del lattante si sviluppano in fretta e hanno bisogno di <strong>energia</strong> e <strong>acidi grassi</strong>. Le pappe di verdure fatte in casa sono povere di grassi: aggiungere un grasso come l'olio d'oliva aumenta l'apporto energetico e fornisce acidi grassi insaturi utili allo sviluppo.</p>"),
        ("Da che età",
         "<p>L'olio d'oliva si può introdurre <strong>dall'inizio dell'alimentazione complementare</strong>, spesso verso i 6 mesi, insieme alle prime verdure. Il momento esatto è individuale: segui le indicazioni del pediatra o delle autorità sanitarie del tuo paese.</p>"),
        ("Quanto e come",
         "<p>Aggiungi circa <strong>un cucchiaino di olio d'oliva a crudo</strong> nella pappa di verdure una volta cotta e intiepidita. Non si frigge il cibo del bambino: l'olio si aggiunge a freddo, al momento di servire.</p>"),
        ("Variare i grassi",
         "<p>Le indicazioni consigliano di <strong>alternare le fonti di grassi</strong>: olio d'oliva, olio di colza (ricco di omega-3) e a volte un po' di burro. Questa varietà copre meglio il bisogno di diversi acidi grassi.</p>"),
    ],
    faqs=[
        ("Da che età si può dare l'olio d'oliva a un neonato?",
         "In genere dall'inizio dello svezzamento, spesso verso 6 mesi, aggiunto a crudo nelle pappe. Il momento preciso dipende dal bambino: segui il pediatra."),
        ("Quanto olio d'oliva per un neonato?",
         "Circa un cucchiaino a crudo per pappa di verdure. L'obiettivo è arricchire il pasto di grassi buoni, non metterne molto."),
        ("L'olio d'oliva per il neonato va cotto?",
         "No. Si aggiunge a crudo nella pappa già cotta e tiepida, al momento di servire."),
        ("Quale olio scegliere per le pappe?",
         "L'olio extravergine è una buona opzione. Le indicazioni consigliano di variare con olio di colza (omega-3) e un po' di burro."),
        ("L'olio d'oliva aiuta il neonato con la stitichezza?",
         "Non dare olio d'oliva a un lattante come lassativo senza parere medico. Per la stitichezza del bambino, parlane prima col pediatra."),
    ],
)
BB["el"] = dict(
    title="Ελαιόλαδο για το μωρό: από ποια ηλικία και πώς να το χρησιμοποιείτε;",
    desc="Ελαιόλαδο για το μωρό: από την έναρξη των στερεών (γύρω στους 6 μήνες), λίγο ωμό στους πουρέδες. Ποσότητα, διατροφική αξία και πώς να ποικίλλετε τα λιπαρά.",
    h1="Ελαιόλαδο για το μωρό: από ποια ηλικία;",
    lede="Η προσθήκη λίγου ελαιόλαδου στους πουρέδες του μωρού συχνά συνιστάται από την έναρξη των στερεών. Δείτε από πότε, πόσο και γιατί τα λιπαρά είναι σημαντικά για το βρέφος.",
    section="nutrition", datePublished="2026-05-04", disclaimer=MED["el"],
    keywords="ελαιόλαδο μωρό, ελαιόλαδο βρέφος ηλικία, λιπαρά στερεές τροφές, ελαιόλαδο πουρές μωρού",
    intro="Σε αντίθεση με τη διαδεδομένη αντίληψη, τα μωρά χρειάζονται λιπαρά: δίνουν ενέργεια και απαραίτητα λιπαρά οξέα για την ανάπτυξη. Το ελαιόλαδο είναι μία από τις συνιστώμενες επιλογές, προστιθέμενο ωμό στους πουρέδες από την έναρξη των στερεών.",
    key_facts=[
        "Το ελαιόλαδο μπορεί να εισαχθεί από την έναρξη των στερεών, συνήθως γύρω στους 6 μήνες (κατά τον παιδίατρο).",
        "Προστίθεται ωμό, περίπου ένα κουταλάκι, στον πουρέ λαχανικών αφού μαγειρευτεί.",
        "Δίνει ενέργεια, ακόρεστα λιπαρά οξέα και βιταμίνη E, χρήσιμα στην ανάπτυξη.",
        "Ποικίλλετε τα λιπαρά (ελαιόλαδο, λάδι κράμβης, λίγο βούτυρο) αντί για ένα μόνο.",
    ],
    sections=[
        ("Γιατί να προσθέτετε λιπαρά στα γεύματα του μωρού",
         "<p>Ο εγκέφαλος και το σώμα του βρέφους αναπτύσσονται γρήγορα και χρειάζονται <strong>ενέργεια</strong> και <strong>λιπαρά οξέα</strong>. Οι σπιτικοί πουρέδες λαχανικών είναι φτωχοί σε λιπαρά: η προσθήκη ελαιόλαδου αυξάνει την ενέργεια και δίνει ακόρεστα λιπαρά οξέα χρήσιμα στην ανάπτυξη.</p>"),
        ("Από ποια ηλικία",
         "<p>Το ελαιόλαδο μπορεί να εισαχθεί <strong>από την έναρξη των συμπληρωματικών τροφών</strong>, συχνά γύρω στους 6 μήνες, μαζί με τα πρώτα λαχανικά. Ο ακριβής χρόνος είναι ατομικός: ακολουθήστε τις οδηγίες του παιδιάτρου ή των αρχών υγείας.</p>"),
        ("Πόσο και πώς",
         "<p>Προσθέστε περίπου <strong>ένα κουταλάκι ωμό ελαιόλαδο</strong> στον πουρέ λαχανικών αφού μαγειρευτεί και χλιάνει. Δεν τηγανίζουμε το φαγητό του μωρού: το λάδι μπαίνει κρύο, στο σερβίρισμα.</p>"),
        ("Ποικιλία στα λιπαρά",
         "<p>Οι οδηγίες συνιστούν <strong>εναλλαγή πηγών λιπαρών</strong>: ελαιόλαδο, λάδι κράμβης (πλούσιο σε ωμέγα-3) και ενίοτε λίγο βούτυρο. Η ποικιλία καλύπτει καλύτερα τις ανάγκες σε διαφορετικά λιπαρά οξέα.</p>"),
    ],
    faqs=[
        ("Από ποια ηλικία δίνουμε ελαιόλαδο στο μωρό;",
         "Γενικά από την έναρξη των στερεών, συχνά γύρω στους 6 μήνες, ωμό στους πουρέδες. Ο ακριβής χρόνος εξαρτάται από το παιδί: ακολουθήστε τον παιδίατρο."),
        ("Πόσο ελαιόλαδο για το μωρό;",
         "Περίπου ένα κουταλάκι ωμό ανά πουρέ λαχανικών αρκεί. Στόχος είναι να εμπλουτίσετε το γεύμα με καλά λιπαρά, όχι να βάλετε πολύ."),
        ("Πρέπει να μαγειρεύεται το ελαιόλαδο για το μωρό;",
         "Όχι. Προστίθεται ωμό στον ήδη μαγειρεμένο, χλιαρό πουρέ, στο σερβίρισμα."),
        ("Ποιο λάδι για τα γεύματα του μωρού;",
         "Το έξτρα παρθένο ελαιόλαδο είναι καλή επιλογή. Οι οδηγίες συνιστούν εναλλαγή με λάδι κράμβης (ωμέγα-3) και λίγο βούτυρο."),
        ("Βοηθά το ελαιόλαδο το μωρό στη δυσκοιλιότητα;",
         "Μη δίνετε ελαιόλαδο σε βρέφος ως καθαρτικό χωρίς ιατρική συμβουλή. Για δυσκοιλιότητα του μωρού, μιλήστε πρώτα στον παιδίατρο."),
    ],
)

if __name__ == "__main__":
    print("Batch 4:")
    write_guide_cluster("huile-olive-psoriasis-eczema", E)
    write_guide_cluster("huile-olive-contre-constipation", CO)
    write_guide_cluster("huile-olive-bebe-diversification", BB)
