# -*- coding: utf-8 -*-
"""Authentic Aioli + Bruschetta tomate-basilic x4 languages."""
from recipe_render import write_cluster

# ===================================================================== AIOLI ==
A = {}
A["fr"] = dict(
    title="Aïoli maison : la vraie recette de la sauce à l'ail et à l'huile d'olive",
    desc="Vrai aïoli maison : émulsion d'ail et d'huile d'olive, montée au mortier. Méthode, astuce anti-amertume, que faire si l'aïoli tranche, et avec quoi le servir.",
    h1="Aïoli maison à l'huile d'olive",
    lede="L'aïoli, c'est de l'ail et de l'huile d'olive montés en émulsion crémeuse. Voici la méthode traditionnelle au mortier, l'astuce pour éviter l'amertume et le rattrapage si la sauce tranche.",
    info="<strong>Préparation :</strong> 15 min · <strong>Cuisson :</strong> 0 min · <strong>Pour :</strong> 4 personnes · <strong>Cuisine :</strong> provençale / méditerranéenne · <strong>Difficulté :</strong> moyenne",
    intro="Dans sa forme la plus pure (l'<em>all i oli</em> catalan), l'aïoli n'est qu'ail, sel et huile d'olive montés à la force du poignet. En Provence, on stabilise souvent l'émulsion avec un jaune d'œuf. Dans les deux cas, tout se joue sur une chose : incorporer l'huile très progressivement.",
    ingredients=[
        "4 gousses d'ail",
        "1 jaune d'œuf (version provençale, à température ambiante)",
        "200 ml d'huile d'olive (voir l'astuce anti-amertume)",
        "1 c. à café de jus de citron",
        "Sel",
    ],
    steps=[
        "<strong>Piler l'ail.</strong> Dans un mortier, écrasez l'ail avec une pincée de sel jusqu'à obtenir une pâte lisse.",
        "<strong>Le jaune.</strong> Ajoutez le jaune d'œuf (version provençale) et mélangez.",
        "<strong>Monter à l'huile.</strong> Versez l'huile d'olive goutte à goutte au début, en tournant sans arrêt, jusqu'à ce que l'émulsion prenne. Continuez ensuite en filet fin jusqu'à une sauce épaisse et crémeuse.",
        "<strong>Assaisonner.</strong> Ajoutez le jus de citron et rectifiez le sel. L'aïoli doit napper la cuillère.",
    ],
    oil="L'huile d'olive est l'âme de l'aïoli, mais attention : une huile extra vierge très intense, montée en émulsion, peut devenir <strong>amère, voire piquante</strong> (les polyphénols se libèrent). Pour un aïoli doux, utilisez une huile d'olive fruitée légère, ou coupez une extra vierge de caractère avec une huile plus neutre. Montez à la main plutôt qu'au robot, qui accentue l'amertume.",
    tips=[
        "Tous les ingrédients à température ambiante : une émulsion froide prend mal.",
        "Au début, l'huile goutte à goutte : c'est là que l'émulsion se crée.",
        "Huile pas trop amère et montage à la main pour éviter l'amertume.",
        "Si l'aïoli tranche, repartez d'un jaune neuf et réincorporez la sauce ratée petit à petit.",
    ],
    variations=[
        "<strong>All i oli pur (sans œuf) :</strong> uniquement ail, sel et huile d'olive — plus délicat à monter.",
        "<strong>Aïoli express :</strong> une cuillère de mayonnaise + ail pilé pour dépanner.",
    ],
    serve="L'aïoli se sert avec des légumes croquants, du poisson poché, des pommes de terre, des œufs durs, ou dans le grand aïoli provençal (morue et légumes). C'est aussi une sauce parfaite pour tremper du pain ou accompagner des grillades.",
    store="À conserver au réfrigérateur, dans un bocal fermé, 1 à 2 jours maximum (il contient de l'ail cru et un jaune d'œuf cru). Ne le laissez pas à température ambiante. Déconseillé aux personnes sensibles à l'œuf cru (femmes enceintes, etc.).",
    faqs=[
        ("Quelle est la différence entre aïoli et mayonnaise ?",
         "L'aïoli est d'abord une émulsion d'ail et d'huile d'olive ; la mayonnaise est une émulsion de jaune d'œuf, moutarde et huile neutre. La version provençale de l'aïoli ajoute un jaune, mais l'ail et l'huile d'olive restent la signature."),
        ("Pourquoi mon aïoli est-il amer ?",
         "Souvent à cause d'une huile d'olive extra vierge très intense montée au robot : l'émulsion libère les polyphénols et rend la sauce amère. Utilisez une huile plus douce et montez à la main."),
        ("Que faire si l'aïoli tranche ?",
         "Recommencez dans un bol propre avec un jaune d'œuf neuf, puis incorporez la sauce ratée cuillère par cuillère, comme une nouvelle huile, jusqu'à ce que l'émulsion reprenne."),
        ("Peut-on faire un aïoli sans œuf ?",
         "Oui, c'est l'all i oli traditionnel : ail, sel et huile d'olive uniquement. Il demande plus de patience car l'émulsion est moins stable."),
        ("Avec quoi servir l'aïoli ?",
         "Légumes crus ou vapeur, poisson, pommes de terre, œufs durs, pain grillé, ou le grand aïoli provençal avec morue et légumes."),
    ],
    schema_name="Aïoli maison à l'huile d'olive",
    schema_desc="Vrai aïoli maison : émulsion d'ail et d'huile d'olive montée au mortier, avec un jaune d'œuf (version provençale).",
    schema_ing=["4 gousses d'ail", "1 jaune d'œuf", "200 ml huile d'olive", "1 c. à café jus de citron", "sel"],
    schema_steps=[
        "Piler l'ail avec du sel en pâte.",
        "Ajouter le jaune d'œuf.",
        "Monter en versant l'huile d'olive goutte à goutte puis en filet.",
        "Assaisonner de citron et de sel."],
    keywords="aioli, aïoli maison, recette aioli, sauce ail huile d'olive, all i oli",
    cuisine="Mediterranean", category="Sauce", prep="PT15M", cook="PT0M", total="PT15M", yield_="4 servings",
    nutrition={"servingSize": "1 c. à soupe", "calories": "120 kcal", "fatContent": "13 g", "proteinContent": "0 g", "carbohydrateContent": "0 g"},
)
A["en"] = dict(
    title="Homemade Aioli: the real garlic and olive oil sauce recipe",
    desc="Real homemade aioli: an emulsion of garlic and olive oil, made in a mortar. Method, the anti-bitterness trick, what to do if it splits, and what to serve it with.",
    h1="Homemade Aioli with olive oil",
    lede="Aioli is garlic and olive oil whipped into a creamy emulsion. Here is the traditional mortar method, the trick to avoid bitterness, and how to rescue it if it splits.",
    info="<strong>Prep:</strong> 15 min · <strong>Cook:</strong> 0 min · <strong>Serves:</strong> 4 · <strong>Cuisine:</strong> Provençal / Mediterranean · <strong>Difficulty:</strong> medium",
    intro="In its purest form (Catalan <em>all i oli</em>), aioli is nothing but garlic, salt and olive oil whipped by hand. In Provence, an egg yolk is often added to stabilise the emulsion. Either way, it all comes down to one thing: add the oil very gradually.",
    ingredients=[
        "4 garlic cloves",
        "1 egg yolk (Provençal version, at room temperature)",
        "200 ml olive oil (see the anti-bitterness tip)",
        "1 tsp lemon juice",
        "Salt",
    ],
    steps=[
        "<strong>Pound the garlic.</strong> In a mortar, crush the garlic with a pinch of salt into a smooth paste.",
        "<strong>The yolk.</strong> Add the egg yolk (Provençal version) and mix.",
        "<strong>Build the emulsion.</strong> Add the olive oil drop by drop at first, stirring constantly, until the emulsion takes. Then continue in a thin stream to a thick, creamy sauce.",
        "<strong>Season.</strong> Add the lemon juice and adjust salt. Aioli should coat the spoon.",
    ],
    oil="Olive oil is the soul of aioli, but beware: a very intense extra virgin oil, whipped into an emulsion, can turn <strong>bitter, even pungent</strong> (the polyphenols are released). For a mild aioli, use a light fruity olive oil, or cut a characterful extra virgin with a more neutral oil. Whip by hand rather than in a machine, which amplifies bitterness.",
    tips=[
        "All ingredients at room temperature: a cold emulsion takes poorly.",
        "At first, oil drop by drop: that's where the emulsion is born.",
        "A milder oil and hand-whipping avoid bitterness.",
        "If it splits, start with a fresh yolk and re-incorporate the failed sauce little by little.",
    ],
    variations=[
        "<strong>Pure all i oli (no egg):</strong> garlic, salt and olive oil only — trickier to emulsify.",
        "<strong>Quick aioli:</strong> a spoon of mayonnaise + crushed garlic in a pinch.",
    ],
    serve="Serve aioli with crunchy vegetables, poached fish, potatoes, hard-boiled eggs, or in the Provençal grand aïoli (salt cod and vegetables). It's also a perfect dip for bread or grilled food.",
    store="Keep it in the fridge, in a closed jar, 1–2 days maximum (it contains raw garlic and a raw egg yolk). Do not leave it at room temperature. Not advised for those sensitive to raw egg (pregnant women, etc.).",
    faqs=[
        ("What's the difference between aioli and mayonnaise?",
         "Aioli is first an emulsion of garlic and olive oil; mayonnaise is an emulsion of egg yolk, mustard and neutral oil. The Provençal aioli adds a yolk, but garlic and olive oil remain the signature."),
        ("Why is my aioli bitter?",
         "Often because of a very intense extra virgin olive oil whipped in a machine: the emulsion releases polyphenols and makes the sauce bitter. Use a milder oil and whip by hand."),
        ("What do I do if aioli splits?",
         "Start again in a clean bowl with a fresh egg yolk, then add the failed sauce spoon by spoon, like fresh oil, until the emulsion comes back."),
        ("Can you make aioli without egg?",
         "Yes, that's the traditional all i oli: garlic, salt and olive oil only. It takes more patience because the emulsion is less stable."),
        ("What do you serve with aioli?",
         "Raw or steamed vegetables, fish, potatoes, hard-boiled eggs, toasted bread, or the Provençal grand aïoli with salt cod and vegetables."),
    ],
    schema_name="Homemade Aioli with olive oil",
    schema_desc="Real homemade aioli: an emulsion of garlic and olive oil made in a mortar, with an egg yolk (Provençal version).",
    schema_ing=["4 garlic cloves", "1 egg yolk", "200 ml olive oil", "1 tsp lemon juice", "salt"],
    schema_steps=[
        "Pound garlic with salt into a paste.",
        "Add the egg yolk.",
        "Build the emulsion adding olive oil drop by drop then in a stream.",
        "Season with lemon and salt."],
    keywords="aioli, homemade aioli, aioli recipe, garlic olive oil sauce, all i oli",
    cuisine="Mediterranean", category="Sauce", prep="PT15M", cook="PT0M", total="PT15M", yield_="4 servings",
    nutrition={"servingSize": "1 tbsp", "calories": "120 kcal", "fatContent": "13 g", "proteinContent": "0 g", "carbohydrateContent": "0 g"},
)
A["it"] = dict(
    title="Aioli fatto in casa: la vera ricetta della salsa all'aglio e olio d'oliva",
    desc="Vero aioli fatto in casa: emulsione di aglio e olio d'oliva al mortaio. Metodo, trucco anti-amaro, cosa fare se impazzisce e con cosa servirlo.",
    h1="Aioli fatto in casa all'olio d'oliva",
    lede="L'aioli è aglio e olio d'oliva montati in un'emulsione cremosa. Ecco il metodo tradizionale al mortaio, il trucco per evitare l'amaro e come recuperarlo se impazzisce.",
    info="<strong>Preparazione:</strong> 15 min · <strong>Cottura:</strong> 0 min · <strong>Per:</strong> 4 persone · <strong>Cucina:</strong> provenzale / mediterranea · <strong>Difficoltà:</strong> media",
    intro="Nella forma più pura (l'<em>all i oli</em> catalano), l'aioli è solo aglio, sale e olio d'oliva montati a mano. In Provenza si stabilizza spesso con un tuorlo. In entrambi i casi conta una cosa: incorporare l'olio molto gradualmente.",
    ingredients=[
        "4 spicchi d'aglio",
        "1 tuorlo d'uovo (versione provenzale, a temperatura ambiente)",
        "200 ml di olio d'oliva (vedi il trucco anti-amaro)",
        "1 cucchiaino di succo di limone",
        "Sale",
    ],
    steps=[
        "<strong>Pestare l'aglio.</strong> Nel mortaio, schiaccia l'aglio con un pizzico di sale fino a una pasta liscia.",
        "<strong>Il tuorlo.</strong> Aggiungi il tuorlo (versione provenzale) e mescola.",
        "<strong>Montare con l'olio.</strong> Versa l'olio d'oliva goccia a goccia all'inizio, mescolando senza sosta, finché l'emulsione prende. Continua a filo fino a una salsa densa e cremosa.",
        "<strong>Condire.</strong> Aggiungi il succo di limone e regola il sale. L'aioli deve velare il cucchiaio.",
    ],
    oil="L'olio d'oliva è l'anima dell'aioli, ma attenzione: un extravergine molto intenso, montato in emulsione, può diventare <strong>amaro, persino piccante</strong> (si liberano i polifenoli). Per un aioli dolce, usa un olio fruttato leggero, o taglia un extravergine deciso con un olio più neutro. Monta a mano più che a macchina.",
    tips=[
        "Tutti gli ingredienti a temperatura ambiente: un'emulsione fredda prende male.",
        "All'inizio olio goccia a goccia: lì nasce l'emulsione.",
        "Olio non troppo amaro e montatura a mano per evitare l'amaro.",
        "Se impazzisce, riparti da un tuorlo nuovo e reincorpora la salsa fallita poco a poco.",
    ],
    variations=[
        "<strong>All i oli puro (senza uovo):</strong> solo aglio, sale e olio d'oliva — più difficile da montare.",
        "<strong>Aioli veloce:</strong> un cucchiaio di maionese + aglio pestato per rimediare.",
    ],
    serve="L'aioli si serve con verdure croccanti, pesce lessato, patate, uova sode, o nel grand aïoli provenzale (baccalà e verdure). È anche una salsa perfetta per intingere pane o accompagnare grigliate.",
    store="Conserva in frigorifero, in un vasetto chiuso, 1–2 giorni al massimo (contiene aglio crudo e tuorlo crudo). Non lasciarlo a temperatura ambiente. Sconsigliato a chi è sensibile all'uovo crudo (gravidanza, ecc.).",
    faqs=[
        ("Qual è la differenza tra aioli e maionese?",
         "L'aioli è prima di tutto un'emulsione di aglio e olio d'oliva; la maionese è un'emulsione di tuorlo, senape e olio neutro. La versione provenzale aggiunge un tuorlo, ma aglio e olio d'oliva restano la firma."),
        ("Perché il mio aioli è amaro?",
         "Spesso per un extravergine molto intenso montato a macchina: l'emulsione libera i polifenoli e rende la salsa amara. Usa un olio più dolce e monta a mano."),
        ("Cosa fare se l'aioli impazzisce?",
         "Ricomincia in una ciotola pulita con un tuorlo nuovo, poi incorpora la salsa fallita un cucchiaio alla volta, come nuovo olio, finché l'emulsione riparte."),
        ("Si può fare l'aioli senza uovo?",
         "Sì, è l'all i oli tradizionale: solo aglio, sale e olio d'oliva. Richiede più pazienza perché l'emulsione è meno stabile."),
        ("Con cosa servire l'aioli?",
         "Verdure crude o al vapore, pesce, patate, uova sode, pane tostato, o il grand aïoli provenzale con baccalà e verdure."),
    ],
    schema_name="Aioli fatto in casa all'olio d'oliva",
    schema_desc="Vero aioli fatto in casa: emulsione di aglio e olio d'oliva al mortaio, con un tuorlo (versione provenzale).",
    schema_ing=["4 spicchi d'aglio", "1 tuorlo d'uovo", "200 ml olio d'oliva", "1 cucchiaino succo di limone", "sale"],
    schema_steps=[
        "Pestare l'aglio con sale in pasta.",
        "Aggiungere il tuorlo.",
        "Montare versando l'olio d'oliva goccia a goccia poi a filo.",
        "Condire con limone e sale."],
    keywords="aioli, aioli fatto in casa, ricetta aioli, salsa aglio olio d'oliva, all i oli",
    cuisine="Mediterranean", category="Salsa", prep="PT15M", cook="PT0M", total="PT15M", yield_="4 porzioni",
    nutrition={"servingSize": "1 cucchiaio", "calories": "120 kcal", "fatContent": "13 g", "proteinContent": "0 g", "carbohydrateContent": "0 g"},
)
A["el"] = dict(
    title="Αϊόλι σπιτικό: η αυθεντική συνταγή για σάλτσα σκόρδου με ελαιόλαδο",
    desc="Αληθινό σπιτικό αϊόλι: γαλάκτωμα σκόρδου και ελαιόλαδου στο γουδί. Μέθοδος, κόλπο κατά της πικράδας, τι κάνετε αν κόψει και με τι σερβίρεται.",
    h1="Αϊόλι σπιτικό με ελαιόλαδο",
    lede="Το αϊόλι είναι σκόρδο και ελαιόλαδο χτυπημένα σε κρεμώδες γαλάκτωμα. Δείτε την παραδοσιακή μέθοδο στο γουδί, το κόλπο κατά της πικράδας και πώς το σώζετε αν κόψει.",
    info="<strong>Προετοιμασία:</strong> 15 λεπτά · <strong>Μαγείρεμα:</strong> 0 λεπτά · <strong>Μερίδες:</strong> 4 · <strong>Κουζίνα:</strong> προβηγκιανή / μεσογειακή · <strong>Δυσκολία:</strong> μέτρια",
    intro="Στην πιο αγνή μορφή του (το καταλανικό <em>all i oli</em>), το αϊόλι είναι μόνο σκόρδο, αλάτι και ελαιόλαδο χτυπημένα στο χέρι. Στην Προβηγκία συχνά σταθεροποιείται με έναν κρόκο. Και στις δύο περιπτώσεις μετράει ένα: να προσθέτετε το λάδι πολύ σταδιακά.",
    ingredients=[
        "4 σκελίδες σκόρδο",
        "1 κρόκος αυγού (προβηγκιανή εκδοχή, σε θερμοκρασία δωματίου)",
        "200 ml ελαιόλαδο (δείτε το κόλπο κατά της πικράδας)",
        "1 κ.γ. χυμό λεμονιού",
        "Αλάτι",
    ],
    steps=[
        "<strong>Λιώστε το σκόρδο.</strong> Στο γουδί, λιώστε το σκόρδο με λίγο αλάτι σε λεία πάστα.",
        "<strong>Ο κρόκος.</strong> Προσθέστε τον κρόκο (προβηγκιανή εκδοχή) και ανακατέψτε.",
        "<strong>Χτυπήστε με το λάδι.</strong> Ρίξτε το ελαιόλαδο σταγόνα-σταγόνα στην αρχή, ανακατεύοντας συνεχώς, μέχρι να δέσει το γαλάκτωμα. Συνεχίστε σε λεπτή ροή μέχρι πηχτή, κρεμώδη σάλτσα.",
        "<strong>Καρυκεύστε.</strong> Προσθέστε τον χυμό λεμονιού και ρυθμίστε το αλάτι.",
    ],
    oil="Το ελαιόλαδο είναι η ψυχή του αϊόλι, αλλά προσοχή: ένα πολύ έντονο έξτρα παρθένο, χτυπημένο σε γαλάκτωμα, μπορεί να γίνει <strong>πικρό, ακόμη και καυτερό</strong> (απελευθερώνονται οι πολυφαινόλες). Για απαλό αϊόλι, χρησιμοποιήστε ένα ελαφρύ φρουτώδες λάδι ή αραιώστε ένα έντονο έξτρα παρθένο. Χτυπήστε στο χέρι, όχι σε μηχανή.",
    tips=[
        "Όλα τα υλικά σε θερμοκρασία δωματίου: το κρύο γαλάκτωμα δεν δένει.",
        "Στην αρχή λάδι σταγόνα-σταγόνα: εκεί γεννιέται το γαλάκτωμα.",
        "Πιο απαλό λάδι και χτύπημα στο χέρι κατά της πικράδας.",
        "Αν κόψει, ξεκινήστε με νέο κρόκο και ενσωματώστε τη χαλασμένη σάλτσα σιγά-σιγά.",
    ],
    variations=[
        "<strong>Καθαρό all i oli (χωρίς αυγό):</strong> μόνο σκόρδο, αλάτι και ελαιόλαδο — πιο δύσκολο να δέσει.",
        "<strong>Γρήγορο αϊόλι:</strong> μια κουταλιά μαγιονέζα + λιωμένο σκόρδο.",
    ],
    serve="Το αϊόλι σερβίρεται με τραγανά λαχανικά, ποσέ ψάρι, πατάτες, βραστά αυγά, ή στο προβηγκιανό grand aïoli (μπακαλιάρος και λαχανικά). Είναι και τέλειο ντιπ για ψωμί ή ψητά.",
    store="Διατηρήστε στο ψυγείο, σε κλειστό βαζάκι, 1–2 ημέρες το πολύ (περιέχει ωμό σκόρδο και ωμό κρόκο). Μην το αφήνετε σε θερμοκρασία δωματίου. Δεν συνιστάται σε ευαίσθητους στο ωμό αυγό (εγκυμοσύνη κ.λπ.).",
    faqs=[
        ("Ποια η διαφορά αϊόλι και μαγιονέζας;",
         "Το αϊόλι είναι πρώτα γαλάκτωμα σκόρδου και ελαιόλαδου· η μαγιονέζα είναι γαλάκτωμα κρόκου, μουστάρδας και ουδέτερου λαδιού. Η προβηγκιανή εκδοχή προσθέτει κρόκο, αλλά σκόρδο και ελαιόλαδο μένουν η υπογραφή."),
        ("Γιατί το αϊόλι μου είναι πικρό;",
         "Συχνά λόγω πολύ έντονου έξτρα παρθένου χτυπημένου σε μηχανή: το γαλάκτωμα απελευθερώνει πολυφαινόλες. Χρησιμοποιήστε πιο απαλό λάδι και χτυπήστε στο χέρι."),
        ("Τι κάνω αν κόψει το αϊόλι;",
         "Ξεκινήστε ξανά σε καθαρό μπολ με νέο κρόκο και ενσωματώστε τη χαλασμένη σάλτσα κουταλιά-κουταλιά, σαν νέο λάδι."),
        ("Γίνεται αϊόλι χωρίς αυγό;",
         "Ναι, είναι το παραδοσιακό all i oli: μόνο σκόρδο, αλάτι και ελαιόλαδο. Θέλει υπομονή γιατί το γαλάκτωμα είναι λιγότερο σταθερό."),
        ("Με τι σερβίρεται το αϊόλι;",
         "Ωμά ή στον ατμό λαχανικά, ψάρι, πατάτες, βραστά αυγά, ψωμί, ή το προβηγκιανό grand aïoli με μπακαλιάρο και λαχανικά."),
    ],
    schema_name="Αϊόλι σπιτικό με ελαιόλαδο",
    schema_desc="Αληθινό σπιτικό αϊόλι: γαλάκτωμα σκόρδου και ελαιόλαδου στο γουδί, με κρόκο (προβηγκιανή εκδοχή).",
    schema_ing=["4 σκελίδες σκόρδο", "1 κρόκος αυγού", "200 ml ελαιόλαδο", "1 κ.γ. χυμό λεμονιού", "αλάτι"],
    schema_steps=[
        "Λιώστε το σκόρδο με αλάτι σε πάστα.",
        "Προσθέστε τον κρόκο.",
        "Χτυπήστε προσθέτοντας ελαιόλαδο σταγόνα-σταγόνα και μετά σε ροή.",
        "Καρυκεύστε με λεμόνι και αλάτι."],
    keywords="αϊόλι, σπιτικό αϊόλι, συνταγή αϊόλι, σάλτσα σκόρδου ελαιόλαδο, all i oli",
    cuisine="Mediterranean", category="Σάλτσα", prep="PT15M", cook="PT0M", total="PT15M", yield_="4 μερίδες",
    nutrition={"servingSize": "1 κ.σ.", "calories": "120 kcal", "fatContent": "13 g", "proteinContent": "0 g", "carbohydrateContent": "0 g"},
)

# ================================================================ BRUSCHETTA ==
B = {}
B["fr"] = dict(
    title="Bruschetta tomate-basilic : la vraie recette italienne à l'huile d'olive",
    desc="Vraie bruschetta tomate-basilic : pain grillé frotté à l'ail, tomates mûres, basilic et huile d'olive extra vierge. Astuce pour un pain croustillant et des tomates non détrempées.",
    h1="Bruschetta tomate-basilic",
    lede="La bruschetta authentique, c'est d'abord une belle tranche de pain grillée, frottée à l'ail et arrosée d'huile d'olive extra vierge. La garniture tomate-basilic vient ensuite, au dernier moment, pour garder le croustillant.",
    info="<strong>Préparation :</strong> 15 min · <strong>Cuisson :</strong> 5 min · <strong>Pour :</strong> 4 personnes · <strong>Cuisine :</strong> italienne · <strong>Difficulté :</strong> facile",
    intro="À l'origine, la <em>bruschetta</em> n'est qu'un pain grillé frotté d'ail et nappé d'huile d'olive nouvelle — une façon de goûter l'huile. La version tomate-basilic est la plus connue. Sa réussite tient à deux choses : un bon pain bien grillé et des tomates mûres que l'on ne pose qu'au dernier moment.",
    ingredients=[
        "4 tranches de pain de campagne (ou ciabatta)",
        "3 tomates mûres et fermes",
        "1 gousse d'ail",
        "Quelques feuilles de basilic frais",
        "4 c. à soupe d'huile d'olive extra vierge",
        "Sel, poivre",
    ],
    steps=[
        "<strong>Préparer les tomates.</strong> Coupez les tomates en petits dés, retirez l'excès de jus et de pépins, salez légèrement et laissez égoutter dans une passoire.",
        "<strong>Griller le pain.</strong> Faites griller les tranches de pain au four, au grille-pain ou à la poêle, jusqu'à ce qu'elles soient dorées et croustillantes.",
        "<strong>Frotter à l'ail.</strong> Frottez chaque tranche encore chaude avec la gousse d'ail coupée, puis arrosez d'un filet d'huile d'olive extra vierge.",
        "<strong>Garnir.</strong> Mélangez les tomates égouttées avec le basilic ciselé, un peu d'huile d'olive, du sel et du poivre. Répartissez sur le pain juste avant de servir.",
        "<strong>Finir.</strong> Ajoutez un dernier filet d'huile d'olive et quelques feuilles de basilic. Servez aussitôt.",
    ],
    oil="Sur la bruschetta, l'huile d'olive n'est pas un accompagnement : c'est l'ingrédient vedette. Utilisez une <strong>extra vierge fruitée et parfumée</strong>, à cru, à la fois sur le pain grillé et dans la garniture. C'est la recette idéale pour mettre en valeur une belle huile d'olive nouvelle.",
    tips=[
        "Égouttez les tomates : c'est le secret d'une bruschetta non détrempée.",
        "Frottez l'ail sur le pain chaud pour qu'il parfume sans dominer.",
        "Garnissez au dernier moment pour garder le croustillant.",
        "Une huile d'olive de qualité fait toute la différence, ici plus qu'ailleurs.",
    ],
    variations=[
        "<strong>Nature :</strong> pain grillé, ail et huile d'olive seuls (la bruschetta d'origine).",
        "<strong>Balsamique :</strong> quelques gouttes de vinaigre balsamique sur les tomates.",
        "<strong>Autres garnitures :</strong> mozzarella, olives, poivrons grillés, roquette.",
    ],
    serve="Servez la bruschetta en apéritif, en entrée ou en antipasti, aussitôt garnie pour qu'elle reste croustillante. Accompagnez d'un verre de vin et, éventuellement, d'autres bouchées méditerranéennes.",
    store="La bruschetta se mange immédiatement : garnie à l'avance, le pain se détrempe. Vous pouvez préparer les tomates égouttées et griller le pain séparément, puis assembler au moment de servir.",
    faqs=[
        ("Comment éviter une bruschetta détrempée ?",
         "Coupez les tomates, salez-les et laissez-les égoutter pour retirer l'eau, puis garnissez le pain grillé seulement au dernier moment. Un pain bien croustillant résiste mieux."),
        ("Faut-il frotter le pain avec de l'ail ?",
         "Oui, c'est la base de la bruschetta : on frotte la tranche encore chaude avec une gousse d'ail coupée, ce qui parfume sans ajouter d'ail cru en morceaux."),
        ("Quel pain pour la bruschetta ?",
         "Un pain rustique à mie dense : pain de campagne, ciabatta ou pain au levain, coupé en tranches épaisses et bien grillé."),
        ("Quelle huile d'olive pour la bruschetta ?",
         "Une huile d'olive extra vierge fruitée et de qualité, utilisée à cru : c'est l'ingrédient principal, avec le pain et la tomate."),
        ("Peut-on préparer la bruschetta à l'avance ?",
         "Préparez les éléments séparément (tomates égouttées, pain grillé) et assemblez juste avant de servir, sinon la bruschetta ramollit."),
    ],
    schema_name="Bruschetta tomate-basilic",
    schema_desc="Vraie bruschetta tomate-basilic : pain grillé frotté à l'ail, tomates mûres, basilic et huile d'olive extra vierge.",
    schema_ing=["4 tranches de pain de campagne", "3 tomates mûres", "1 gousse d'ail", "basilic frais",
                "4 c. à soupe huile d'olive extra vierge", "sel, poivre"],
    schema_steps=[
        "Couper les tomates en dés, saler et laisser égoutter.",
        "Griller le pain jusqu'à ce qu'il soit croustillant.",
        "Frotter le pain chaud à l'ail et arroser d'huile d'olive.",
        "Mélanger tomates, basilic, huile d'olive, sel et poivre.",
        "Garnir le pain au dernier moment et servir aussitôt."],
    keywords="bruschetta, bruschetta tomate basilic, recette bruschetta, bruschetta huile d'olive, pain grillé italien",
    cuisine="Italian", category="Antipasti", prep="PT15M", cook="PT5M", total="PT20M", yield_="4 servings",
    nutrition={"servingSize": "1 bruschetta", "calories": "160 kcal", "fatContent": "9 g", "proteinContent": "3 g", "carbohydrateContent": "17 g"},
)
B["en"] = dict(
    title="Tomato Basil Bruschetta: the real Italian recipe with olive oil",
    desc="Real tomato basil bruschetta: grilled bread rubbed with garlic, ripe tomatoes, basil and extra virgin olive oil. The trick for crisp bread and tomatoes that don't go soggy.",
    h1="Tomato Basil Bruschetta",
    lede="Authentic bruschetta starts with a good slice of grilled bread, rubbed with garlic and drizzled with extra virgin olive oil. The tomato-basil topping comes after, at the last moment, to keep the crunch.",
    info="<strong>Prep:</strong> 15 min · <strong>Cook:</strong> 5 min · <strong>Serves:</strong> 4 · <strong>Cuisine:</strong> Italian · <strong>Difficulty:</strong> easy",
    intro="Originally, <em>bruschetta</em> is just grilled bread rubbed with garlic and drenched in new olive oil — a way to taste the oil. The tomato-basil version is the best known. Success comes down to two things: good, well-grilled bread and ripe tomatoes added only at the last minute.",
    ingredients=[
        "4 slices of rustic bread (or ciabatta)",
        "3 ripe, firm tomatoes",
        "1 garlic clove",
        "A few fresh basil leaves",
        "4 tbsp extra virgin olive oil",
        "Salt, pepper",
    ],
    steps=[
        "<strong>Prepare the tomatoes.</strong> Dice the tomatoes, remove excess juice and seeds, lightly salt and let them drain in a sieve.",
        "<strong>Grill the bread.</strong> Toast the bread slices in the oven, toaster or a pan until golden and crisp.",
        "<strong>Rub with garlic.</strong> Rub each still-warm slice with the cut garlic clove, then drizzle with extra virgin olive oil.",
        "<strong>Top.</strong> Mix the drained tomatoes with torn basil, a little olive oil, salt and pepper. Spoon onto the bread just before serving.",
        "<strong>Finish.</strong> Add a final drizzle of olive oil and a few basil leaves. Serve at once.",
    ],
    oil="On bruschetta, olive oil is not a side note: it's the star ingredient. Use a <strong>fruity, fragrant extra virgin</strong>, raw, both on the grilled bread and in the topping. This is the ideal recipe to show off a good new-harvest olive oil.",
    tips=[
        "Drain the tomatoes: the secret to bruschetta that isn't soggy.",
        "Rub garlic on the warm bread so it perfumes without dominating.",
        "Top at the last moment to keep the crunch.",
        "A quality olive oil makes all the difference here, more than anywhere.",
    ],
    variations=[
        "<strong>Plain:</strong> grilled bread, garlic and olive oil only (the original bruschetta).",
        "<strong>Balsamic:</strong> a few drops of balsamic vinegar on the tomatoes.",
        "<strong>Other toppings:</strong> mozzarella, olives, grilled peppers, arugula.",
    ],
    serve="Serve bruschetta as an aperitivo, starter or antipasto, topped just before serving so it stays crisp. Pair with a glass of wine and, if you like, other Mediterranean bites.",
    store="Bruschetta is eaten immediately: topped ahead, the bread goes soggy. You can prepare the drained tomatoes and grill the bread separately, then assemble at serving time.",
    faqs=[
        ("How do I stop bruschetta going soggy?",
         "Dice the tomatoes, salt them and let them drain to remove water, then top the grilled bread only at the last moment. Well-crisped bread holds up better."),
        ("Should you rub the bread with garlic?",
         "Yes, it's the base of bruschetta: rub the still-warm slice with a cut garlic clove, which perfumes it without adding raw garlic pieces."),
        ("Which bread for bruschetta?",
         "A rustic bread with a dense crumb: country bread, ciabatta or sourdough, cut into thick slices and well grilled."),
        ("Which olive oil for bruschetta?",
         "A fruity, quality extra virgin olive oil, used raw: it's the main ingredient, along with the bread and tomato."),
        ("Can bruschetta be made ahead?",
         "Prepare the parts separately (drained tomatoes, grilled bread) and assemble just before serving, otherwise the bruschetta softens."),
    ],
    schema_name="Tomato Basil Bruschetta",
    schema_desc="Real tomato basil bruschetta: grilled bread rubbed with garlic, ripe tomatoes, basil and extra virgin olive oil.",
    schema_ing=["4 slices rustic bread", "3 ripe tomatoes", "1 garlic clove", "fresh basil",
                "4 tbsp extra virgin olive oil", "salt, pepper"],
    schema_steps=[
        "Dice tomatoes, salt and let drain.",
        "Grill the bread until crisp.",
        "Rub warm bread with garlic and drizzle with olive oil.",
        "Mix tomatoes, basil, olive oil, salt and pepper.",
        "Top the bread at the last moment and serve at once."],
    keywords="bruschetta, tomato basil bruschetta, bruschetta recipe, bruschetta olive oil, italian grilled bread",
    cuisine="Italian", category="Antipasto", prep="PT15M", cook="PT5M", total="PT20M", yield_="4 servings",
    nutrition={"servingSize": "1 bruschetta", "calories": "160 kcal", "fatContent": "9 g", "proteinContent": "3 g", "carbohydrateContent": "17 g"},
)
B["it"] = dict(
    title="Bruschetta al pomodoro e basilico: la vera ricetta con olio d'oliva",
    desc="Vera bruschetta al pomodoro e basilico: pane abbrustolito strofinato con aglio, pomodori maturi, basilico e olio extravergine d'oliva. Il trucco per pane croccante e pomodori non acquosi.",
    h1="Bruschetta al pomodoro e basilico",
    lede="La bruschetta autentica parte da una bella fetta di pane abbrustolito, strofinata con aglio e irrorata di olio extravergine. Il condimento pomodoro-basilico viene dopo, all'ultimo, per mantenere la croccantezza.",
    info="<strong>Preparazione:</strong> 15 min · <strong>Cottura:</strong> 5 min · <strong>Per:</strong> 4 persone · <strong>Cucina:</strong> italiana · <strong>Difficoltà:</strong> facile",
    intro="In origine la <em>bruschetta</em> è solo pane abbrustolito strofinato con aglio e coperto d'olio nuovo — un modo per assaggiare l'olio. La versione pomodoro-basilico è la più nota. La riuscita dipende da due cose: buon pane ben abbrustolito e pomodori maturi aggiunti solo all'ultimo minuto.",
    ingredients=[
        "4 fette di pane rustico (o ciabatta)",
        "3 pomodori maturi e sodi",
        "1 spicchio d'aglio",
        "Qualche foglia di basilico fresco",
        "4 cucchiai di olio extravergine d'oliva",
        "Sale, pepe",
    ],
    steps=[
        "<strong>Preparare i pomodori.</strong> Taglia i pomodori a dadini, togli succo e semi in eccesso, sala leggermente e lascia scolare in un colino.",
        "<strong>Abbrustolire il pane.</strong> Tosta le fette in forno, nel tostapane o in padella, fino a doratura e croccantezza.",
        "<strong>Strofinare con l'aglio.</strong> Strofina ogni fetta ancora calda con lo spicchio d'aglio tagliato, poi irrora con un filo di olio extravergine.",
        "<strong>Condire.</strong> Mescola i pomodori scolati con basilico spezzettato, un po' d'olio, sale e pepe. Distribuisci sul pane appena prima di servire.",
        "<strong>Finire.</strong> Aggiungi un ultimo filo d'olio e qualche foglia di basilico. Servi subito.",
    ],
    oil="Sulla bruschetta l'olio d'oliva non è un contorno: è l'ingrediente protagonista. Usa un <strong>extravergine fruttato e profumato</strong>, a crudo, sia sul pane sia nel condimento. È la ricetta ideale per valorizzare un buon olio nuovo.",
    tips=[
        "Scola i pomodori: il segreto di una bruschetta non acquosa.",
        "Strofina l'aglio sul pane caldo perché profumi senza dominare.",
        "Condisci all'ultimo per mantenere la croccantezza.",
        "Un olio di qualità fa la differenza, qui più che altrove.",
    ],
    variations=[
        "<strong>Semplice:</strong> pane abbrustolito, aglio e olio d'oliva soli (la bruschetta originale).",
        "<strong>Balsamico:</strong> qualche goccia di aceto balsamico sui pomodori.",
        "<strong>Altri condimenti:</strong> mozzarella, olive, peperoni grigliati, rucola.",
    ],
    serve="Servi la bruschetta come aperitivo, antipasto o stuzzichino, condita appena prima per mantenerla croccante. Accompagna con un bicchiere di vino e, se vuoi, altri bocconi mediterranei.",
    store="La bruschetta si mangia subito: condita in anticipo, il pane si ammorbidisce. Puoi preparare i pomodori scolati e abbrustolire il pane separatamente, poi assemblare al momento.",
    faqs=[
        ("Come evitare una bruschetta acquosa?",
         "Taglia i pomodori, salali e lasciali scolare per togliere l'acqua, poi condisci il pane solo all'ultimo. Un pane ben croccante regge meglio."),
        ("Bisogna strofinare il pane con l'aglio?",
         "Sì, è la base della bruschetta: si strofina la fetta ancora calda con uno spicchio tagliato, che profuma senza aggiungere pezzi di aglio crudo."),
        ("Quale pane per la bruschetta?",
         "Un pane rustico a mollica densa: pane casereccio, ciabatta o pane a lievito madre, a fette spesse e ben abbrustolito."),
        ("Quale olio d'oliva per la bruschetta?",
         "Un olio extravergine fruttato e di qualità, usato a crudo: è l'ingrediente principale con pane e pomodoro."),
        ("Si può preparare in anticipo?",
         "Prepara gli elementi separatamente (pomodori scolati, pane abbrustolito) e assembla appena prima di servire, altrimenti si ammorbidisce."),
    ],
    schema_name="Bruschetta al pomodoro e basilico",
    schema_desc="Vera bruschetta al pomodoro e basilico: pane abbrustolito strofinato con aglio, pomodori maturi, basilico e olio extravergine d'oliva.",
    schema_ing=["4 fette di pane rustico", "3 pomodori maturi", "1 spicchio d'aglio", "basilico fresco",
                "4 cucchiai olio extravergine d'oliva", "sale, pepe"],
    schema_steps=[
        "Tagliare i pomodori a dadini, salare e scolare.",
        "Abbrustolire il pane fino a croccante.",
        "Strofinare il pane caldo con aglio e irrorare d'olio.",
        "Mescolare pomodori, basilico, olio, sale e pepe.",
        "Condire il pane all'ultimo e servire subito."],
    keywords="bruschetta, bruschetta pomodoro basilico, ricetta bruschetta, bruschetta olio d'oliva, pane abbrustolito",
    cuisine="Italian", category="Antipasto", prep="PT15M", cook="PT5M", total="PT20M", yield_="4 porzioni",
    nutrition={"servingSize": "1 bruschetta", "calories": "160 kcal", "fatContent": "9 g", "proteinContent": "3 g", "carbohydrateContent": "17 g"},
)
B["el"] = dict(
    title="Μπρουσκέτα ντομάτα-βασιλικός: η αυθεντική ιταλική συνταγή με ελαιόλαδο",
    desc="Αυθεντική μπρουσκέτα ντομάτα-βασιλικός: ψωμί ψημένο τριμμένο με σκόρδο, ώριμες ντομάτες, βασιλικός και έξτρα παρθένο ελαιόλαδο. Το κόλπο για τραγανό ψωμί και ντομάτες που δεν νερουλιάζουν.",
    h1="Μπρουσκέτα ντομάτα-βασιλικός",
    lede="Η αυθεντική μπρουσκέτα ξεκινά από μια καλή φέτα ψημένο ψωμί, τριμμένη με σκόρδο και περιχυμένη με έξτρα παρθένο ελαιόλαδο. Το τόπινγκ ντομάτα-βασιλικός μπαίνει μετά, την τελευταία στιγμή, για να μείνει τραγανό.",
    info="<strong>Προετοιμασία:</strong> 15 λεπτά · <strong>Ψήσιμο:</strong> 5 λεπτά · <strong>Μερίδες:</strong> 4 · <strong>Κουζίνα:</strong> ιταλική · <strong>Δυσκολία:</strong> εύκολη",
    intro="Αρχικά η <em>μπρουσκέτα</em> είναι απλώς ψημένο ψωμί τριμμένο με σκόρδο και περιχυμένο με νέο ελαιόλαδο — τρόπος να δοκιμάσεις το λάδι. Η εκδοχή ντομάτα-βασιλικός είναι η πιο γνωστή. Η επιτυχία εξαρτάται από δύο πράγματα: καλό, καλοψημένο ψωμί και ώριμες ντομάτες που μπαίνουν μόνο την τελευταία στιγμή.",
    ingredients=[
        "4 φέτες χωριάτικο ψωμί (ή ciabatta)",
        "3 ώριμες, σφιχτές ντομάτες",
        "1 σκελίδα σκόρδο",
        "Λίγα φρέσκα φύλλα βασιλικού",
        "4 κ.σ. έξτρα παρθένο ελαιόλαδο",
        "Αλάτι, πιπέρι",
    ],
    steps=[
        "<strong>Ετοιμάστε τις ντομάτες.</strong> Κόψτε τις ντομάτες σε κυβάκια, αφαιρέστε το περίσσιο ζουμί και σπόρους, αλατίστε ελαφρά και αφήστε να στραγγίσουν σε σουρωτήρι.",
        "<strong>Ψήστε το ψωμί.</strong> Ψήστε τις φέτες στον φούρνο, στην τοστιέρα ή στο τηγάνι, μέχρι να ροδίσουν και να γίνουν τραγανές.",
        "<strong>Τρίψτε με σκόρδο.</strong> Τρίψτε κάθε ζεστή φέτα με την κομμένη σκελίδα σκόρδο, μετά περιχύστε με λίγο έξτρα παρθένο ελαιόλαδο.",
        "<strong>Γαρνίρετε.</strong> Ανακατέψτε τις στραγγισμένες ντομάτες με βασιλικό, λίγο ελαιόλαδο, αλάτι και πιπέρι. Απλώστε στο ψωμί λίγο πριν το σερβίρισμα.",
        "<strong>Ολοκληρώστε.</strong> Προσθέστε λίγο ακόμη ελαιόλαδο και φύλλα βασιλικού. Σερβίρετε αμέσως.",
    ],
    oil="Στη μπρουσκέτα το ελαιόλαδο δεν είναι συνοδευτικό: είναι το πρωταγωνιστικό υλικό. Χρησιμοποιήστε ένα <strong>φρουτώδες, αρωματικό έξτρα παρθένο</strong>, ωμό, τόσο στο ψωμί όσο και στο τόπινγκ. Ιδανική συνταγή για να αναδείξετε ένα καλό νέο ελαιόλαδο.",
    tips=[
        "Στραγγίστε τις ντομάτες: το μυστικό για μη νερουλή μπρουσκέτα.",
        "Τρίψτε το σκόρδο στο ζεστό ψωμί για άρωμα χωρίς να κυριαρχεί.",
        "Γαρνίρετε την τελευταία στιγμή για να μείνει τραγανό.",
        "Ένα ποιοτικό ελαιόλαδο κάνει τη διαφορά, εδώ περισσότερο από αλλού.",
    ],
    variations=[
        "<strong>Σκέτη:</strong> ψημένο ψωμί, σκόρδο και ελαιόλαδο μόνο (η αρχική μπρουσκέτα).",
        "<strong>Βαλσάμικο:</strong> λίγες σταγόνες βαλσάμικο στις ντομάτες.",
        "<strong>Άλλα τόπινγκ:</strong> μοτσαρέλα, ελιές, ψητές πιπεριές, ρόκα.",
    ],
    serve="Σερβίρετε τη μπρουσκέτα ως απεριτίφ, ορεκτικό ή αντιπάστο, γαρνιρισμένη λίγο πριν για να μείνει τραγανή. Συνοδεύστε με ένα ποτήρι κρασί και άλλα μεσογειακά μεζεδάκια.",
    store="Η μπρουσκέτα τρώγεται αμέσως: γαρνιρισμένη από πριν, το ψωμί μαλακώνει. Ετοιμάστε τις στραγγισμένες ντομάτες και ψήστε το ψωμί ξεχωριστά, μετά συνθέστε στο σερβίρισμα.",
    faqs=[
        ("Πώς να μη νερουλιάσει η μπρουσκέτα;",
         "Κόψτε τις ντομάτες, αλατίστε τες και αφήστε τες να στραγγίσουν, μετά γαρνίρετε το ψωμί μόνο την τελευταία στιγμή. Το τραγανό ψωμί αντέχει καλύτερα."),
        ("Πρέπει να τρίβουμε το ψωμί με σκόρδο;",
         "Ναι, είναι η βάση της μπρουσκέτα: τρίβουμε τη ζεστή φέτα με κομμένη σκελίδα, που αρωματίζει χωρίς κομμάτια ωμού σκόρδου."),
        ("Ποιο ψωμί για μπρουσκέτα;",
         "Χωριάτικο ψωμί με πυκνή ψίχα: ζυμωτό, ciabatta ή προζυμένιο, σε χοντρές φέτες και καλοψημένο."),
        ("Ποιο ελαιόλαδο για μπρουσκέτα;",
         "Ένα φρουτώδες, ποιοτικό έξτρα παρθένο ελαιόλαδο, ωμό: είναι το κύριο υλικό μαζί με το ψωμί και την ντομάτα."),
        ("Ετοιμάζεται από πριν;",
         "Ετοιμάστε τα υλικά ξεχωριστά (στραγγισμένες ντομάτες, ψημένο ψωμί) και συνθέστε λίγο πριν το σερβίρισμα, αλλιώς μαλακώνει."),
    ],
    schema_name="Μπρουσκέτα ντομάτα-βασιλικός",
    schema_desc="Αυθεντική μπρουσκέτα ντομάτα-βασιλικός: ψημένο ψωμί τριμμένο με σκόρδο, ώριμες ντομάτες, βασιλικός και έξτρα παρθένο ελαιόλαδο.",
    schema_ing=["4 φέτες χωριάτικο ψωμί", "3 ώριμες ντομάτες", "1 σκελίδα σκόρδο", "φρέσκος βασιλικός",
                "4 κ.σ. έξτρα παρθένο ελαιόλαδο", "αλάτι, πιπέρι"],
    schema_steps=[
        "Κόψτε τις ντομάτες σε κύβους, αλατίστε και στραγγίστε.",
        "Ψήστε το ψωμί μέχρι τραγανό.",
        "Τρίψτε το ζεστό ψωμί με σκόρδο και περιχύστε με ελαιόλαδο.",
        "Ανακατέψτε ντομάτες, βασιλικό, ελαιόλαδο, αλάτι και πιπέρι.",
        "Γαρνίρετε το ψωμί την τελευταία στιγμή και σερβίρετε αμέσως."],
    keywords="μπρουσκέτα, μπρουσκέτα ντομάτα βασιλικός, συνταγή μπρουσκέτα, μπρουσκέτα ελαιόλαδο, ιταλικό ψητό ψωμί",
    cuisine="Italian", category="Ορεκτικό", prep="PT15M", cook="PT5M", total="PT20M", yield_="4 μερίδες",
    nutrition={"servingSize": "1 μπρουσκέτα", "calories": "160 kcal", "fatContent": "9 g", "proteinContent": "3 g", "carbohydrateContent": "17 g"},
)

if __name__ == "__main__":
    write_cluster("aioli-maison-huile-olive", A)
    write_cluster("bruschetta-tomate-basilic", B)
